= Back up a Database Cluster
:description:
:sectnums:

This page walks you through the steps to back up your database cluster.
The process also applies to single-server instances.

Backing up a cluster is an online operation.
Your database remains available during the backup.

Consult xref:system-management:management-commands.adoc[the gadmin Command Glossary] to view the help files for the `gadmin backup` commands.

== Prerequisites
* You have access to the TigerGraph Linux user account on your cluster.
All commands must be run from the TigerGraph Linux user.
* You have provided valid xref:configurations.adoc[configurations for database backup].

== Procedure

=== Data backup

To back up a database cluster, run the following command:

[.wrap,console]
----
$ gadmin backup create <tag>
----

Replace `<tag>` with a custom tag for the backup.
A timestamp is suffixed to the tag you provided to form the full tag of the backup.
If no tag is provided, the system uses the default `backup` followed by the timestamp when the backup is created as the tag for the backup.

For example, run the following command to create a backup for a database cluster:

[.wrap,console]
----
$ gadmin backup create weekly
----

This creates a backup named `weekly-<timestamp>` at the xref:configurations.adoc[backup location you configured].

You can also make `weekly` the entire tag by using the flag `--custom-tag`:
----
$ gadmin backup create weekly --custom-tag
----
This creates a backup named `weekly` without the `-<timestamp>` suffix.
