= Backup and Restore Configurations

This page describes the configuration options available for backup and restore on TigerGraph and how to set them.

== Prerequisites
* You have access to the TigerGraph Linux user account on your cluster.
All commands must be run from the TigerGraph Linux user.

== Configuration parameters

The following is a list of configurations available for backup and restore.

|===
|Configuration parameter |Description |Default

|System.Backup.Local.Enable |Whether to store the database backup data to a local path. *IMPORTANT*: See note at end of table.

If this parameter is set to true, `System.Backup.S3.Enable` cannot be set to true.
|`false`

|System.Backup.Local.Path |Local path to store the backup files.
Required if backup is to be stored locally. |null

|System.Backup.S3.AWSAccessKeyID |AWS access key ID for s3 bucket of
backup.
Required if backup is to be stored on S3. |null

|System.Backup.S3.AWSSecretAccessKey |Secret access key for s3
bucket.
Required if backup is to be stored on S3.

*NOTE*: If setting this in interactive mode, store the key in a file and provide the path to the file, e.g., `@/tmp/test_secret`.
|`+nan+`

|System.Backup.S3.BucketName |Name of the S3 bucket to store backup files.
Required if backup is to be stored on S3.|null

|System.Backup.S3.Enable |Whether to store the database backup data to S3.
Required if backup is to be stored on S3.

If this parameter is set to true, `System.Backup.Local.Enable` cannot be set to true.|`+false+`

|System.Backup.S3.Endpoint | Endpoint to use instead of the S3 default endpoint. Must be a fully qualified URL.
Typically used when operating in a private network or with a non-AWS S3-compatible endpoint. | null

|System.Backup.TimeoutSec |Timeout limit for the backup operation in seconds |`+18000+`

|System.Backup.CompressProcessNumber | Number of concurrent processes for compression during backup.

It's recommended to keep the default value `8`, which means the number of processes used to compress is equal to the number of CPU cores on each node.
| `8`

|System.Backup.DecompressProcessNumber | The number of concurrent processes for decompression during the restore.
| `8`

|System.Backup.CompressionLevel |The backup compression level strikes a balance between size and speed. The better compression, the longer it takes.
("BestSpeed", "DefaultCompression", "BestCompression")
| "DefaultCompression"
|===

IMPORTANT: If `System.Backup.Local.Enable` is set to `true`, this also enables a daily full backup at 12:00am UTC.

== Configure backup and restore

Running `gadmin config entry backup` allows you to enter the value for each parameter individually.

Alternatively, you can also use `gadmin config set <parameter>` to change the value of any parameter.

After configuring the parameters, run `gadmin config apply` to apply the new parameter values.
