= Differential Backup

== Terminology Definition
Full backups comprise entire data backup sets, regardless of already existing backups or data change circumstances.

* Differential backups comprise data files that have changed since the most recently completed full backup.
* Incremental backups involve data files changed since the last incremental backup.

For example, a full backup happened at `tid:100`, a schema change happened at `tid:150` and an differential backup happened at `tid:200`.

== How Differential Backup works

To illustrate how differential backup works, take into account the user scenario below.

.User Scenario
====
. A user creates a full backup every __Sunday__ (Or Day `N`).

. During the week, between the two full backup days (__Sunday__ and __Next Sunday__) TigerGraph provides differential backups.

. A differential backup is taken until the backup data is as large as the backup on __Sunday__
. Another full backup is taken on __Next Sunday__ and the circle repeats steps 2-4.
====

=== Enable Differential Backup

If a user wants to make a full backup _**WITH**_ differential backups run `gadmin backup create` with the `--incremental` flag:

.Ex.
[console, gsql]
----
gadmin backup create <tag> --incremental
----

[NOTE]
====
For more details on `gadmin backup create` see xref:tigergraph-server:backup-and-restore:backup-cluster.adoc#_procedure[Back up a Database Cluster Procedure].
====

To restore a differential backup, users need to find the correct `<tag>` from the backup list.
To see the list of backups, run:

.Ex.
[console, gsql]
----
gadmin backup list
----

This will list all the backup tags.
To restore the specific backup, run:

.Ex.
[console, gsql]
----
gadmin backup restore <differential backup tag>
----

=== Disable Differential Backup

If a user wants to make a full backup _**WITHOUT**_ differential backup enabled, they can do so by excluding the `--incremental` flag in `gadmin backup create`.

.Ex.
[console, gsql]
----
gadmin backup create <tag>
----

== Limitations

Differential backup does have some know limitations:

* Currently, schema change is not yet supported.
This means users cannot run a differential backup, if they have run schema changes since last full snapshot backup.
Users have to run a full snapshot backup first, then they can use differential Backup.

* Currently, restored TigerGraph is not supported yet.
If the TigerGraph was restored from a full snapshot backup, users cannot run a differential backup.
Users have to run a full snapshot backup first, then they can use Differential Backup.

* Open transactions at the full backup happening is not yet supported.
This may cause data lost.

* Kafka reset or kafka purging too often is not yet supported by differential backups.

* Differential Backup must based on last full snapshot backup and cannot be based on a previous days differential backup.
** For example: If a user did a full backup on _Sunday_ and then one differential backup on _Monday_. Then, if the user wants to run a differential backup on _Tuesday_, they will have to base it on _Sunday's_ full backup and save all changes since then.
So part of your__ Tuesday__ differential backup is actually the same as _Monday's_.