= Point-in-Time Restore

The introduction of Point-in-Time Restore in version 4.1.0 is designed to enable users to restore the database to a previous time point, they can provide a timestamp and restore to it using previous made backups, even though no backup has been conducted at exactly that time point.
This feature is based on xref:tigergraph-server:backup-and-restore:differential-backups.adoc[Differential Backup].

== Usage


== Key Benefits

The primary advantage of Point-in-Time Restore is the flexibility it offers in selecting any specific time point on the timeline for restoration.

.Key Benefit Scenario
====
. A user creates a full backup on __Sunday__.

. During the week, user creates a differential backup on every day 10pm.

. On Tursday, user finds there are unwanted changes made on Wednesday around 2pm.

. User can restore system to 1:55pm of Wednesday instead of the backup made on Tuesday 10pm.

. The changes made between Tuesday 10pm and Wednesday 1:55pm are saved this way.
====

Summery of key benefits:

* Precise recover time point to save a much as possible correct work made to database.


== Limitations and Considerations

Currently, the Point-in-Time Restore feature has these known limitations:

* GSQL’s content can not be restored to the version of user provided time point, like catalog(schemas,RBAC). After completion of a point in time restore, its version will be the same as the differential backup used, that is the nearest differential backup covered that time point.
* Accuracy, error range of a couple of minutes. To ensure data consistency, point-in-time restore has an error range of a couple of minutes. So if disaster/unwanted operation happened at a timestamp, user should point in time restore to at least 2 mins in advance.
* Cannot point-in-time restore to a timestamp not covered by a differential backup. A timestamp before the existing earliest full backup cannot be restored to anyway. Other timestamps not covered by an existing differential backup will be reminded to kick off a new differential backup when executing point-in-time restore. After successful completion of the prompted differential backup, user would be able to point in time restore.
** To maximize the potential of Point-in-Time Restore, users are expected to do backups regulary. A good example can be doing weekly full backup and daily differential backup in days between two full backups.


