= The GSQL Shell

The GSQL shell is a fully functional Java environment for interacting with the TigerGraph database. 
It is one of the primary ways to interact with the TigerGraph database and is included in a standard TigerGraph installation. 

== Launch the shell
As the TigerGraph Linux user, type `gsql` into the bash terminal to start a GSQL shell session:

[source,bash]
----
$ gsql
----

If authentication is enabled, you will need to provide credentials in order to launch the shell. 

== Run a GSQL script
You don't always need to enter the interactive shell in order to run a GSQL command. To run a GSQL command non-interactively, run the command `gsql` followed by the GSQL commands you want to run in quotes:

[source,bash]
----
$ gsql 'ls'
----

== Change scope
In the GSQL shell, you can run commands on a global scope or on a local scope. 
When you start a GSQL session, you are in the global scope.
To change to the local scope of a graph, run the `USE GRAPH` command.

[source,GSQL]
----
GSQL > USE GRAPH social
Using graph 'social'
----

To switch back to the global scope, run `USE GLOBAL`. 

[source,GSQL]
----
GSQL > USE GLOBAL
----

Operating on different scopes will require different privileges. 
For more information, see Roles and Privileges. 