= GSQL Shell (Web)
:description: Introduction of the web version of GSQL shell.
:experimental:

TigerGraph provides the GSQL shell through the web as part of xref:master@home:ROOT:index.adoc#_tigergraph_suite[TigerGraph Suite].

The web version of GSQL provides many user-friendly features such as command history, script uploading and downloading, keyboard shortcuts, autocomplete, syntax highlighting, and many more that make the GSQL shell easier to use for developers.

== Supported browsers
TigerGraph has verified support for the GSQL web shell on the following browsers:

* Google Chrome Version 103.0.5060.53 (Official Build) (arm64)
* Safari Version 15.2 (17612.3.6.1.6)
* Firefox Version 102.0.1
* Microsoft Edge Version 104.0.1293.54 (Official build) (arm64)

Please make sure to enable JavaScript and cookies in your browser settings.

== Access GSQL shell via browser
To access the GSQL shell via browser for an on-prem instance, visit the domain or IP address of the instance via port 14240 in your browser:

For example, if your instance is on `localhost`, visit \http://localhost:14240, log in if xref:user-access:enabling-user-authentication.adoc[authentication is enabled], and select btn:[GSQL Shell].

== Run GSQL commands
To run a GSQL command, type the command in the GSQL Editor at the bottom of the screen, and press kbd:[Cmd+Enter] or kbd:[Ctrl+Enter] depending on your OS.

The GSQL editor has multi-line mode enabled by default.
You do not need to enter `BEGIN .. END` in order to run a multi-line command.

=== View results
The results of each command show up in the results panel right above the GSQL editor.

== View command history
You can view a history of the commands that were executed in your session on the left pane of the GSQL web shell.


== Editor keyboard shortcuts

The following is a list of keyboard shortcuts.
Since the web shell is web-based, you also have access to browser keyboard shortcuts (Chrome, Safari, Firefox, Edge).

|===
|Action |macOS |Windows

|Execute command
|kbd:[Cmd+Enter]
|kbd:[Ctrl+Enter]

|Previous command
|kbd:[Cmd+Up]
|kbd:[Ctrl+Up]

|Next command
|kbd:[Cmd+Down]
|kbd:[Ctrl+Down]
|===

== Limitations

The following commands are not supported in the GSQL web shell:

* `CREATE USER`
* `ALTER PASSWORD`
* `EXPORT GRAPH ALL -P`
* `IMPORT GRAPH -P`
* `CLEAR GRAPH STORE -HARD`
* `DROP DATASOURCE`
* `PUT`
* `GET`
