= Welcome to TigerGraph DB
:description:This page provides a brief overview of TigerGraph's key features, the GSQL language, versioning, and internal architecture.
:page-aliases: introduction.adoc

//Introduction and Welcome
TigerGraph, the world's fastest and most scalable graph analytics platform, breaks through the limitations of other graph technologies to enable real-time big data graph applications. 
Lowering costs by getting more done with less storage, less memory, and less time.

To keep up-to-date on key new features of the most recent LTS versions of TigerGraph, please see:

* xref:release-notes:index.adoc[Release Notes - TigerGraph 3.9]
* xref:3.6@tigergraph-server:release-notes:index.adoc[Release Notes - TigerGraph 3.6]

NOTE: To view the documentation of a particular TigerGraph version, use the dropdown in the upper left to pick a specific version.

== Get to Know Your TigerGraph DB
[.home-card,cols="2,2",grid=none,frame=none]
|===
a|
*Internal Architecture*

The TigerGraph Platform runs on standard, commodity-grade Linux servers and is designed in C++ to fit into your existing environment with a minimum of fuss.

xref:internal-architecture.adoc[]
a|
*Multi-graph Overview*

One TigerGraph instance can manage multiple graphs, each with its own set of user privileges.

xref:multigraph-overview.adoc[Multi-graph Overview]

a|
*ACID Transactions*

The TigerGraph distributed database provides full ACID transactions with sequential consistency.

xref:transaction-and-acid.adoc[]

a|
*Continuous Availability*

TigerGraph goes beyond the standard scope and definition of High Availability (HA) and provides Continuous Availability.

xref:tigergraph-server:cluster-and-ha-management:ha-overview.adoc[],
xref:continuous-availability-overview.adoc[]

a|
*Comparing Editions*

Compare what is included in the Enterprise Edition vs. TigerGraph Cloud of the TigerGraph platform.

xref:comparison-of-editions.adoc[]
a|
*Release and Patch Process*

We create a new branch of documentation for every major and minor release.

xref:release-process.adoc[Release and Patch Process].

a|
|===

Go hands on with TigerGraph in the xref:tigergraph-server:getting-started:index.adoc[Getting Started] documentation.
Or explore more of TigerGraph DB's key components below.

== Key Components
[.home-card,cols="2,2",grid=none,frame=none]
|===
a|
*GSQL Language*

The xref:gsql-ref:intro:index.adoc[GSQL™] software program is the TigerGraph comprehensive environment for designing graph schemas, loading and managing data to build a graph, and querying the graph to perform data analysis.

a|
*Data Science Library*

TigerGraph provides a xref:graph-ml:intro:index.adoc[Graph Data Science Library] of expertly written GSQL queries that efficiently implement common graph algorithms.

a|
*Admin Portal and GraphStudio*

xref:gui:intro:index.adoc[] are TigerGraph's graphic user interfaces (GUI).

a|
*TigerGraph Cloud*

xref:cloud:start:overview.adoc[] is a fully-managed cloud database built on the same TigerGraph Enterprise Server engine that is delivering the fastest and most scalable graph database.
|===