= 概要
:description:このページでは、TigerGraphの主な機能、GSQL言語、バージョン管理、内部アーキテクチャーについて簡単に説明します。

世界最速で最もスケーラブルなグラフ分析プラットフォームTigerGraphは、グラフテクノロジーの限界を越えた、リアルタイムのビッグデータグラフ機能を実現します。
また、より少ないストレージ、メモリー、時間でより多くのことを実行できるため、コストの削減も可能です。



== GSQL
GSQL™ソフトウェアプログラムはTigerGraphの包括的な環境で、グラフスキーマの設計、グラフ作成用データの読み込みと管理、データ分析時のグラフのクエリーの実行などを行うことができます。つまりTigerGraphでは、ほとんどの作業をGSQLプログラムを通じて行うことになります。

GSQLについての詳細は、xref:gsql-ref:intro:intro.adoc[GSQL言語についての参考資料]を参照してください。

=== TigerGraphデータサイエンスライブラリ
TigerGraphでは、一般的なグラフアルゴリズムを効率的に実行できる、専門的に記述された数々のGSQLクエリーを提供しています。
詳細については、xref:graph-ml:intro:overview.adoc[TigerGraphグラフデータサイエンスライブラリ]をご覧ください。

== GraphStudioと管理ポータル
GraphStudioと管理ポータルはTigerGraphのグラフィックユーザーインターフェイスです。

TigerGraph GraphStudio™ UI(ユーザーインターフェイス)は、直感的なブラウザーベースのインターフェイスを提供します。これにより、グラフスキーマの設計、スキーママッピングの作成、データの読み込み、グラフの探索、書き込みやGSQLクエリーの作成などのグラフベースのアプリケーション開発タスクをすばやく始めることができます。 

TigerGraphの管理ポータルはブラウザーベースのDevOpsツールであり、アプリケーションとインフラストラクチャーの観点から、実行中のTigerGraphシステムの概要を知ることができます。また、使いやすいインターフェイスを通してTigerGraphシステムの設定を行うことができます。

GraphStudioと管理ポータルについての詳細は、xref:gui:graphstudio:overview.adoc[GraphStudioと管理ポータル]をご覧ください。

== TigerGraph Cloud
TigerGraph Cloudは、フルマネージドのクラウドデータベースで、最速で最もスケーラブルなグラフデータベースを提供しているTigerGraph Enterpriseサーバーのエンジン上に構築されています。
TigerGraph Cloudは、複雑なデプロイやデプロイ管理を、お使いのクラウドサービスプロバイダー(AWS、Azure、GCP)ですべて処理できます。

詳細については、xref:cloud:start:overview.adoc[こちら]をご覧ください。

== バージョニング
TiGerGraphは https://semver.org/[セマンティックバージョニング] を使用しています。``メジャー.マイナー.パッチ``で構成されるバージョン番号には次のようなルールがあります。 

* ``メジャー``バージョン: 以前のメジャーバージョンと互換性のないAPIの変更が行われたとき、``メジャー``バージョンが上がります
* ``マイナー``バージョン: 下位互換性のある機能が追加されたとき、 ``マイナー``バージョンが上がります
* ``パッチ``バージョン: 下位互換性のあるバグ修正を行ったとき、 ``パッチ``バージョンが増加します。

メジャーリリース、マイナーリリースごとに、新しいドキュメントのブランチを作成しています。
TigerGraphのバージョンのドキュメントを見るには、ページの右上、ナビバーの下にあるバージョンセレクターを使います。
また、ページ左下のコンポーネントバージョンセレクターで、別のコンポーネントやバージョンに切り替えることができます。

== アーキテクチャーの概要
TigerGraphプラットフォームは、標準のコモディティグレードのLinuxサーバーで動作します。
コアコンポーネント(GSEおよびGPE)は、最適なパフォーマンスを実現するためにC++で設定されています。TigerGraphのシステムは、最小限の手間でお使いの環境に適合するように設計されています。

* データソース: プラットフォームには、フレキシブルで高性能なデータローダーを備えており、システムがオンラインのときに表形式または半構造化データをストリーミングできます。
* インフラストラクチャー: プラットフォームは、オンプレミス、クラウド、またはハイブリッドで使用できます。
* 統合: TigerGraphを既存のエンタープライズデータインフラストラクチャーおよびワークフローと統合できるよう、REST APIが提供されています。

TigerGraphのシステムは、メッセージパッシングデザインを使用し、コンポーネントのアクティビティを調整します。強化されたRESTfulサーバーであるRESTPPが、タスク管理の中心となります。以下の通り、システムとの対話方法の選択が可能です。
GSQLクライアント - 1つのTigerGraphインスタンスは、リモートノードで複数のGSQLクライアントをサポートできます。
GraphStudio - 基本的なGSQL機能のほとんどが使用できる、視覚的・直感的なグラフィカルユーザーインターフェイスです。 
RESTAPI - 同じクエリーを多数回実行する必要があるエンタープライズアプリケーションは、RESTPPと直接通信することにより、効率を最大限に高めることができます。
gAdminはシステム管理に使用されます。

== 主要な特長
=== ハイパフォーマンス
TigerGraphは、データ取り込みとクエリーをハイパフォーマンスで行います。特長は以下の通りです。

* グラフ作成のための高速データ読み込み - マシン1台、1時間当たり、50〜150GBのデータを読み込めます。
* 並列グラフアルゴリズムの高速実行 - マシン1台、1秒当たり数億の頂点/エッジをトラバースできます。
* RESTを使用したリアルタイムの更新と挿入 - わずか20台のコモディティマシンのクラスター上で、1,000億以上の頂点と6,000億以上のエッジを持つグラフにリアルタイムで20億以上のデイリーのイベントをストリーミングできます。
* リアルタイム分析を大規模なオフラインデータ処理と統合する機能を持つ、画期的なシステムです。

=== 高機能なクエリー言語
TigerGraphのGSQLは、チューリング完全な言語で、大規模なグラフの探索と分析が可能です。

=== 継続的可用性
TigerGraphの性能は、高可用性(High Availability = HA)の標準的な範囲と定義を高く上回っています。継続的可用性を提供するため、次の機能を備えています。

* データベースサーバーの損失に対するフォールトトレランス
** クラスター内障害に対するサービスの自動回復
* ユーザー用アプリケーションの完全なネイティブHAサポート
** スタンバイGSQLサーバーおよびGraphStudioサーバーへのシームレスな自動クライアント再接続
* 障害リカバリー中のリモートクラスターへのフェイルオーバー
* 追加レプリカでRoIを改善
** クエリースループットパフォーマンスを強化
** 運用ワークロードの同時実行性の向上

=== ACIDトランザクション
TigerGraph分散データベースは、逐次一貫性を備えた完全なACIDトランザクションを実現します。

