= TigerGraph Release Cycle
:description:This page explains TigerGraph's release process and patch naming conventions.

TigerGraph follows a release cadence that allows us to regularly deliver product and service improvements in the form of new features, enhancements, bug fixes and security patches.

In summary, the TigerGraph release types are:

* Feature releases
* Long-term support (LTS) releases
* Maintenance releases

This document describes the process we follow for these three types of releases.


== Naming convention
For all releases, we use https://en.wikipedia.org/wiki/Software_versioning[sequence-based identifiers] in the format *major.minor.patch*.

Here, *major* is a number and increment for the most significant releases, *minor* is an incrementable number for less significant releases, and *patch* is a number for the maintenance release.

For example, in the release version *3.5.2*, the major version is 3, the minor version is 5, and the patch version is 2.

Our documentation (found at https://docs.tigergraph.com/https://docs.tigergraph.com/[docs.tigergraph.com]) is updated with a new branch when the major or minor version number changes.
We do not provide a new documentation branch for patch releases. Instead, we may update the corresponding *major.minor* version’s documents.

== Release types

=== Feature release

A feature release is a planned product roadmap release, where either the major or the minor number in the release version name is changed.
Feature releases are for fast testing and adoption of new features to test in development environments.
We do not suggest using feature releases in a production environment.

A feature release's name is usually *major.minor.0*, abbreviated as *major.minor*.
It may include any of the following:

* New features
* Feature enhancements or updates
* Bug fixes

In addition, the following documentation deliverables accompany a feature release:

* xref:release-notes:index.adoc[] section included in the TigerGraph online documentation.
* xref:installation:upgrade.adoc[Upgrade] section included in the TigerGraph online documentation.
* Updated TigerGraph online documentation for each new feature release version.

==== Notification
Full releases will be announced on our documentation website.
TigerGraph’s Customer Success team will also proactively share the release notes with existing customers.

==== Maintenance
Each feature release will get a maintenance release three months after the initial release.

NOTE: The schedule for maintenance releases is flexible.
For example, if a critical issue is discovered, a maintenance release might come earlier than three months.
If no issues are discovered, a maintenance release might come later.

=== LTS release
Every third feature release is a long-term support (LTS) release.
An LTS release is essentially a feature release that TigerGraph commits to maintaining for a longer period of time.
Just like a feature release, an LTS release is also a planned product roadmap release, where either the major or the minor number in the release version name is increased.

An LTS release's name is usually *major.minor.0*, abbreviated as *major.minor*.
It may include any of the following:

* New features
* Feature enhancements or updates
* Bug fixes

In addition, the following documentation deliverables accompany a feature release:

* xref:release-notes:index.adoc[] section included in the TigerGraph online documentation.
* xref:installation:upgrade.adoc[Upgrade] section included in the TigerGraph online documentation.
* Updated TigerGraph online documentation for each new LTS release version.

==== Notification
LTS releases are announced on our documentation website.
TigerGraph’s Customer Success team will also proactively share the release notes with existing customers.

==== Maintenance
Each LTS release will get a maintenance release three months after the initial release.
After the first maintenance release, an LTS release continues to get maintenance releases every two month for at least four more releases.

For example, with 3.9 as a LTS release, it gets a maintenance release - 3.9.1 -
three months after 3.9.0.
After 3.9.1, the 3. LTS release continues to get maintenance releases every two months until 3.9.5.
This ensures that each LTS version continues to be maintained for at least 12 months.

NOTE: The schedule for maintenance releases is flexible.
For example, if a critical issue is discovered, a maintenance release might come earlier than three months.
If no issues are discovered, a maintenance release might come later.

=== Maintenance release

A maintenance release is a release version that only includes fixes for a feature release or an LTS release.

==== Notification
Maintenance releases are announced on our documentation website in a subsection of the Release Notes.
TigerGraph’s Customer Success team will proactively share the release notes with existing customers.

==== Upgrades
The maintenance release upgrade process is the same as the upgrade guidance in a Full release, as documented in the xref:installation:upgrade.adoc[Upgrade] section of the documentation.
Depending on the urgency of the patch, our Customer Success team may reach out to customers to discuss the upgrade of a Patch release.