= TigerGraph Release And Patch Process
:description:This page explains TigerGraph's release process and patch naming conventions.

Updated March 6, 2023

== Versions and Support

TigerGraph is committed to providing the most scalable, most reliable, most secure, and highest performing enterprise-grade graph database.

=== LTS Version

To provide users with a long and stable product lifecycle, we designate certain versions of the product as LTS (Long Term Support) versions.
We commit to providing 24 months of maintenance releases, critical issue patches, and technical https://www.tigergraph.com/support-policy[product support] for LTS versions, starting from their initial release.
We expect to release up to two (2) new LTS versions per year.

=== Preview Version

In between LTS versions, we will release Preview versions that introduce previews of new features.
Preview versions enable users to get an early look at upcoming features and to provide feedback to TigerGraph.
Preview versions are not covered by the https://www.tigergraph.com/support-policy[Product Support Policy] and therefore are not suitable for production use.

TigerGraph Cloud will offer users a choice of either the latest LTS version or the latest Preview version.

In summary, TigerGraph has the following types of Versions and Releases:

. LTS Version
** Supported for 24 months after initial release
** Will receive Maintenance releases and critical patches
. Preview Version
** Introduces early versions of new features
** Not covered by Support Policy

== Release Numbering and Terminology

=== Version vs. Release

*Version* refers to a feature set, not a particular release.
A Version comprises an initial release containing new features, plus its subsequent Maintenance releases.
So, a version may include a series of releases.

* For example, Version 3.6 encompasses release 3.6.0, 3.6.1, and any future 3.6.x releases.
Release 3.7.0 starts Version 3.7.
* Our documentation is organized by Version.

=== Release Numbering

TigerGraph uses a 3-part numbering scheme:
`<Generation>.<Feature>.<Maintenance>`

*Generation and Feature Releases*

The initial release of either an LTS Version or a Preview Version is a Feature Release. Every year or two, the changes are significant enough that we designate the new version as a new Generation.

* If it is a new generation, we increment `<Generation>` and reset `<Feature>.<Maintenance>` to 0.0.
Upgrading may take some migration effort, and some features may  not be backwardly compatible.
* If it is a Feature Release within the same generation, then we increment `<Feature>` and reset `<Maintenance>` to 0.
We strive for backward compatibility so that existing applications built on the previous feature version will continue to work without modification.

*Maintenance Release*

While we work hard to release high-quality, well-tested software, some bugs or unexpected behaviors do occur. Maintenance releases provide bug fixes, security patches, performance improvements, and other improvements.
They are not intended to introduce new features, unless the features are directly related to quality and stability improvement.
A maintenance release keeps `<generation>.<feature>` the same and increments `<maintenance>`.
LTS versions will have maintenance releases for 2 years.

For example, in the release *3.6.1*, the generation is 3, the feature version is 3.6, and the patch version is 1.

*Patch*

TigerGraph may provide a patch for an existing release that may or may not impact all customers.
These are used to address security vulnerabilities or critical bugs in a timely manner.



Our documentation (found at https://docs.tigergraph.com/https://docs.tigergraph.com/[docs.tigergraph.com]) is updated with a new branch when the major or minor version number changes.
We do not provide a new documentation branch for patch releases. Instead, we may update the corresponding feature version’s documents.

== Deliverables

=== Feature Release

A feature release is a planned product roadmap event. In addition to the software, the following documentation deliverables accompany the release:

* xref:release-notes:index.adoc[] section included in the TigerGraph online documentation.
* xref:installation:upgrade.adoc[Upgrade] section included in the TigerGraph online documentation.
* A complete new branch in the TigerGraph online documentation for that product version.

*Notification:* Feature releases will be announced on our documentation website.
TigerGraph’s Customer Success team will also proactively share the release notes with existing customers.

*Upgrade Support:* Customers using an older version should refer to the upgrade section of the online documentation and should https://tigergraph.zendesk.com/hc/en-us/[open a support ticket] for assistance.

=== Maintenance Release

A Maintenance release provides fixes and improvements for a particular feature version.
The release cycle varies, depending on the number and severity of issues that have been detected and addressed.

*Notification:* Maintenance releases are announced on our documentation website in a subsection of the Release Notes.
TigerGraph’s Customer Success team will proactively share the release notes with existing customers.

*Upgrade Support:* Users should refer to the xref:installation:upgrade.adoc[Upgrade] section of the documentation. Depending on the urgency of the patch, our Customer Success team may reach out to customers to discuss upgrading.

=== One-Off patches

In some instances, a One-Off patch is released to address critical security issues or critical bugs.
Unlike Maintenance releases, a one-off patch is usually an urgent point fix, meaning that it will not wait for other fixes.

One-off patches are released as the situation demands.
They could be universal, applicable to all customers, or specific, applicable to a handful of customers who have deployed a TigerGraph product under a certain environment.

*Notification:* As a One-Off patch is being developed, the Customer Success team will reach out to the affected customers to inform them of the discovered issue and the immediate remediation plan while the patch is under development.

*Application of the patch:* After the patch is developed and has gone through the release certification process, the technical support team will email customers instructions on downloading and applying the patch.

*Post-release:* The patch will be merged in to future maintenance and feature releases. Given the additional time before those releases, the patch may be replaced with an improved solution to the problem.

=== Support

Customers who need assistance can open a support ticket at https://tigergraph.zendesk.com/hc/en-us/[TigerGraph's ZenDesk Portal].

== Managed Service

For customers who subscribe to TigerGraph’s Managed Service, our Cloud Engineering team will apply upgrades for backward compatible changes or One-Off patches transparently when the release is available or during the customer-notified system maintenance window (in situations requiring system downtime).

For releases with non-backward compatible changes, the TigerGraph Customer Success team will reach out to customers to discuss opt-out or opt-in choices.

Should the customer choose to opt-in, our Cloud Engineering team will coordinate and perform the upgrade for the customer.


