= Data Streaming Connector
:description: A guide to TigerGraph's Streaming Data Connector.
:sectnums:

TigerGraph Data Streaming Connector is a link:https://docs.confluent.io/home/connect/overview.html[Kafka connector] that provides fast and scalable data streaming between TigerGraph and other data systems.

== Supported data systems
The data streaming connector supports the following data systems:

* Google Cloud Storage (GCS)
* Apache Kafka

== Stream data from Google Cloud Storage
You can create a data connector between TigerGraph's internal Kafka server and your GCS service with a specified topic.
The connector will stream data from the data source in your GCS buckets to TigerGraph's internal Kafka cluster.
You can then create and run a loading job to load data from Kafka into the graph store using the xref:kafka-loader/index.adoc[Kafka loader].

Before you begin, make sure the following prerequisites are met:

* Your source data files are stored in Google Cloud Storage buckets.
* You have link:https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating[generated a key that has access to your source data from your Google Cloud Platform service account].


=== Specify connector configurations
The connector configurations provide the following information:

* Connector class
* Your GCP service account credentials
* Information on how to parse the source data
* Mapping between connector and source file

==== Specify connector class
The connector class indicates what type of connector the configuration file is used to create.
Connector class is specified by the `connector.class` key.
For connecting to GCS, its value is set to `com.tigergraph.kafka.connect.filesystem.FsSourceConnector`.

==== Provide GCP account credentials
You need to provide following information for the connector to access the files in your GCS bucket.
You should be able to find all items on this list in your link:https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating[service account key]:

* `file.reader.settings.fs.gs.auth.service.account.email`: The email address associated with the service account
* `file.reader.settings.fs.gs.auth.service.account.private.key.id`: The private key ID associated with the service account used for GCS access.
* `file.reader.settings.fs.gs.auth.service.account.private.key`: The private key associated with the service account used for GCS access.
* `file.reader.settings.client_email`:
The service account email.
* `file.reader.settings.fs.gs.project.id`: Google Cloud Project ID with access to GCS buckets.
* `file.reader.settings.fs.gs.auth.service.account.enable`: Whether to create objects for the parent directories of objects with `/` in their path. For example, creating `gs://bucket/foo/` upon deleting or renaming `gs://bucket/foo/bar`.
* `file.reader.settings.fs.gs.impl`: The FileSystem for gs: (GCS) uris.
The value for this configuration should be `com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem`.
* `file.reader.settings.fs.AbstractFileSystem.gs.impl`: The AbstractFileSystem for `gs:` (GCS) URIs. Only necessary for use with Hadoop 2.
The value for this configuration should be `com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS`.

==== Specify parsing rules
The streaming connector supports the following file types:

* CSV files
* JSON files.
Each JSON object must be on a separate line.
* directories
* tar files
* zip files

For URIs that point to directories and compressed files, the connector looks for all files inside the directory or the compressed file that match the `file.regexp` parameter.
By default, this includes both CSV and JSON files.

If you set `file.recursive` to true, the connector looks for files recursively.


The following parsing options are available:


|===
|Name |Description |Default

|`file.regexp`
|The regular expression to filter which files to read.
The default value matches all files.
|`.*`

|`file.recursive`
|Whether to retrieve files recursively if the URI points to a directory.
|`true`

|`file.reader.type`
|The type of file reader to use.
The only supported value is `text`.
|`text`

|`file.reader.delimited.separator`
|The character that separates columns.
This parameter does not affect JSON files.
|`,`

|`file.reader.delimited.quote`
a|The explicit boundary markers for string tokens, either single or double quotation marks.
This parameter does not affect JSON files.

The parser will not treat separator characters found within a pair of quotation marks as a separator.

Accepted values:

* `single`: single quotes `'` are boundary markers.
* `double`: double quotes `"` are boundary markers.
* Empty string `""`: Quotation marks are treated as ordinary characters.
| Empty string `""`

|`file.reader.delimited.value.default`
|The default value for a column when its value is null.
This parameter does not affect JSON files.
| Empty string `""`

|`file.reader.batch.size`
|The maximum number of lines to include in a single batch.
|`1000`

|`file.reader.text.eol`
|End of line character.
|`\n`

|`file.reader.text.header`
|Whether the first line of the files is a header line.
If you are using JSON files, set this parameter to false.
|`false`

|`file.reader.text.archive.type`
a|File type for archive files.
Setting the value of this configuration to `auto` will allow the connector to decide file types automatically based on the file extensions.
Accepted values:

* `tar`
* `zip`
* `gzip`
* `none`
* `auto`
|`auto`

|`file.reader.text.archive.extensions.tar`
|If a file has this extension, treat it as a tar file
|`tar`

|`file.reader.text.archive.extensions.zip`
|If a file has this extension, treat it as a zip file
|`zip`

|`file.reader.text.archive.extensions.gzip`
|If a file has this extension, treat it as a gzip file
|`gz`, `tgz`
|===


==== Map source file to connector
The below configurations are required:

|===
|Name |Description |Default

| `name`
| Name of the connector.
| None. Must be provided by the user.

| `topic`
| Name of the topic to create in Kafka.
| None. Must be provided by the user.

|`tasks.max`
|The maximum number of tasks which can run in parallel.
|1

|`file.uris`
|The path(s) to the data files on Google Cloud Filestore.
The URI may point to a CSV file, a zip file, a gzip file, or a directory
|None.
Must be provided by the user.
|===

Below is an example configuration:

[,text]
----
connector.class=com.tigergraph.kafka.connect.filesystem.FsSourceConnector
file.reader.settings.fs.gs.auth.service.account.email=gcsconnect@example.iam.gserviceaccount.com
file.reader.settings.fs.gs.auth.service.account.private.key.id=55c1d79a46c1f3f598ec38
file.reader.settings.fs.gs.auth.service.account.private.key="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDSqbYRwD68FvA7\nLkC1HpjrJ9QIJ+iOyQPFeSoI+3pjmVTrX2B2aYIMByNubV6Js+n1x5ro/XW0nt3y\nk/BAn8BgaYita8\nIAhLLOf/kFmFmmlM2k02iAZPIBjFvAs7ChGEHsXecQKBgQDq9AKPXaMOiy43EzHPf5JiDeMAMeltz
...
\nokX4AaXPZj5lOmhEii9V8oIa1msPE5AmGrRmQhhI82xVIdnrbVItZcOIUd+Tbs2K\nJZzA2Spvo3yxi2nFptqRk/xi2/8sVXQ8XllQs6UbAoGAdqnrlEAIlCb5hdVNrLXT\nToqdq54G9g82L8/Y+WraqJSNOFKXCGQvC2N16ava4sZ65DCjT6FnCR/UhYS7Z6Vf\nR5EtMRYAyAcyn3g9tcfzINmEbpvwpHBqsr1xPcrfx/WRurIC6EBgLPgX+lALBI0G\n+Uu87tgHhcGFJfmQMQNeQWM=\n-----END PRIVATE KEY-----\n"
file.reader.settings.client_email="gcsconnect@example.iam.gserviceaccount.com"
file.reader.settings.fs.gs.project.id="example"
file.reader.settings.fs.gs.auth.service.account.enable=true
file.reader.settings.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
file.reader.settings.fs.AbstractFileSystem.gs.impl="com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"

mode=eof
file.regexp=".*"
file.recursive=true
file.reader.type=text
file.reader.batch.size=10000
file.reader.text.eol="\\n"
file.reader.text.header=true
file.reader.text.archive.type=auto
file.reader.text.archive.extensions.tar=tar
file.reader.text.archive.extensions.zip=zip
file.reader.text.archive.extensions.gzip=tar.gz,tgz

[connector_person]
name = fs-person-demo-104
tasks.max=10
topic=person-demo-104
file.uris=gs://example/p.csv

[connector_friend]
name = fs-friend-demo-104
tasks.max=10
topic=friend-demo-104
file.uris=gs://example/f.csv
----

include::partial$create-connector.adoc[]

include::partial$create-data-source.adoc[]

include::partial$create-loading-job-kafka.adoc[]

For example, suppose we have the following two CSV files and schema:

[tabs]
====
Schema::
+
--
[,gsql]
----
CREATE VERTEX person (PRIMARY_ID name STRING, name STRING, age INT, gender STRING, state STRING)
CREATE UNDIRECTED EDGE friendship (FROM person, TO person, connect_day DATETIME)
CREATE GRAPH social (person, friendship)
----
--
p.csv::
+
--
[,csv]
----
name,gender,age,state
Tom,male,40,ca
Dan,male,34,ny
Jenny,female,25,tx
Kevin,male,28,az
Amily,female,22,ca
Nancy,female,20,ky
Jack,male,26,fl
A,male,29,ca
----
--
f.csv::
+
--
[,csv]
----
person1,person2,date
Tom,Dan,2017-06-03
Tom,Jenny,2015-01-01
Dan,Jenny,2016-08-03
Jenny,Amily,2015-06-08
Dan,Nancy,2016-01-03
Nancy,Jack,2017-03-02
Dan,Kevin,2015-12-30
Amily,Dan,1990-1-1
----
--
====


The following topic-partition configurations and loading job will load the two CSV files into the graph:

[tabs]
====
topic_person.json::
+
--
[,json]
----
{
  "topic": "person-demo-104",
  "partition_list": [
    {
      "start_offset": -2,
      "partition": 0
    }
  ]
}
----
--
topic_friend.json::
+
--
[,json]
----
{
  "topic": "friend-demo-104",
  "partition_list": [
    {
      "start_offset": -2,
      "partition": 0
    }
  ]
}
----
--
Loading job::
+
--
[.wrap,gsql]
----
CREATE LOADING JOB load_person FOR GRAPH social {
    DEFINE FILENAME f1 = "$k1:/home/mydata/topic_person.json";
    DEFINE FILENAME f2 = "$k1:/home/mydata/topic_friend.json";
    LOAD f1 TO VERTEX person VALUES ($0, $0, $2, $1, $3) USING separator=",";
    LOAD f2 TO EDGE friendship VALUES ($0, $1, $2)  USING separator=",";
}
----
--
====

==== Run loading job
Run the loading job created in the last step will load the streamed data into the graph.
If you make changes to the topic-partition configuration file, you can overwrite the values for the filename variables with xref:gsql-ref:ddl-and-loading:running-a-loading-job.adoc#_run_loading_job[the `USING` clause].

[,gsql]
----
GSQL > RUN LOADING JOB load_person
----

By default, loading jobs that use Kafka data sources run in streaming mode and do not stop until manually aborted.
As data is streamed from the data source, the running loading job will continuously ingest the streamed data into the graph store.

=== Stream data source updates

To load updates to the data source after you've created the connectors, you need to delete the connector and recreate another connector.

In the future, the streaming data connector will support automatically scanning for updates and stream data to TigerGraph.

== Stream data from an external Kafka cluster
You can create a data connector between an external Kafka cluster (source cluster) and TigerGraph’s internal Kafka server (destination cluster) to stream data from the source cluster.
The connector streams the Avro data to TigerGraph's internal Kafka server, and transforms the data into JSON format.
You can then create and run a loading job to load data from Kafka into the graph store using the Kafka loader.

Before you begin, make sure the following prerequisites are met:

* Your TigerGraph instance has access to your external Kafka cluster

=== Specify connector configurations

The data streaming connector for external Kafka data is based on Apache Kafka MirrorMaker and shares many configurations as MirrorMaker.

TO DO: explain what the important configurations are? What are the mandatory ones and what are the ones that users can usually go with the default values

=== Specify SSL/SASL configurations (optional)
If the source cluster has configured SSL or SASL protocols, you need to provide SSL/SASL configurations to the connector in order to communicate with the source connector. 

include::partial$create-connector.adoc[]

include::partial$create-data-source.adoc[]

include::partial$create-loading-job-kafka.adoc[]

For example, suppose we have the following graph schema with only one vertex type
 and the following JSON line data in Kafka:

[tabs]
====
Schema::
+
--
[.wrap,gsql]
----
CREATE VERTEX Company (primary_id name STRING, employee_num INT)
CREATE GRAPH Company_Graph (Company)
----
--
Data::
+
--
[.wrap,json]
----
{"company":"TigerGraph","employee_num":346}
{"company":"Apple","employee_num":373704}
{"company":"Google","employee_num":277618}
----
--
====

To create the loading job, we start by creating a data source configuration file and point it to the Kafka cluster and create the data source:

[tabs]
====
Data source configuration::
+
--
[.wrap,json]
----
    {
        "broker":"localhost:30002",
        "kafka_config":
            {
                "group.id": "tigergraph"
            }
    }
----
--
Create data source::
+
--
Run the following command in GSQL and replace `<path_to_datasource_file` with the absolute path to your data source file to create the data source.
[.wrap,gsql]
----
CREATE DATA_SOURCE KAFKA k1=<path_to_datasource_file>
----
--
====

Then we create a topic-partition configuration file, and then write the loading job.
In the `LOAD` statement, map the JSON line fields to the corresponding attributes of the vertex types:

[tabs]
====
Topic-partition configuration file::
+
--
[.wrap,json]
----
{
    "topic": "Hello.avro-with-registry-topic",
    "default_start_offset": -2
}
----
--
Loading job::
+
--
[.wrap,gsql]
----
CREATE LOADING JOB load_company FOR GRAPH Company_Graph {
    DEFINE FILENAME f1 = "$k1:<path_to_topic_partition_configuration>}";
    LOAD f1 TO VERTEX company VALUES ($"company", $"employee_num") USING JSON_FILE="true";
}
----
--
====

Once the loading job is created, run the loading job to load data into the graph:

[.wrap,gsql]
----
RUN LOADING JOB -noprint load_company USING EOF="true"
----





== Manage connectors

After creating a connector, you can choose to delete it or pause it.
You can also use `gadmin` commands to view status of all existing connectors.

=== List connectors
You can list all running connectors or view detailed configuration of a specific connector.

To view a list of all connectors, run `gadmin connector list` from your bash terminal as the TigerGraph Linux user.

To view configuration details of a specific connector, run `gadmin connector list <name_of_connector>` and replace `<name_of_connector>` with the name of the connector you want to inspect.

=== Pause a connector
Pausing a connector stops the connector from streaming data from the data source.
The data that has been streamed to TigerGraph's internal Kafka can still be loaded into the graph store via a loading job.

To pause a connector, run the below command and replace `<connector_name>` with the name of the connector:

[,console]
----
$ gadmin connector pause <connector_name>
----

=== Resume a connector
Resuming a connector resumes streaming for a paused connector.

To resume a connector, run the below command and replace `<connector_name>` with the name of the connector:

[,console]
----
$ gadmin connector resume <connector_name>
----

=== Delete a connector
Deleting a connector removes a connector.
It stops the connector from streaming, but the data that has been streamed to Kafka can still be ingested by a loading job.
This action cannot be undone and a removed connector cannot be resumed.

To delete a connector,  run the below command and replace `<connector_name>` with the name of the connector:

[,console]
----
$ gadmin connector delete <connector_name>
----