= Data Loading High Availability (HA) BETA
:page-aliases:

NOTE: This is currently a beta feature

Data Loading High Availability (HA) provides load balancing and automatic fail over in the event of a service disruption.

The new data loading mode Data Loading V2 (Beta) provides support for the HA feature.

== `Setup`
First, set up a cluster with replication factor greater than 1 following xref:cluster-and-ha-management:ha-cluster.adoc[High Availability Cluster Configuration]

Second, enable Kafka Connect V2 using `gadmin` commands.
[source, bash]
----
gadmin config set KafkaConnect.EnableV2 true
----

Then run config apply and restart dependency services.

[source, bash]
----
gadmin config apply --restart-deps
----

== `Run Loading Job`
You can now run any loading job as usual following these instructions xref:data-loading:data-loading-overview.adoc[]

== `Configuration`

[separator=¦ ]
|===
¦ Key ¦ Default Value ¦  Description ¦ Note

¦ `batch.size.bytes`
¦ 0 (infinite)
¦ The data size to be broken into if data in batch.size.rows is larger than batch.size.bytes. Example, each row of data is 1kb, and batch.size.rows = 10, batch.size.bytes = 5000, the data will be split into 2 5kb batches.

Example usage: `DEFINE FILENAME file_Comment = """$s1:{"file.uris":"gs://data/Comment", "batch.size": 10000, "batch.size.bytes": 4000000}""";`

¦ Only takes effect if data loading V2 is enabled

|===

NOTE: Modifying security configs such as Nginx SSL while loading job is running may cause failure of the loading job