= Data Loading
:description: Introduction to data loading and data loaders in TigerGraph.
:page-aliases: README.adoc, data-loading.adoc, readme.adoc

Once you have defined a graph schema, you can load data into the graph store.
The data loading process varies based on where the data files are located relative to the TigerGraph server.

If you are loading from files that exist locally on a TigerGraph server, xref:gsql-ref:ddl-and-loading:creating-a-loading-job.adoc[create a loading job] in GSQL to load from the files directly.

Loading data from an outside source, such as cloud storage, is a multi-step process:

. Define a data source.
. Create a loading job.
. Run the loading job.

== GSQL loading jobs

GSQL uses a user-provided configuration file to automatically set up a streaming data connection and a loading job for data in these external cloud data hosts:

* Google Cloud Storage (GCS)
* AWS S3
* Azure Blob Storage (ABS)

Go to the xref:data-streaming-connector/index.adoc[] main page for instructions on setting up the loading job.

== Manual connector setup
For data stored in the following data systems, you need to perform a few more steps to set up data streaming.
Each of these pages has its own separate instructions.

* xref:data-streaming-connector/kafka.adoc[Apache Kafka]
* xref:data-streaming-connector/big-query.adoc[Google BigQuery]
