= Data Loading
:description: Outline of data loading
//:page-aliases: README.adoc, data-loading.adoc, readme.adoc

There are various ways to load data in TigerGraph. Here you can find an overview and detailed instructions for the loading method that fits your needs.

== xref:data-loading-overview.adoc[Overview of Data Loading]

Available loading methods and supported features.
Start from this page to pick what works for you.

== xref:load-local-files.adoc[Load Data from Local Files]

Instructions for loading local files.

== xref:load-from-cloud.adoc[Load Data from Cloud Storage]

Instructions for loading files stored in third-party cloud storage
(Amazon S3, Google Cloud Storage, and Microsoft Azure).

== xref:load-from-warehouse.adoc[Load Data from a Data Warehouse]

Instructions for loading query results from a data warehouse
(xref:load-from-warehouse.adoc#_bigquery[BigQuery], xref:load-from-warehouse.adoc#_snowflake[Snowflake], and xref:tigergraph-server:data-loading:load-from-warehouse.adoc#_postgresql[PostgreSql]).

== xref:load-from-kafka.adoc[Load Data from an External Kafka Cluster, in v3.9.3+]
Instructions for loading records from Kafka topics including CSV, JSON and Avro formats.
With additional instructions on xref:avro-validation-with-kafka.adoc[Avro Data Validation through KafkaConnect].

* For versions earlier than 3.9.3, see xref:data-streaming-connector/kafka.adoc[Stream from an External Kafka Cluster (deprecated)].

== xref:load-from-spark-dataframe.adoc[Load from a Spark DataFrame]

Instructions for TigerGraph's dedicated connector used to read data from a Spark DataFrame.

* xref:spark-connection-via-jdbc-driver.adoc[] is now deprecated and will no longer be supported.

