= Data Loading
:description: Outline of data loading
:page-aliases: README.adoc, data-loading.adoc, readme.adoc

There are various ways to load data in TigerGraph. Here you can find an overview and detailed instructions for the loading method that fits your needs.

== xref:data-loading-overview.adoc[Overview of Data Loading]

Available loading methods and supported features.
Start from this page to pick what works for you.

== xref:load-local-files.adoc[Load Data from Local Files]

Instructions for loading local files.

== xref:data-streaming-connector/index.adoc[Load Data from Cloud Storage]

Instructions for loading files stored in third-party cloud storage
(Amazon S3, Google Cloud Storage, and Microsoft Azure).

== xref:data-streaming-connector/big-query.adoc[Load Data from a Data Warehouse]

Instructions for loading query results from a data warehouse (BigQuery).

== xref:data-streaming-connector/kafka.adoc[Load Data from an External Kafka Cluster, in v3.9.3+]
nstructions for loading records from Kafka topics including CSV, JSON and Avro formats.

* For versions earlier than 3.9.3, see xref:data-streaming-connector/kafka.adoc[Stream from an External Kafka Cluster (deprecated)].

== xref:spark-connection-via-jdbc-driver.adoc[Load DataFrames from Spark]

Instructions for writing Spark DataFrames to TigerGraph via a JDBC connector.
