= User Access Management
:description: User Privileges and Authentication, LDAP, Single Sign-on
:pp: {plus}{plus}
:page-aliases: README.adoc, readme.adoc

TigerGraph's user access management features are based on the role-based access control (RBAC) model, on top of which are additional features that give users finer-grain data access control.
Particularly, users can use access control lists (ACL) to govern access to GSQL queries and even override RBAC.

//Authentication is "who are you"
//Authorization is "what can you do"
//
//
//
//~~~ Why can users override RBAC?
//
//~~~ this page should provide the three-axis overview of our access control concept.
//
//~~~ how does ACL and RBAC work?

WARNING: User authentication is not enabled by default.
To secure your database and the underlying system, we strongly suggest that you xref:enabling-user-authentication.adoc[enable authentication].

//
//
//== Access Control Lists
//
//== Role Base Access Control
//
//definition
//
//example
//
//Link?



