= User Access Management
:description: User Privileges and Authentication, LDAP, Single Sign-on
:pp: {plus}{plus}
:page-aliases: README.adoc, readme.adoc

TigerGraph's user access management features are based on the role-based access control (RBAC) model, on top of which are additional features that give users finer-grain data access control.
Particularly, users can use access control lists (ACL) to govern access to GSQL queries and even override RBAC.

WARNING: User authentication is not enabled by default.
To secure your database and the underlying system, we strongly suggest that you xref:enabling-user-authentication.adoc[enable authentication].

Below is a list of the key features of TigerGraph's user access management system:

* xref:enabling-user-authentication.adoc[Authentication]
* xref:user-management.adoc[User management]
* xref:role-management.adoc[Role management]
* xref:vlac.adoc[Vertex-level access control (VLAC)]
* xref:ldap.adoc[Lightweight Directory Access Protocol (LDAP)]
* xref:sso.adoc[Single sign-on]

== Users and Credentials

A TigerGraph user is a database-level security principal on the TigerGraph platform.
When user authentication is enabled, only clients who can provide credentials that identify themselves as a user can interact with the TigerGraph database.

The TigerGraph platform offers two options for credentials:

* A username-password pair used to log in to GSQL and make HTTP requests.
* A token - a unique 32-character string with an expiration date, used for REST{pp} requests.
* An ACL password used to run commands to alter the ACL privileges of a query.

