= User Access Management
:description: User Privileges and Authentication, LDAP, Single Sign-on
:pp: {plus}{plus}

TigerGraph's user access management features are based on the Role-based Access Control model, on top of which there are additional features that give users finer-grain data access control. Some key features include:

* xref:enabling-user-authentication.adoc[Authentication]
* xref:user-management.adoc[User management]
* xref:role-management.adoc[Role management]
* xref:vertex-level-access-control-beta.adoc[Vertex-level access control (VLAC)]
* xref:ldap.adoc[Lightweight Directory Access Protocol (LDAP)]
* xref:single-sign-on.adoc[Single sign-on]

[discrete]
=== Users and Credentials

A TigerGraph user is a database-level security principal on the TigerGraph platform. When user authentication is enabled, only clients who can provide credentials that identify themselves as a user can interact with the TigerGraph database.

The TigerGraph platform offers two options for credentials:

. A username-password pair
. A token - a unique 32-character string used for REST{pp} requests, with an expiration date.
