= User Management
:description: This page explains the procedures for various user management tasks under TigerGraph's RBAC authorization model.

This page explains the procedures for various user management tasks under TigerGraph's role-based access control(RBAC) model.

To see user management tasks under the xref:access-control-model.adoc#_access_control_lists[Access Control List (ACL)] model, see xref:acl-management.adoc[].

== Create a user

You can run the `CREATE USER` command to create a user.

The username cannot contain the following characters: `\` ,` ` `(` , `)`, `[`, `]`, `:`, `<`, `>`, `;`, `,`, `@`, `\r`, `\n`, `\f`, `\t`, `\\`, `\0`, `\b`.
It also cannot start with a dot `.` or have multiple dots in a sequence.

You can use non-ascii characters, such as Chinese and Kanji characters.

=== Syntax

[source,gsql]
----
CREATE USER
----

=== Required privilege

`WRITE_USER`

=== Procedure

. From the GSQL shell, run the `CREATE USER` command:
+
[source,gsql]
----
GSQL > CREATE USER
----

. Enter the user information in the prompts that follow:
+
.Example: Create user
+
[source,console]
----
User Name : frank@email.com
New Password : ************
Re-enter Password : ************
The user "frank" is created.
----


== View roles assignments and login attempts
The `SHOW USER` command displays the role assignments, as well as the login attempts,  of the current user.
If the current user hsa the `READ_USER` privilege

=== Syntax

[source,gsql]
----
SHOW USER
----

=== Required privilege

`READ_USER` for displaying roles of other users

=== Procedure

From the GSQL shell, run the `SHOW USER` command:

[source,gsql]
----
GSQL > SHOW USER
- Name: testUser
    - Global Roles: superuser
    - LastSuccessLogin: Thu Sep 22 12:43:07 UTC 2022
    - NextValidLogin: Thu Sep 22 12:43:07 UTC 2022 <1>
    - FailedAttempts: 0
    - ShowAlterPasswordWarning: false
----
<1> The next time the user is allowed to attempt login.
For more information, see xref:security:login-protection.adoc[]

If the user running the command has the `READ_USER` privilege, information on all users is displayed.
Otherwise, only the current user's information is displayed.

== View privileges of a user

Users with the `READ_USER` privilege in a scope can view the RBAC privileges of the users in that scope.

=== Syntax

[source,gsql]
----
SHOW PRIVILEGE ON USER <username> (, <username>)*
----

=== Required privilege

`READ_USER`

=== Procedure

. From the GSQL shell, run the `SHOW PRIVILEGE ON USER` command :
+
[source,gsql]
----
GSQL > SHOW PRIVILEGE ON USER tigergraph
----

The above command will show the privileges of user `tigergraph`:

[source,text]
----
User: "tigergraph"
  - Global Privileges:
    READ_SCHEMA
    WRITE_SCHEMA
    READ_LOADINGJOB
    EXECUTE_LOADINGJOB
    WRITE_LOADINGJOB
    READ_QUERY
    WRITE_QUERY
    READ_DATA
    WRITE_DATA
    WRITE_DATASOURCE
    READ_ROLE
    WRITE_ROLE
    READ_USER
    WRITE_USER
    READ_PROXYGROUP
    WRITE_PROXYGROUP
    READ_FILE
    WRITE_FILE
    DROP_GRAPH
    EXPORT_GRAPH
    CLEAR_GRAPHSTORE
    DROP_ALL
    ACCESS_TAG
----

To view xref:access-control-model.adoc#_access_control_lists[ACL privileges] of a user, see xref:acl-management.adoc#_view_acl_privileges_of_a_user_[View ACL privileges of a user].

[#_grant_a_role_to_a_user]
== Grant a role to a user/proxy group

=== Syntax

[source,gsql]
----
GRANT ROLE <role_name1> (, role_name2)* [ON GRAPH <graph_name>]
  TO <username1>|<proxy_group_name1> (, <username2> | <proxy_group_name>2)*
----

=== Required privilege

`WRITE_ROLE`

=== Procedure

. Start the GSQL shell and make sure you are using the correct graph
+
[source,console]
----
$ gsql
GSQL > USE GRAPH example_graph
----

. From the GSQL shell, run the `GRANT ROLE` command. You can grant multiple roles to multiple users:
+
[source,gsql]
----
GSQL > GRANT ROLE role1 , role2 ON GRAPH example_graph TO user1, user2
----

The above command will grant roles `role1` and `role2` on graph `example_graph` to users `user1` and `user2`.

== Revoke a role from a user

=== Syntax

[source,gsql]
----
REVOKE ROLE <roleName1> (, <roleName2)* [ON GRAPH <graphName>]
        FROM <userName1> (, <userName2>)*
----

=== Required privilege

`WRITE_ROLE`

=== Procedure

. Start the GSQL shell and make sure you are using the correct graph
+
[source,console]
----
$ gsql
GSQL > USE GRAPH example_graph
----

. From the GSQL shell, run the `REVOKE_ROLE` command. You can revoke multiple roles from multiple users at the same time:
+
[source,gsql]
----
GSQL > REVOKE ROLE role1, role2 ON GRAPH example_graph
        FROM user1, user2
----

The above command will revoke roles `role1` and `role2` on graph `example_graph` from users `user1` and `user2`.

== Change a user's password

Users can change their own passwords used for login without needing any privilege.
Users with the `WRITE_USER` privilege can change the passwords of other users.

=== Syntax

[source,gsql]
----
ALTER PASSWORD <username>
----

=== Required privilege

`WRITE_USER` for changing the password of a user other than the current user

=== Procedure

. From the GSQL shell, run the following command. Replace `username` with the user whose password you want to change
+
[source,gsql]
----
GSQL > ALTER PASSWORD username
----

. Enter the new password in the prompt that follows.

NOTE: To see how to change a user's xref:access-control-model.adoc#_acl_password[ACL password], see xref:acl-management.adoc#_change_acl_password[Change ACL password]

== Drop a user

=== Syntax

[source,gsql]
----
DROP USER <user1> (,<user2>)*
----

=== Required privilege

`WRITE_USER`

=== Procedure

. From the GSQL shell, run the `DROP USER` command. You can drop multiple users in the same command.
+
[source,gsql]
----
GSQL > DROP USER user1, user2
----

. GSQL will confirm that the users you entered have been dropped



