= User Management
:description: This page explains the procedures for various user management tasks under TigerGraph's RBAC authorization model.

This page explains the procedures for various user management tasks under TigerGraph's role-based access control(RBAC) model.

To see user management tasks under the xref:access-control-model.adoc#_access_control_lists[Access Control List (ACL)] model, see xref:acl-management.adoc[].

== Create a user

You can run the `CREATE USER` command to create a user.

=== Username Rules for v3.9.3 and above

NOTE: v3.9.3 removes some of the restrictions on username strings.

. A username can contain most Unicode characters, but it *may not* contain any of the following characters:
* the colon (`:`) character
* any whitespace character
* nonprintable characters, such as `\a`, `\b`, `\f`, `\n`, `\r`, `\s`, `\t`, `\v`, `\0`

. A username which either follows the pattern `[a-zA-Z_][a-zA-Z0-9]*` or is a simple email address does not need to be enclosed in delimiters. All other usernames must be enclosed in backquotes (```). Delimiters are not stored internally.

=== Username Rules for v3.9.2 and below

Usernames must follow the following string rules:

. A username can contain most Unicode characters, but it *may not* contain any of the following characters:
+
* these punctuation symbols: `\` `(` `)` `[` `]` `:` `<` `>` `;` `,` `@` `*`
* whitespace characters
* nonprintable characters, such as `\a`, `\b`, `\f`, `\n`, `\r`, `\s`, `\t`, `\v`, `\0`


. A username *may not* start with a dot ( `.` ) or have multiple dots ( `...` or `a.b..c...` ) in a sequence.

. Backquotes ( ``` ) *must* be used as a delimiter to enclose usernames which do not follow
the simple pattern `[a-zA-Z_][a-zA-Z0-9]*`. Delimiters are not stored internally.

=== Syntax

[source,gsql]
----
CREATE USER
----

=== Required privilege

`WRITE_USER`

=== Procedure

. From the GSQL shell, run the `CREATE USER` command:
+
[source,gsql]
----
GSQL > CREATE USER
----

. Enter the user information in the prompts that follow:
+
.Example 1: Create user
+
[source,console]
----
User Name : user1
New Password : ************
Re-enter Password : ************
The user "user1" is created.
----
+
.Example 2: Create user with email
+
[source,console]
----
User Name : a@b.com
New Password : ************
Re-enter Password : ************
The user "a@b.com" is created.
----
+
.Example 3: Create user with special characters (*Only* v3.9.3)
+
[source,console]
----
User Name : `:"/.,@#$%^*()_+=-`
New Password : ************
Re-enter Password : ************
The user ":"/.,@#$%^*()_+=-" is created.
----

== View roles assignments and login attempts
The `SHOW USER` command displays the role assignments, as well as the login attempts,  of the current user.
If the current user hsa the `READ_USER` privilege

=== Syntax

[source,gsql]
----
SHOW USER
----

=== Required privilege

`READ_USER` for displaying roles of other users

=== Procedure

From the GSQL shell, run the `SHOW USER` command:

[source,gsql]
----
GSQL > SHOW USER
- Name: testUser
    - Global Roles: superuser
    - LastSuccessLogin: Thu Sep 22 12:43:07 UTC 2022
    - NextValidLogin: Thu Sep 22 12:43:07 UTC 2022 <1>
    - FailedAttempts: 0
    - ShowAlterPasswordWarning: false
----
<1> The next time the user is allowed to attempt login.
For more information, see xref:security:login-protection.adoc[]

If the user running the command has the `READ_USER` privilege, information on all users is displayed.
Otherwise, only the current user's information is displayed.

== View privileges of a user

Users with the `READ_USER` privilege in a scope can view the RBAC privileges of the users in that scope.

=== Syntax

[source,gsql]
----
SHOW PRIVILEGE ON USER <username> (, <username>)*
----

=== Required privilege

`READ_USER`

=== Procedure

. From the GSQL shell, run the `SHOW PRIVILEGE ON USER` command :
+
[source,gsql]
----
GSQL > SHOW PRIVILEGE ON USER tigergraph
----

The above command will show the privileges of user `tigergraph`:

[source,text]
----
User: "tigergraph"
  - Global Privileges:
    READ_SCHEMA
    WRITE_SCHEMA
    READ_LOADINGJOB
    EXECUTE_LOADINGJOB
    WRITE_LOADINGJOB
    READ_QUERY
    WRITE_QUERY
    READ_DATA
    WRITE_DATA
    WRITE_DATASOURCE
    READ_ROLE
    WRITE_ROLE
    READ_USER
    WRITE_USER
    READ_PROXYGROUP
    WRITE_PROXYGROUP
    READ_FILE
    WRITE_FILE
    DROP_GRAPH
    EXPORT_GRAPH
    CLEAR_GRAPHSTORE
    DROP_ALL
    ACCESS_TAG
----

To view xref:access-control-model.adoc#_access_control_lists[ACL privileges] of a user, see xref:acl-management.adoc#_view_acl_privileges_of_a_user_[View ACL privileges of a user].

[#_grant_a_role_to_a_user]
== Grant a role to a user/proxy group

=== Syntax

[source,gsql]
----
GRANT ROLE <role_name1> (, role_name2)* [ON GRAPH <graph_name>]
  TO <username1>|<proxy_group_name1> (, <username2> | <proxy_group_name>2)*
----

=== Required privilege

`WRITE_ROLE`

=== Procedure

. Start the GSQL shell and make sure you are using the correct graph
+
[source,console]
----
$ gsql
GSQL > USE GRAPH example_graph
----

. From the GSQL shell, run the `GRANT ROLE` command. You can grant multiple roles to multiple users:
+
[source,gsql]
----
GSQL > GRANT ROLE role1 , role2 ON GRAPH example_graph TO user1, user2
----

The above command will grant roles `role1` and `role2` on graph `example_graph` to users `user1` and `user2`.

== Revoke a role from a user

=== Syntax

[source,gsql]
----
REVOKE ROLE <roleName1> (, <roleName2)* [ON GRAPH <graphName>]
        FROM <userName1> (, <userName2>)*
----

=== Required privilege

`WRITE_ROLE`

=== Procedure

. Start the GSQL shell and make sure you are using the correct graph
+
[source,console]
----
$ gsql
GSQL > USE GRAPH example_graph
----

. From the GSQL shell, run the `REVOKE_ROLE` command. You can revoke multiple roles from multiple users at the same time:
+
[source,gsql]
----
GSQL > REVOKE ROLE role1, role2 ON GRAPH example_graph
        FROM user1, user2
----

The above command will revoke roles `role1` and `role2` on graph `example_graph` from users `user1` and `user2`.

== Change a user's password

Users can change their own passwords used for login without needing any privilege.
Users with the `WRITE_USER` privilege can change the passwords of other users.

=== Syntax

[source,gsql]
----
ALTER PASSWORD <username>
----

=== Required privilege

`WRITE_USER` for changing the password of a user other than the current user

=== Procedure

. From the GSQL shell, run the following command. Replace `username` with the user whose password you want to change
+
[source,gsql]
----
GSQL > ALTER PASSWORD username
----

. Enter the new password in the prompt that follows.

NOTE: To see how to change a user's xref:access-control-model.adoc#_acl_password[ACL password], see xref:acl-management.adoc#_change_acl_password[Change ACL password]

== Drop a user

=== Syntax

[source,gsql]
----
DROP USER <user1> (,<user2>)*
----

=== Required privilege

`WRITE_USER`

=== Procedure

. From the GSQL shell, run the `DROP USER` command. You can drop multiple users in the same command.
+
[source,gsql]
----
GSQL > DROP USER user1, a@b.com, `:"/.,@#$%^*()_+=-`
----

. GSQL will confirm that the users you entered have been dropped



