= Source conversion issues
:sectnums:

For converting .md files to .adoc, I used https://github.com/asciidoctor/kramdown-asciidoc[kramdoc], which tooko care of most syntax conversion except for the following cases.

== Admonitions
Markdown does not support admonitions. Therefore, Gitbook implemented their own Admonition syntax that requires post-processing.

=== Raw text after kramdoc
The `{% hint style %}` template marker remained untouched.
[source]
----
{% hint style="info" %}
    This is an admonition
{% endhint %}
----

=== Target adoc
* Change `{% hint style %}` into Asciidoc admonition markers.
** `NOTE`, `IMPORTANT`, `CAUTION`, `TIP`, `WARNING` in square brackets `[]` followed by four equal signs in the next line.
** See <<_admonition_style_matching>> for how to map Gitbook admonition style to Asciidoc style.
* Change `{% endhint %}` into `====`
[source,adoc]
----
[NOTE]
====
This is an admonition
====
----


=== Admonition style matching
Gitbook has four admonition styles, and here is how we map them to asciidoc admonitions:

.Gitbook admonitions to asciidoc
[cols="1,1"]
|===
|Gitbook style | Asciidoc style

|info
|NOTE

|warning
|CAUTION

|success
|NOTE

|danger
|WARNING
|===

== Tabbed blocks
Tabs are a little complicated because it is not natively supported in asciidoc either and requires a plug-in.

=== Raw text after kramdoc

[source]
----
{% tabs %} 
{% tab title="Title A" %}
	Content
{% endtab %} 
{% tab title=”Title B”}
	Content
{% endtab %}
{% endtabs %}

----

=== Target adoc (with plug-in)
* Change `{% tabs %}` to `[tabs]` with four equal signs `====` on the next line
* Change `{% tab  title="Title X" "%}` to `Title X::` with a plus sign on the next line, and then two dashes `--` on the line after
* Change `{% endtab %}` to `--`
* Change `{% endtabs %}` to four equal signs
[source]
----

[tabs]
====
Title A::
+
--
Contents of tab A.
--
Title B::
+
--
Contents of tab B.
--
====

----


== Code block with title

=== Raw text after kramdoc
* The template markers remained untouched
[literal]
....
{% code title="RUN_cf.sh: Bash script for Collaborative Filtering (cf) example" %}
 
[,bash]
----
#!/bin/bash
test='cf'
###
gsql 'DROP ALL'
gsql ../${test}/${test}_model.gsql
gsql 'CREATE GRAPH gsql_demo(*)'
 
# Loading
gsql -g gsql_demo ../${test}/${test}_load.gsql
## loading script contains this line:
## RUN JOB load_cf USING FILENAME="../cf/data/cf_data.csv", SEPARATOR=",", EOL="\n"
 
# Querying
gsql -g gsql_demo ../${test}/${test}_query.gsql
gsql -g gsql_demo INSTALL QUERY ALL
gsql -g gsql_demo 'RUN QUERY topCoLiked("id1", 10)'
----
 
{% endcode %}
....

=== Target adoc
* Change `{% code title={title}} %}` to `.title`. No space between the period and the title.
* Remove {% endcode %}

[literal]
....
.RUN_cf.sh: Bash script for Collaborative Filtering (cf) example
[,bash]
----
#!/bin/bash
test='cf'
###
gsql 'DROP ALL'
gsql ../${test}/${test}_model.gsql
gsql 'CREATE GRAPH gsql_demo(*)'
 
# Loading
gsql -g gsql_demo ../${test}/${test}_load.gsql
## loading script contains this line:
## RUN JOB load_cf USING FILENAME="../cf/data/cf_data.csv", SEPARATOR=",", EOL="\n"
 
# Querying
gsql -g gsql_demo ../${test}/${test}_query.gsql
gsql -g gsql_demo INSTALL QUERY ALL
gsql -g gsql_demo 'RUN QUERY topCoLiked("id1", 10)'
----
....

== Images 
Images are handled automatically by the converter, but they won't be referencing to the correct location. 

Is it possible to have a script that moves the image files?

. Search a page for references to images 
. Fetch the image from the outside image folder to put in the correct location

=== What we have now
An assets folder with all the images inside it.

=== What we need
* Each module needs its own image directory. So if a page in a module references a image, the image needs to be copied/moved from the big assets directory into the `images` directory of that module.
----
=server
|--modules
     |--ha
        |--pages
        |--images
----
* We also need to change the reference to images in the adoc files and cut out all the relative paths references:
----
image::../../../.gitbook/assets/diagram-draft-1-.svg[]
----
needs to change to:
----
image::diagram-draft-1-.svg[]
----

== Code languages
Gitbook did not allow us to customize syntax highlighting, so we have been using ErLang and SQL highlighting rules in our documentation.
Antora is able to integrate with Pygment for syntax highlighting, so we should change the code to say GSQL.

=== Rawtext after kramdoc
----
[,sql]
[,erlang]
----

=== Target adoc

* I realize now that this can literally be done with a find and replace, so probably nothing is needed.

----
[source,gsql]
----
