NOTE: While a loading job may have multiple `FILENAME` variables , they must all refer to the same `DATA_SOURCE` object.

==== Cloud file descriptors

For cloud sources, the file descriptor has three valid formats.
You can simply provide the file URI. Or, you can provide optional configuration details, either in a JSON file or as inline JSON content.

[source,php,linenum]
DEFINE FILENAME file_name = "$[data source name]:[URI]";
DEFINE FILENAME file_name = "$[data source name]:[json config file]";
DEFINE FILENAME file_name = "$[data source name]:[inline json content]";

See the following examples.


[source,go]
----
// Format 1: URI only
DEFINE FILENAME uri_s3 = "$s_s3:s3://s3-loading-test/tg_ldbc_snb/sf0.1_csv/dynamic/Comment";
DEFINE FILENAME uri_gcs = "$s_gcs:gs://tg_ldbc_snb/sf0.1_csv/dynamic/Person";
DEFINE FILENAME uri_abs = "$s_abs:abfss://person@yandblobstorage.dfs.core.windows.net/persondata.csv";

// Format 2: URI and configuration file
DEFINE FILENAME uri_s3 = "$s1:myfile.json";

// Format 3: URI and inline JSON
DEFINE FILENAME parquet_s3 = """$s1:{
  "file.uris":"s3://s3-loading-test/tg_ldbc_snb/sf0.1_parquet/dynamic/Comment",
  "file.type":"parquet"}""";
DEFINE FILENAME csv_gcs = """$s1:{
  "file.uris": "gs://tg_ldbc_snb/sf0.1_csv/dynamic/Person",
  "file.type": "text",
  "num.partitions": 6}""";
----

==== Filename parameters

These are the required and optional configuration parameters:

[%header,cols="1,4,1,4"]
|===
|Parameter |Description |Required? |Default value

|file.uris
|The URI or URIs separated by commas.
|Required
|N/A

|file.type
|`text` for CSV and JSON files; `parquet` for Parquet files.
|Optional
|If the file extension is `parquet`, then file.type default is Parquet;
otherwise the default is `text`.

|num.partitions
|The number of partitions to use.
When loading data, each partition is distributed evenly across each node.
If one filename contains much more data than others, consider using a larger partition number.
|Optional
|3

|batch.size
|The number of CSV lines or JSON objects that will be processed per batch.
|Optional
|10000

|recursive
|If the URI refers to a directory, whether to search subdirectories recursively for files to load.
|Optional
|true

|regexp
|A regular expression to filter filenames to be loaded. Uses Java regular expression patterns.
|Optional
|.*, which permits all filenames.

|default
|The default value for any field left empty.
|Optional
|"", an empty string.

|archive.type
|The file type for archive files. Accepted values: `auto` (where it uses the file extension as the file type), `tar`, `zip`, `gzip`, `tar.gz` and `none` (loading from an uncompressed file).
|Optional
|auto

|tasks.max
|The number of threads used to download data.
|Optional
|1
|===
