NOTE: While a loading job may have multiple `FILENAME` variables , they must all refer to the same `DATA_SOURCE` object.

==== Cloud file descriptors

For cloud sources, the file descriptor has three valid formats.
You can simply provide the file URI. Or, you can provide optional configuration details, either in a JSON file or as inline JSON content.

[source,php,linenum]
DEFINE FILENAME file_name = "$[data source name]:[URI]";
DEFINE FILENAME file_name = "$[data source name]:[json config file]";
DEFINE FILENAME file_name = "$[data source name]:[inline json content]";

See the following examples.


[source,go]
----
// Format 1: URI only
DEFINE FILENAME uri_s3 = "$s_s3:s3://s3-loading-test/tg_ldbc_snb/sf0.1_csv/dynamic/Comment";
DEFINE FILENAME uri_gcs = "$s_gcs:gs://tg_ldbc_snb/sf0.1_csv/dynamic/Person";
DEFINE FILENAME uri_abs = "$s_abs:abfss://person@yandblobstorage.dfs.core.windows.net/persondata.csv";

// Format 2: URI and configuration file
DEFINE FILENAME uri_s3 = "$s1:myfile.json";

// Format 3: URI and inline JSON
DEFINE FILENAME parquet_s3 = """$s1:{
  "file.uris":"s3://s3-loading-test/tg_ldbc_snb/sf0.1_parquet/dynamic/Comment",
  "file.type":"parquet"}""";
DEFINE FILENAME csv_gcs = """$s1:{
  "file.uris": "gs://tg_ldbc_snb/sf0.1_csv/dynamic/Person",
  "file.type": "text",
  "num.partitions": 6}""";
----

==== Filename parameters

These are the required and optional configuration parameters:

[%header,cols="1,4,1,4"]
|===
|Parameter |Description |Required? |Default value

|file.uris
|The URI or URIs separated by commas.
|Yes
|N/A

|file.type
|`text` for CSV and JSON files; `parquet` for Parquet files.
|No
|If the file extension is `parquet`, then file.type default is Parquet;
otherwise the default is `text`.

|batch.size
|The number of CSV lines or JSON objects that will be processed per batch.
|No
|10000

|recursive
|If the URI refers to a directory, whether to search subdirectories recursively for files to load.
|No
|true

|regexp
|A regular expression to filter filenames to be loaded. Uses Java regular expression patterns.
|No
|.*, which permits all filenames.

|default
|The default value for any field left empty.
|No
|"", an empty string.

|archive.type
|The file type for archive files. Accepted values: `auto` (where it uses the file extension as the file type), `tar`, `zip`, `gzip`, `tar.gz` and `none` (loading from an uncompressed file).
|No
|auto

|tasks.max
|The number of threads used to download data.
|No
|1

|loading.timeout.ms
|The loading timeout per batch in milliseconds.

If set to 0, then the global parameter `RESTPP.Factory.DefaultLoadingTimeoutSec` is used.
|No
|0

|loading.max.retry.attempts
|The maximum number of retries after a retryable server error.

0 means an unlimited number of retries.
|No
|0

|io.max.retry.attempts
|The maximum number of HTTP transport retries.

0 means an unlimited number of retries.
|No
|0

|batch.size.bytes
|The maximum data batch size in bytes, overriding the `batch.size.rows` limit.

Example: If each row of data is 1000b, `batch.size.rows` = 10, and `batch.size.bytes` = 5000, then the data will be split into 2 5000b batches.
|No
|2,097,152 (2 MiB)

|num.partitions
|[Legacy: only used when gadmin parameter `KafkaConnect.EnableV2` is false] The number of partitions to use.
When loading data, each partition is distributed evenly across each node.
If one filename contains much more data than others, consider increasing this value.
|No
|3

|===