= Dockerの使用の開始

本ドキュメントでは、最新のTigerGraph Enterprise Edition Docker Imageをお使いのホストマシンにプルする方法について順を追って説明します。セクションで説明している手順に従うことで、TigerGraph Docker環境のセットアップを行うことができます。

最新のTigerGraph Docker Imageには、次のコンテンツが含まれています。

* TigerGraphの最新バージョン
* Linuxパッケージ 
 ** openssh-server
 ** git
 ** wget
 ** curl
 ** emac
 ** vim
 ** jq
 ** tar
* 説明資料
 ** GSQL 101
 ** GSQL 102
* 最新のGSQLオープンソースグラフアルゴリズムライブラリー

この補足動画でセットアッププロセス全体をご覧いただけます

video::V5VvgJyjLxA[youtube]

== 1. Docker Desktopのインストール

以下の手順に従って、Docker Desktopをお使いのマシンにインストールし、TigerGraphの使用に十分なリソースを設定します。

. お使いのOSにDockerをインストール
 ** Mac OSにDockerをインストールする際はこちらの動画をご確認ください。 https://www.youtube.com/watch?v=MU8HUVlJTEY
 ** LinuxにDockerをインストールする際はこちらの動画をご確認ください。
  *** Centos: https://docs.docker.com/install/linux/docker-ce/centos/
  *** Ubuntu: https://docs.docker.com/install/linux/docker-ce/ubuntu/
 ** WindowsにDockerをインストールする際はこちらの動画をご確認ください。 https://www.youtube.com/watch?v=ymlWt1MqURY
. TigerGraphの使用に十分なリソースでDocker Desktopを設定
 ** 推奨: 4コアプロセッサーと16GB RAM
 ** 最小: 2コアプロセッサーと10GB RAM。
 ** Docker Desktopアイコンをクリックし、*Preferences* >> *Resources* の順でクリックします。CPUスライダーとメモリスライダーをドラッグして設定し、保存後、Docker Desktopを再起動します。

== 2. Dockerコンテナと共有するホストOS上の共有フォルダーの準備

お使いのホストマシンでシェルを開き、ホストマシンとDockerコンテナ間でのデータ共有のためのディレクトリーを作成または選択します。フォルダーには、読み取り+書き込み+実行の権限を付与します。以下に例として、Linuxで"data"というフォルダーを作成する方法を示します。

[source,console]
----
$ mkdir data
$ chmod 777 data
----

データフォルダーをDockerコンテナ下のフォルダーにマウント(マップ)できます。これで、ホストOSとDocker OSの間でファイルを共有できます。

たとえば、ホストOSのフォルダー `~/data` をDockerのフォルダー `/home/tigergraph/mydata` にマウントすると、 `~/data` に置いたものはすべて `/home/tigergraph/mydata` 下のDockerコンテナに表示されます。また、その逆も可能です。

== 3. TigerGraph Docker Imageをデーモンとして実行

次のコマンドを実行して、TigerGraph Dockerイメージをプルし、ポートのバインドを行い、共有データフォルダーをマップし、イメージからコンテナを開始します。注: このコマンドは非常に長いので、スクロールバーを最後までドラッグして、コマンド全体をコピーするようにしてください。

[source,console]
----
$ docker run -d -p 14022:22 -p 9000:9000 -p 14240:14240 --name tigergraph --ulimit nofile=1000000:1000000 -v ~/data:/home/tigergraph/mydata -t docker.tigergraph.com/tigergraph:latest
----

* 上記のコマンドのオプションと引数は次のとおりです。
 ** `-d`: コンテナをバックグラウンドで実行します。
 ** `-p`: OSポート14022、9000、14240をDockerポート22、9000、14240にマップします。
 ** `--name`: コンテナに"tigergraph"という名前を付けます。
 ** `--ulimit`: `ulimit`(各プロセスで開くファイル記述子の数)を100万に設定します。
 ** `-v`: -vオプションを使用して、ホストOSの `~/data` フォルダーをDockerの `/home/tigergraph/mydata` フォルダーにマウントします。Windows使用の場合は、`~/data` をWindowsのファイルシステムの規則に合わせて変更します。たとえば、`c:\data` などです。
 ** `-t`: 擬似TTYの割り当て
 ** TigerGraph Dockerレジストリー(URL: `docker.tigergraph.com/tigergraph`)から最新のDockerイメージをダウンロードします。

[NOTE]
====
TigerGraphの特定のバージョンを使用したい場合は、 "latest" をバージョン番号に置き換えてください。バージョン3.0.5の場合のURLは以下の通りです。

`docker.tigergraph.com/tigergraph:3.0.5`

従来の開発者向けエディションを使用するには、以下を使用します。

`docker.tigergraph.com/tigergraph-dev`
====

Windowsを使用し、上記のコマンドによってディスクドライブのアクセス許可の問題が発生する場合は、次のコマンドを代わりに試してください(このコマンドは、ホストマシン上の共有フォルダーをコンテナにマップしません)

[source,console]
----
$ docker run -d -p 14022:22 -p 9000:9000 -p 14240:14240 --name tigergraph --ulimit nofile=1000000:1000000 -t docker.tigergraph.com/tigergraph:latest
----

== 4. SSHを使用してコンテナに接続

コンテナを起動した後、SSHを使用してコンテナに接続できます。

. コンテナが起動していることを確認します。以下のコマンドを実行すると、起動中のコンテナの状態を説明するメッセージが表示されます。
+
[source,console]
----
$ docker ps | grep tigergraph
----

. SSHを使用して、コンテナへのシェルを開きます。プロンプトで、パスワードとして `tigergraph` を入力します。ホスト14022ポートをコンテナの22ポート(SSHのデフォルトポート)にマップしているため、ホストではSSHを使用してポート14022に接続していることに注意してください。
+
[source,console]
----
$ ssh -p 14022 tigergraph@localhost
----

== 5. TigerGraphを起動

. SSHを介してコンテナに接続した後、コンテナ内で次のコマンドを使用して、TigerGraphサービスを起動します(最大で1分ほどかかる場合があります)。
+
[source,console]
----
$ gadmin start all
----

. 以下に示す通り `gsql` コマンドを実行して、GSQLシェルを起動します。TigerGraphを初めて使用する場合は、xref:gsql-ref:tutorials:gsql-101/index.adoc[GSQL 101]チュートリアルをここで実行できます。
+
[source,console]
----
$ gsql
GSQL >
----

. お使いのPC(ホストOS)のブラウザーで `+http://localhost:14240+`  
+
にアクセスして、TigerGraphのビジュアルIDであるGraphStudioを起動します

== 操作コマンド早見表

* Docker Desktopの起動後、コンテナの停止や再起動を行うには以下のコマンドを使用します。
+
[source,console]
----
  $ docker container stop tigergraph
  $ docker container start tigergraph
----

* コンテナ内でTigerGraphサービスを起動します。
+
[source,console]
----
  $ gadmin start all
  $ gadmin stop  all
----

* コンテナへのSSH。注: ローカルホストが認識されない場合は、ローカルホストエントリを ~/.ssh/known_hostsから削除してください。
+
[source,console]
----
  $ sed -i.bak '/localhost/d' ~/.ssh/known_hosts
  $ ssh -p 14022 tigergraph@localhost
----

* Linuxユーザーは、IPアドレスを介してコンテナに直接アクセスできます。
+
[source,console]
----
  $ docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' tigergraph
  $ vssh tigergraph@<container_ip_address>
----

* デフォルトユーザー名: `tigergraph`
* デフォルトパスワード: `tigergraph`
* `gadmin start` の実行後、GraphStudioに移動できます。PC(ホストOS)ブラウザーを開き、次のURLでGraphStudioにアクセスします
+
[,text]
----
  http://localhost:14240
----

* GSQLのバージョンを確認します
+
[source,console]
----
$ gsql version
----
