= Get Started
//:page-aliases: getting-started:readme.adoc, getting-started:README.adoc

This Get Started section covers the various options for users who are installing the TigerGraph database themselves.
The Community Edition can be installed on a single machine either directly on a Linux or as a Docker image.
The Enterprise Edition offers additional options; it can also be installed on a cluster of servers directly or through Kubernetes.

Please see
xref:intro:comparison-of-editions.adoc[Comparing TigerGraph Editions] for a chart of the features available for your edition.

== xref:getting-started:docker.adoc[]

If you are a Mac or Windows user, we recommend you use Docker to start up TigerGraph on your computer.

== xref:getting-started:linux.adoc[Get Started on Linux]

If you have a Linux machine that meets our xref:installation:hw-and-sw-requirements.adoc[], you can install TigerGraph on your machine directly.


== xref:getting-started:kubernetes.adoc[]

Deploy a TigerGraph cluster on GKE, EKS, AKS, or OpenShift using the TigerGraph Operator.

== xref:getting-started:cloud-images/index.adoc[Get Started from a Cloud Marketplace]

You can also start up TigerGraph instances from cloud images on AWS, Microsoft Azure, or Google Cloud Platform.
