= Get Started
:page-aliases: getting-started:readme.adoc, getting-started:README.adoc

This Get Started section covers the various options for users who are installing the TigerGraph database themselves.  If you are using TigerGraph Cloud please refer to xref:tigergraph-server:intro:comparison-of-editions.adoc[] for a comparison chart of TigerGraph Server vs. TigerGraph Cloud.

== xref:tigergraph-server:getting-started:docker.adoc[]

If you are a Mac or Windows user, we recommend you use Docker to start up TigerGraph on your computer.

NOTE: The Docker image version of TigerGraph is for personal or R&D use and not for production use.


== xref:tigergraph-server:getting-started:linux.adoc[Get Started on Linux]

If you have a Linux machine that meets our xref:installation:hw-and-sw-requirements.adoc[], you can install TigerGraph on your machine directly.


== xref:tigergraph-server:getting-started:cloud-images/index.adoc[Get Started from a Cloud Marketplace]

You can also start up TigerGraph instances from Cloud Images on AWS, Microsoft Azure, or Google Cloud Platform.
