= Install TigerGraph on Linux

You can install TigerGraph on a Linux machine that meets the xref:../../admin/admin-guide/hw-and-sw-requirements.adoc[Hardware and Software Requirements]. For a step-by-step guide on installing TigerGraph on your Linux machine, please visit the following page:

{% page-ref page="../../admin/admin-guide/install-and-config/install.md" %}

== Quickstart guide for new users +++<a id="GETSTARTEDwithTigerGraphv2.1-QuickStartGuideforNewUsers">++++++</a>+++

=== Installation Checklist

. *CHECK* xref:../../admin/admin-guide/hw-and-sw-requirements.adoc[Hardware and Software Requirements]
. *DOWNLOAD* the TigerGraph platform: https://info.tigergraph.com/enterprise-free
. *INSTALL* the Platform
 .. For simple single-server installation: +
Assuming your downloaded file is called <your_tigergraph_package>:
+
[,bash]
----
tar xzf <your_tigergraph_package>.tar.gz
cd tigergraph*/

# to install license in interactive mode
sudo ./install.sh

# to install license in non-interactive mode
sudo ./install.sh -n
----

 .. For additional options, see xref:../../admin/admin-guide/install-and-config/install.adoc[TigerGraph Platform Installation Guide]
