== Patents and Third Party Software

Patent and Third Party Notice for TigerGraph Platform v 3.2 Sep 2021

U.S. Pat. No. 9953106, 9977837, 10120956. +
Additional Patents pending.

The TigerGraph software program uses some third-party software
components that are licensed under their own terms. The attached notices
are provided for information only.

* Section 1. List of third-party software in the TigerGraph platform.
* Section 2. List of additional third-party software in the TigerGraph
Cloud Service interface.
* Section 3. Table of license types.

A separate third-party disclosure is available for the GraphStudio
Visual SDK. See
https://docs.tigergraph.com/ui/graphstudio/patent-and-third-party-notice


=== Section 1. List of third-party software in the TigerGraph platform


antlr Copyright (c) 2014 antlr.
https://www.antlr.org[https://www.antlr.org/] Licensed under BSD3

commons-cli Copyright (c) 2002-2017 The Apache Software Foundation.
https://commons.apache.org/proper/commons-cli/ Licensed under Apache2

commons-codec Copyright (c) 2002-2017 The Apache Software Foundation.
https://commons.apache.org/proper/commons-codec/ Licensed under Apache2

commons-lang3 Copyright (c) 2001-2018 The Apache Software Foundation.
https://commons.apache.org/proper/commons-lang/ Licensed under Apache2

diffutils Copyright (c) 2010 Free Software Foundation.
https://github.com/java-diff-utils/java-diff-utils Licensed under
Apache2

grpc Copyright (c) 2018 The gRPC authors.
https://grpc.io[https://grpc.io/] Licensed under Apache2

guava Copyright (c) 2010-2016 OneLogin,
Inc. https://github.com/google/guava Licensed under Apache2

java-saml Copyright (c) 2010-2016 OneLogin,
Inc. https://github.com/onelogin/java-saml Licensed under MIT

jline Copyright (c) 2002-2018 Guillaume Nodet.
https://github.com/jline/jline3 Licensed under BSD3

joda-time Copyright (c) 2002-2018 Joda. https://www.joda.org/joda-time/
Licensed under Apache2

json Copyright (c) 2002 JSON. https://github.com/stleary/JSON-java
Licensed under JSON

LDAP SDK Copyright (c) 2009 Ping Identity Corporation.
https://github.com/pingidentity/ldapsdk/blob/master/README.md Licensed
under LDAPSDK

log4j Copyright (c) 1999-2018 The Apache Software Foundation.
https://logging.apache.org/log4j/2.x/ Licensed under Apache2

netty Copyright (c) 2018 The Netty Project.
https://netty.io[https://netty.io/] Licensed under Apache2

protobuf-java Copyright (c) 2008 Google.
https://developers.google.com/protocol-buffers/ Licensed under BSD3

slf4j Copyright (c) 2004-2017 QOS.ch.
https://www.slf4j.org[https://www.slf4j.org/] Licensed under MIT

stax2-api Copyright (c) 2013-2019 Tatu Saloranta.
https://github.com/FasterXML/stax2-api Licensed under BSD

woodstox-core-asl Copyright (c) 2014-2019 Tatu Saloranta.
https://github.com/FasterXML/woodstox Licensed under Apache2

xmlsec Copyright (c) 2002-2016 Aleksey Sanin.
https://www.aleksey.com/xmlsec/ Licensed under MIT

yamlbeans Copyright (c) 2008 Nathan Sweet.
https://github.com/EsotericSoftware/yamlbeans Licensed under MIT

zookeeper Copyright (c) 2010-2018 The Apache Software Foundation.
https://zookeeper.apache.org[https://zookeeper.apache.org/] Licensed
under Apache2

gson Copyright (c) 2008-2019 Google. https://github.com/google/gson
Licensed under Apache2

javacc Copyright (c) 2006 Sun Microsystems.
https://javacc.org[https://javacc.org/] Licensed under BSD3

javacpp Copyright (c) 1989 Ty Coon. https://github.com/bytedeco/javacpp
Licensed under Apache

murmurhash Copyright (c) 2010-2019 aapleby.
https://github.com/aappleby/smhasher Licensed under MIT

kafka Copyright (c) 2017 The Apache Software Foundation.
https://kafka.apache.org[https://kafka.apache.org/] Licensed under
Apache2

librdkafka Copyright (c) 2012-2018 Magnus Edenhill.
https://github.com/edenhill/librdkafka Licensed under BSD2

libfcgi Copyright (c) 2012-2019 toshic.
https://github.com/toshic/libfcgi Licensed under FCGI

zlib Copyright (c) 1995-2017 Jean-loup Gailly.
https://zlib.net[https://zlib.net/] Licensed under ZLIB

libcurl Copyright (c) 1996-2019 Daniel Stenberg.
https://curl.haxx.se/libcurl/ Licensed under CURL

zeromq Copyright (c) 2007-2016 various copyright holders.
http://zeromq.org[http://zeromq.org/] Licensed under LGPL3

libhttp_parser Copyright (c) 2009-2019 Joyent.
https://github.com/nodejs/http-parser Licensed under MIT

yaml-cpp Copyright (c) 2008-2015 Jesse Beder.
https://github.com/jbeder/yaml-cpp Licensed under MIT

cryptopp Copyright (c) 1995-2016 Wei Dai.
https://www.cryptopp.com[https://www.cryptopp.com/] Licensed under BOOST

boost Copyright (c) 1998-2005 Beman Dawes, David Abrahams.
https://www.boost.org[https://www.boost.org/] Licensed under BOOST

snappy Copyright (c) 2011 Google, Inc. https://github.com/google/snappy
Licensed under BSD3

jsoncpp Copyright (c) 2007-2010 Baptiste Lepilleur.
https://github.com/open-source-parsers/jsoncpp Licensed under MIT

cereal Copyright (c) 2014 Randolph Voorhies, Shane Grant.
https://github.com/USCiLab/cereal Licensed under BSD3

nginx Copyright (c) 2011-2018 nginx. http://nginx.org[http://nginx.org/]
Licensed under BSD2

jemalloc Copyright (c) 2002-2018 Jason Evans, (c) 2007-2012 Mozilla
Foundation, (c) 2009-2018 Facebook,
Inc. http://jemalloc.net[http://jemalloc.net/] Licensed under BSD2

sparsehash Copyright (c) 2005 Google.
https://github.com/sparsehash/sparsehash Licensed under BSD3

rapidjson Copyright (c) 2006-2013 Alexander Chemeris.
https://github.com/Tencent/rapidjson Licensed under MIT

openjdk Copyright (c) 2019 Oracle.
https://openjdk.java.net[https://openjdk.java.net/] Licensed under
GPL2+CE GPL2 with Classpath Exception: Clarification that the using the
licensed code with other code does not require that other code to be
GPL2 compatible.

gcc Copyright (c) 1992-2017 Free Software Foundation.
https://gcc.gnu.org[https://gcc.gnu.org/] (gcc) Licensed under GPL3,
with Runtime Library Exception The GCC license provides an exception to
GPLv3 to allow compilation of non- GPL (including proprietary) programs
to use, in this way, the header files and runtime libraries covered by
this Exception. The complete terms are available at
https://www.gnu.org/licenses/gcc-exception.html

tsar Copyright (c) 2004 Apache. https://github.com/alibaba/tsar Licensed
under Apache2

gperftools Copyright (c) 2005 Google.
https://github.com/gperftools/gperftools (we use its tcmalloc) Licensed
under BSD3

python 2.7 Copyright (c) 2001-2019 Python.
https://www.python.org/download/releases/2.7/license/ Licensed under
Python2

Go
http://github.com/GeertJohan/go.rice/embedded[github.com/GeertJohan/go.rice/embedded]
Licensed under BSD 2-clause ``Simplified'' License

Gabs http://github.com/Jeffail/gabs[github.com/Jeffail/gabs] Licensed
under MIT License

Sarama http://github.com/Shopify/sarama[github.com/Shopify/sarama]
Licensed under MIT License

Go Meta Linter
http://github.com/alecthomas/gometalinter[github.com/alecthomas/gometalinter]
Licensed under MIT License

Units http://github.com/alecthomas/units[github.com/alecthomas/units]
Licensed under MIT License

Quantile
http://github.com/beorn7/perks/quantile[github.com/beorn7/perks/quantile]
Licensed under MIT License

Readline http://github.com/chzyer/readline[github.com/chzyer/readline]
Licensed under MIT License

Misspell
http://github.com/client9/misspell/cmd/misspell[github.com/client9/misspell/cmd/misspell]
Licensed under MIT License

Client V3
http://github.com/coreos/etcd/clientv3[github.com/coreos/etcd/clientv3]
Licensed under Apache License 2.0

Journal
http://github.com/coreos/go-systemd/journal[github.com/coreos/go-systemd/journal]
Licensed under Apache License 2.0

Capnslog
http://github.com/coreos/pkg/capnslog[github.com/coreos/pkg/capnslog]
Licensed under Apache License 2.0

Zip http://github.com/daaku/go.zipexe[github.com/daaku/go.zipexe]
Licensed under MIT License

Spew
http://github.com/davecgh/go-spew/spew[github.com/davecgh/go-spew/spew]
Licensed under ISC License

JWT http://github.com/dgrijalva/jwt-go[github.com/dgrijalva/jwt-go]
Licensed under MIT License

Breaker
http://github.com/eapache/go-resiliency/breaker[github.com/eapache/go-resiliency/breaker]
Licensed under MIT License

Go xerial snappy
http://github.com/eapache/go-xerial-snappy[github.com/eapache/go-xerial-snappy]
Licensed under MIT License

Queue http://github.com/eapache/queue[github.com/eapache/queue] Licensed
under MIT License

Color http://github.com/fatih/color[github.com/fatih/color] Licensed
under MIT License

Gorp http://github.com/go-gorp/gorp[github.com/go-gorp/gorp] Licensed
under MIT License

Oleutil
http://github.com/go-ole/go-ole/oleutil[github.com/go-ole/go-ole/oleutil]
Licensed under MIT License

Protobuf http://github.com/gogo/protobuf[github.com/gogo/protobuf]
Licensed under BSD 3-clause "New" or "Revised" License

Go Lint
http://github.com/golang/lint/golint[github.com/golang/lint/golint]
Licensed under BSD 3-clause "New" or "Revised" License

Snappy http://github.com/golang/snappy[github.com/golang/snappy]
Licensed under BSD 3-clause "New" or "Revised" License

Renameio http://github.com/google/renameio[github.com/google/renameio]
Licensed under Apache License 2.0

RocksDB https://github.com/facebook/rocksdb/ Licensed under Apache
License 2.0

Shlex http://github.com/google/shlex[github.com/google/shlex] Licensed
under Apache License 2.0

UUID http://github.com/google/uuid[github.com/google/uuid] Licensed
under BSD 3-clause "New" or "Revised" License

Ineffassign
http://github.com/gordonklaus/ineffassign[github.com/gordonklaus/ineffassign]
Licensed under MIT License

Backoffutils
http://github.com/grpc-ecosystem/go-grpc-middleware/util/backoffutils[github.com/grpc-ecosystem/go-grpc-middleware/util/backoffutils]
Licensed under Apache License 2.0

Prometheus
http://github.com/grpc-ecosystem/go-grpc-prometheus[github.com/grpc-ecosystem/go-grpc-prometheus]
Licensed under Apache License 2.0

GRPC-gateway
http://github.com/grpc-ecosystem/grpc-gateway[github.com/grpc-ecosystem/grpc-gateway]
Licensed under BSD 3-clause "New" or "Revised" License

Go-uuid
http://github.com/hashicorp/go-uuid[github.com/hashicorp/go-uuid]
Licensed under Mozilla Public License 2.0

Go-fork http://github.com/jcmturner/gofork[github.com/jcmturner/gofork]
Licensed under BSD 3-clause "New" or "Revised" License

Ansiterm http://github.com/juju/ansiterm[github.com/juju/ansiterm]
Licensed under GNU Lesser General Public License v3.0

Tabwriter
http://github.com/juju/ansiterm/tabwriter[github.com/juju/ansiterm/tabwriter]
Licensed under BSD 3-clause "New" or "Revised" License

Compress
http://github.com/klauspost/compress[github.com/klauspost/compress]
Licensed under BSD 3-clause "New" or "Revised" License

Xxhash
http://github.com/klauspost/compress/zstd/internal/xxhash[github.com/klauspost/compress/zstd/internal/xxhash]
Licensed under MIT License

fs http://github.com/kr/fs[github.com/kr/fs] Licensed under BSD 3-clause
"New" or "Revised" License

Pretty http://github.com/kr/pretty[github.com/kr/pretty] Licensed under
MIT License

Text http://github.com/kr/text[github.com/kr/text] Licensed under MIT
License

Vtclean
http://github.com/lunixbochs/vtclean[github.com/lunixbochs/vtclean]
Licensed under MIT License

Go-colorable
http://github.com/mattn/go-colorable[github.com/mattn/go-colorable]
Licensed under MIT License

Go-isatty http://github.com/mattn/go-isatty[github.com/mattn/go-isatty]
Licensed under MIT License

Go-sqlite3
http://github.com/mattn/go-sqlite3[github.com/mattn/go-sqlite3] Licensed
under MIT License

Pbutil
http://github.com/matttproud/golang_protobuf_extensions/pbutil[github.com/matttproud/golang_protobuf_extensions/pbutil]
Licensed under Apache License 2.0

i18n
http://github.com/nicksnyder/go-i18n/i18n[github.com/nicksnyder/go-i18n/i18n]
Licensed under MIT License

Go-toml
http://github.com/pelletier/go-toml[github.com/pelletier/go-toml]
Licensed under MIT License

xxh32
http://github.com/pierrec/lz4/internal/xxh32[github.com/pierrec/lz4/internal/xxh32]
Licensed under BSD 3-clause "New" or "Revised" License

errors http://github.com/pkg/errors[github.com/pkg/errors] Licensed
under BSD 2-clause ``Simplified'' License

sftp http://github.com/pkg/sftp[github.com/pkg/sftp] Licensed under BSD
2-clause ``Simplified'' License

difflib
http://github.com/pmezard/go-difflib/difflib[github.com/pmezard/go-difflib/difflib]
Licensed under BSD 3-clause "New" or "Revised" License

Go
http://github.com/prometheus/client_model/go[github.com/prometheus/client_model/go]
Licensed under Apache License 2.0

Common http://github.com/prometheus/common[github.com/prometheus/common]
Licensed under Apache License 2.0

Procfs http://github.com/prometheus/procfs[github.com/prometheus/procfs]
Licensed under Apache License 2.0

Go-metrics
http://github.com/rcrowley/go-metrics[github.com/rcrowley/go-metrics]
Licensed under BSD 2-clause ``Simplified'' License

Cron http://github.com/robfig/cron[github.com/robfig/cron] Licensed
under MIT License

Gopsutil http://github.com/shirou/gopsutil[github.com/shirou/gopsutil]
Licensed under BSD 3-clause "New" or "Revised" License

W32 http://github.com/shirou/w32[github.com/shirou/w32] Licensed under
BSD 3-clause "New" or "Revised" License

Cobra http://github.com/spf13/cobra[github.com/spf13/cobra] Licensed
under Apache License 2.0

Pflag http://github.com/spf13/pflag[github.com/spf13/pflag] Licensed
under BSD 3-clause "New" or "Revised" License

Testify http://github.com/stretchr/testify[github.com/stretchr/testify]
Licensed under MIT License

Promptui
http://github.com/tigergraph/promptui[github.com/tigergraph/promptui]
Licensed under BSD 3-clause "New" or "Revised" License

Deadcode http://github.com/tsenart/deadcode[github.com/tsenart/deadcode]
Licensed under BSD 3-clause "New" or "Revised" License

Etcd http://go.etcd.io/etcd[go.etcd.io/etcd] Licensed under Apache
License 2.0

Atomic http://go.uber.org/atomic[go.uber.org/atomic] Licensed under MIT
License

Multierr http://go.uber.org/multierr[go.uber.org/multierr] Licensed
under MIT License

Zap http://go.uber.org/zap[go.uber.org/zap] Licensed under MIT License

Crypto https://pkg.go.dev/golang.org/x/crypto Licensed under BSD
3-clause "New" or "Revised" License

Golint https://pkg.go.dev/golang.org/x/lint/golint Licensed under BSD
3-clause "New" or "Revised" License

Net https://pkg.go.dev/golang.org/x/text Licensed under BSD 3-clause
"New" or "Revised" License

Errgroup https://pkg.go.dev/golang.org/x/sync/errgroup Licensed under
BSD 3-clause "New" or "Revised" License

Sys https://pkg.go.dev/golang.org/x/sys Licensed under BSD 3-clause
"New" or "Revised" License

Text https://pkg.go.dev/golang.org/x/text Licensed under BSD 3-clause
"New" or "Revised" License

Genproto https://pkg.go.dev/google.golang.org/genproto Licensed under
Apache License 2.0

Grpc https://pkg.go.dev/google.golang.org/grpc Licensed under Apache
License 2.0

Check.v1 http://gopkg.in/check.v1[gopkg.in/check.v1] Licensed under BSD
2-clause ``Simplified'' License

Aescts.v1
http://gopkg.in/jcmturner/aescts.v1[gopkg.in/jcmturner/aescts.v1]
Licensed under Apache License 2.0

dnsutils.v1
http://gopkg.in/jcmturner/dnsutils.v1[gopkg.in/jcmturner/dnsutils.v1]
Licensed under Apache License 2.0

gokrb5.v7
http://gopkg.in/jcmturner/gokrb5.v7[gopkg.in/jcmturner/gokrb5.v7]
Licensed under Apache License 2.0

rpc.v1 http://gopkg.in/jcmturner/rpc.v1[gopkg.in/jcmturner/rpc.v1]
Licensed under Apache License 2.0

jack.v2
http://gopkg.in/natefinch/lumberjack.v2[gopkg.in/natefinch/lumberjack.v2]
Licensed under MIT License

yaml.v2 http://gopkg.in/yaml.v2[gopkg.in/yaml.v2] Licensed under Apache
License 2.0

Go Programming Language http://cloud.google.com/go[cloud.google.com/go]
Licensed under Apache2

go-semver
http://github.com/coreos/go-semver[github.com/coreos/go-semver] Licensed
under Apache2

Resty http://github.com/go-resty/resty[github.com/go-resty/resty]
Licensed under MIT license

flock https://github.com/gofrs/flock[github.com/gofrs/flock] Licensed
under BSD 3-clause "New" or "Revised" License

protobuf http://github.com/golang/protobuf[github.com/golang/protobuf]
Licensed under BSD 3-clause "New" or "Revised" License

client_golang
http://github.com/prometheus/client_golang[github.com/prometheus/client_golang]
Licensed under Apache2

net http://golang.org/x/net[golang.org/x/net] Licensed under BSD
3-clause "New" or "Revised" License


=== Section 2. List of additional third-party software in the TigerGraph Cloud Service interface

The TigerGraph Cloud Service permits users to use the TigerGraph graph
database and analytics platform via a web interface.
TigerGraph does not copy or distribute the TigerGraph Cloud software to the end user.

In additional to having the third-party components of the TigerGraph
Platform, the TigerGraph Cloud Service interface includes the following
additional third-party software.

Netdata Copyright (c) 2016-2018, Costa Tsaousis. Copyright (c) 2018,
Netdata Inc. https://github.com/netdata/netdata Licensed under
https://github.com/netdata/netdata/tree/master/LICENSE[GPL v3 or later].

=== Section 3. Table of license types.

The following table explains the license abbreviations used in the list
of TigerGraph Third Party Software. A link is provided to an official
source for each license.

[cols=",",options="header",]
|===
|Abbreviation |License Name and Source

| Apache2 |

Apache License version 2.0

https://www.apache.org/licenses/LICENSE-2.0

| BOOST |

Boost Software License

http://www.boost.org/LICENSE_1_0.txt
| BSD2 |

2-Clause BSD (Berkeley Standard Distribution) License

https://opensource.org/licenses/BSD-2-Clause


| BSD3 |

3-Clause BSD (Berkeley Standard Distribution) License

https://opensource.org/licenses/BSD-3-Clause


| CURL |

Curl License

https://curl.haxx.se/docs/copyright.html


| FCGI |

FastCGI2 License

https://github.com/FastCGI-Archives/fcgi2/blob/master/LICENSE.TERMS


| GPL2 |

GNU General Public License version 2.0

https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html


| GPL2+CE |

GNU General Public License, version 2, with the Classpath Exception

https://openjdk.java.net/legal/gplv2+ce.html


| GNU |

General Public License version 3.0

https://www.gnu.org/licenses/gpl-3.0.en.html


| ISC | ISC License https://opensource.org/licenses/ISC |  JSON |

JSON License

http://www.json.org/license.html


| LDAPSDK |

UnboundID LDAP SDK Free Use License

https://docs.ldap.com/ldap-sdk/docs/LICENSE-UnboundID-LDAPSDK.txt

|  LGPL3 |

GNU Lesser General Public License version 3.0

https://www.gnu.org/licenses/lgpl-3.0.en.html



| MIT |

MIT (Massachusetts Institute of Technology) License

https://opensource.org/licenses/MIT

| Mozilla |

Mozilla Public License 2.0

https://www.mozilla.org/en-US/MPL/2.0/


| MPICH |

MPICH License

http://git.mpich.org/mpich.git/blob/HEAD:/COPYRIGHT


| OPENSSL |

OpenSSL License

https://www.openssl.org/source/license.html


| Python2 |

Python 2.7 License

https://www.python.org/download/releases/2.7/license/


| SLI_OFL1.1 |

SIL Open Font License version 1.1

http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web


| ZLIB |

zlib License

https://www.zlib.net/zlib_license.html

|===