= 認証
:pp: {plus}{plus}
:description: REST APIにおける認証機能の仕組みについての説明。

TigerGraphのRESTful APIは、ポート9000のREST{pp}サーバーまたはポート14240のGSQLサーバーと通信します。
それぞれのサーバーは異なる認証方法を使用します。

== REST{pp} サーバーのリクエスト

TigerGraphのREST{pp}のエンドポイントはデフォルトではパブリックに設定されています。TigerGraphサーバーのHTTPポートにアクセスできる人なら誰でも、エンドポイントを実行できます。
xref:user-access:enabling-user-authentication.adoc[REST{pp}認証が有効になっている]場合、有効な認証トークンがヘッダーに含まれていなければなりません。

REST{pp}サーバーは、以下の通り、OAuth2.0スタイルの認証を行います。

. 各ユーザーは xref:user-access:managing-credentials.adoc#_create_a_secret[1つ以上の**シークレット**(一意の疑似ランダム文字列)を作成できます]。各シークレットは、特定のユーザーおよび特定のグラフに対するユーザーの権限に関連付けられます。
. このシークレットを持っている人は誰でも、xref:API:built-in-endpoints.adoc#_request_a_token_get [認証を生成する**トークン**](他の疑似ランダム文字列)への特別なRESTエンドポイントを呼び出すことができます。
. 認証トークンは、他のRESTエンドポイントを通してTigerGraphデータベース操作を実行するために使用することができます。各トークンは一定期間後に期限切れになります。TigerGraphでのトークンの有効期間はデフォルトで1か月です。

=== **トークンの使用**

REST{pp}認証が有効である場合、有効なトークンが常にHTTPヘッダーに含まれている必要があります。curlを使用してREST{pp}リクエストのフォーマットおよび送信を行う場合は、次の構文を使用します。

ヘッダーに認証トークンを含むcurl GSQLリクエスト

[source,console]
----
curl -X GET -H "Authorization: Bearer <token>" '<request_URL>'
----



以下はリクエストの例です。

[source,console]
----
curl -X GET -H "Authorization: Bearer 01234567abcdefgh01234567abcdefgh" "http://localhost:9000/graph/socialNet/vertices/User?limit=3"
----

== GSQLサーバーへのリクエスト

GSQLサーバーに対して行われるすべてのリクエストには、ユーザーの資格情報が必要とされます。`curl -u` オプションを使用して、TigerGraphユーザーのユーザー名とパスワードを渡すことができます。

[source,console]
----
curl -X GET -u <username>:<password> "http://localhost:14240/<path_to_endpoint>
----

資格情報をより安全に保つために、コマンドラインにユーザー名とパスワードが表示されないようにしたい場合は、代わりに https://everything.curl.dev/usingcurl/netrc[.netrcファイル] または https://everything.curl.dev/cmdline/configfile[設定ファイル] を使用するのも1つの方法です。インタラクティブモードの場合は、パスワードを指定せずに `-u` オプションを使用することもできます。これにより、curlにパスワードの入力を求められます。
