= Memory Management
:description: How to management memory usage in TigerGraph.

This page describes how to:

* Configure

== Memory usage key factors
Below are the major factors that impact memory usage in TigerGraph:

* Amount of data
** The biggest factor that affects memory usage in TigerGraph is the amount of data you have.
Most database operations require more memory the more data you have.
* Queries
** There are a number of factors that cause queries to use a lot of memories.
Typically, the following types of queries tend to be more memory intensive:
** Queries that read or write a lot of data
** A non-distributed query
** Accumulators can use a lot of memory


=== Queries

== Monitor memory usage
You can monitor memory usage by query and by machine.

=== Monitor query memory usage
GPE records memory usage by query at different stages of the query and saves it to `$(gadmin config get System.LogRoot)/gpe/log.INFO`.
You can monitor how much memory a query is using by searching the log file for the request ID and filter for lines that contain `"QueryMem"`:

[source,console]
----
$ grep -i <request_id> $(gadmin config get System.LogRoot)/gpe/log.INFO |
    grep -i "querymem"
----

You can also run a query first, and then run the following command immediately after to retrieve the most recent query logs and filter for `"QueryMem"`:

[source,console]
----
$ tail -n 50 $(gadmin config get System.LogRoot)/gpe/log.INFO |
    grep -i "querymem"
----

You will get results that look like the following, which shows memory usage by the query at different stages of its execution. The number at the end of each line indicates the number of bytes of memory utilized by the query:

[source.wrap,console]
----
0415 01:33:40.885433  6553 gpr.cpp:195] Engine_MemoryStats|ldbc_snb::,196612.RESTPP_1_1.1618450420870.N,NNN,15,0,0|MONITORING Step(1) BeforeRun[GPR][QueryMem]: 116656

I0415 01:33:42.716199  6553 gpr.cpp:241] Engine_MemoryStats|ldbc_snb::,196612.RESTPP_1_1.1618450420870.N,NNN,15,0,0|MONITORING Step(1) AfterRun[GPR][QueryMem]: 117000
----

=== Monitor system free memory percentage

=== Monitor memory usage by node

=== Linux command

* `free -h` - Check available memory on the node
** Can be combined with `grun`
* `top` - interactively view CPU and memory details
* How to check for out of memory issues
* `dmesg -T | grep -i “oom”`
+
[,console]
----
[Thu Feb  4 00:41:08 2021] google_osconfig invoked oom-killer: gfp_mask=0x201da, order=0, oom_score_adj=0
[Thu Feb  4 00:41:08 2021]  [<ffffffffafdc208d>] oom_kill_process+0x2cd/0x490
[Thu Feb  4 00:41:08 2021] [ pid ]   uid  tigergraph total_vm      rss nr_ptes swapents oom_score_adj name
[Thu Feb  4 00:41:09 2021] [20183]  1004 20183 20200397   377046    5701        0             0 tg_dbs_restd
[Thu Feb  4 00:41:09 2021] Out of memory: Kill process 20183 (tg_dbs_restd) score 239 or sacrifice child
[Thu Feb  4 00:41:09 2021] Killed process 20183 (tg_dbs_restd), UID 1004, total-vm:80801588kB, anon-rss:1508400kB, file-rss:0kB, shmem-rss:0kB
----


== Set global memory threshold


== Manage query workload

