= TigerGraph DB Release Notes
:description: Release notes for TigerGraph {page-component-version}
//:page-aliases: change-log.adoc, release-notes.adoc
:fn-preview: footnote:preview[Features in the preview stage should not be used for production purposes. General Availability (GA) versions of the feature will be available in a later release.]
:pp: {plus}{plus}
:toc:
:to

https://dl.tigergraph.com/?tab=enterprise[TigerGraph Server 4.2.1] LTS was released on September 5, 2025.

TigerGraph Server 4.2.0 Preview was released on April 3, 2025.

TigerGraph Server 4.2.0 Alpha was released on March 4, 2025.

[NOTE]
====
TigerGraph 4.2's feature set is an enhancement of what was available in 4.1.2.
Therefore, features that were  in 4.1.2 are not considered New Features.
====

== Key New Features

* *xref:4.2@gsql-ref:vector:index.adoc[Hybrid Vector Search]*:
Scalable storage and similarity search for vector attributes associated with vertices.

** New `VECTOR` attribute data type with real-time updates
** Fast approximate nearest neighborhood (ANN), with automatic indexing, incremental indexing
** hybrid graph {plus} vector search in GSQL

* *xref:4.2@tigergraph-server:backup-and-restore:incremental-backup.adoc[Incremental Backup]* which efficiently backs up only what has changed since the last backup/restore event.

* *xref:4.2@tigergraph-server:installation:upgrade.adoc#_rolling_upgrade[Rolling Upgrades of maintenance versions]* for HA clusters (Preview).

* *xref:4.2@gsql-ref:querying:select-statement/index.adoc#_from_clause[GQL/OpenCypher path pattern syntax]*, within GSQL syntax

* *Run ad hoc queries directly*  (xref:4.2@gsql-ref:querying:query-modes.adoc[non-procedural interpreted queries])

* *xref:4.2@tigergraph-server:intro:comparison-of-editions.adoc[Community Edition of TigerGraph Database]*:

** Up to 200GB graph data + 100GB vector data, single server only
** Some enterprise features not included. Community support only
** See the full xref:4.2@intro:comparison-of-editions.adoc[comparison of editions].
** [4.2.1] xref:4.2@intro:comparison-of-editions.adoc#_database_features[Combined graph and vector data size] limit for Community Edition, allowing flexible allocation of up to 300 GB for graph and vector storage.

== Detailed List of New and Modified Features

=== System Management Enhancements

* *xref:4.2@tigergraph-server:backup-and-restore:incremental-backup.adoc[Incremental Backup]* which efficiently backs up only what has changed since the last backup/restore event.

* *xref:4.2@tigergraph-server:installation:upgrade.adoc#_rolling_upgrade[Rolling Upgrades of maintenance versions]* for HA clusters (Preview).

* *xref:4.2@tigergraph-server:backup-and-restore:restore-backup-same.adoc#_options_for_restore[Restore option `--keepusers`]* to keep the database users in the current database, not the ones from the backup file.

* *Backup to xref:4.2@tigergraph-server:backup-and-restore:configurations.adoc#_backup_to_abs_azure_blob_storage[Azure] and xref:4.2@tigergraph-server:backup-and-restore:configurations.adoc#_backup_to_gcs_google_cloud_storage[GCP] cloud storage*, analogous to  existing support for backup to AWS S3.

* *More graceful xref:4.2@tigergraph-server:system-management:manage-services.adoc#_graceful_shutdown_of_restpp[user-initiated shutdown]* of RESTPP and GPE services.

* *Backup HA Enhancement*: backup can still work even if a node is down or a region is down.

* *link:https://github.com/tigergraph/ecosys/blob/master/k8s/README.md[Kubernetes Operator update* to v1.5.0] with numerous new features
** CRR replication, Auto cluster monitoring during creation, upgrade pre-check support, rolling upgrades, backoff delay for job retries to improve resilience

* *xref:4.2@tigergraph-server:system-management:management-commands.adoc#_gadmin_status[gadmin status -v]* now displays Role information, with support for GPE, GSE, and GSQL.

* [4.2.1] *xref:4.2@tigergraph-server:reference:configuration-parameters.adoc#_zk[New ZK.SnapCount configuration]* enables users to fine-tune the number of committed ZooKeeper transactions that trigger a snapshot, enhancing memory management and stability under high transaction loads.

=== Security and Access Control Enhancements

* *xref:4.2@tigergraph-server:user-access:jwt-token.adoc#_user_guide_overview[
JWT authentication] for all REST endpoints*, including GSQL endpoints.

* *New xref:4.2@tigergraph-server:user-access:access-control-model.adoc#_built_in_roles[built-in role]: globalobserver*, used in Savanna, for minimal privileges: `READ_SCHEMA` and `READ_LOADINGJOB`.
* *Two new xref:4.2@tigergraph-server:user-access:rbac-row-policy/row-policy-privileges-table.adoc[access privileges]: READ_LOG and APP_ACCESS_LOG* to grant read-only access to log files. `APP_ACCESS_LOG` is specifically designed for xref:4.2@gui:admin-portal:monitoring/log-viewer.adoc#_privilges[
 access from GraphStudio or Savanna].

* [4.2.1] Added the `Security.JWT.JWKS.URL` *xref:4.2@tigergraph-server:user-access:jwt-token.adoc#_setup_jwt_token_gadmin_configuration[configuration parameter]*, to allow JWT certificates to be fetched using the Key ID (kid) from a JWKS (JSON Web Key Set) URL.

=== Integration Enhancements

* *xref:4.2@gsql-ref:querying:data-types.adoc#_s3_object[Writing query output to an S3 object]* can now be configured at the user session level instead at the system administration level, for better alignment of roles and privileges.

* Updated Kafka from 2.5.1 to 3.6.2. Updated Zookeeper from 3.6.3 to 3.8.4.

=== API Enhancements

* *New endpoints to xref:4.2@tigergraph-server:API:gsql-endpoints.adoc#_get_schema_information_from_a_snowflake_data_source[fetch schema information and sample data from Snowflake]*.

* Added a **REST endpoint to xref:4.2@tigergraph-server:API:gsql-endpoints.adoc#_delete_udt_files[delete user-defined function files]**.

* The *Interpret Query endpoint `POST /gsql/v1/queries/interpret`* can now be used with queries that have a xref:4.2@gsql-ref:querying:query-operations.adoc#_complex_type_parameter_passing[datetype parameter].

* The *Edge Upsert endpoint* now supports xref:4.2@tigergraph-server:API:upsert-rest.adoc#_upserting_multi_edges_with_discriminators[upserting the multiple edges of a discriminated edge] in a single API request.

* [4.2.1] Added endpoints to *xref:4.2@tigergraph-server:API:gsql-endpoints.adoc#_list_running_queries[list running queries]* and *xref:4.2@tigergraph-server:API:gsql-endpoints.adoc#_list_running_loading_jobs[list running loading jobs]* for a specific graph. Each endpoint shows currently running queries or loading jobs, plus a `hasRunning` indicator.

* [4.2.1] *xref:4.2@tigergraph-server:API:built-in-endpoints.adoc[RESTPP endpoints `/query_status`, `/query_result`, `/showprocesslist/{graph_name}`, and `/showprocesslistall`]* now report query status and results across all server nodes in a distributed cluster, not just the node receiving the request. Use the optional `disallow_redirect` parameter to query only the local node, if desired.

=== Query Language Enhancements

* Multiple enhancements to *Syntax V3*, which combines GSQL + OpenCypher + GQL Pattern Matching:

** *xref:4.2@gsql-ref:querying:select-statement/index.adoc#_from_clause[GQL/OpenCypher path pattern syntax]*, within GSQL syntax

** *Run ad hoc OpenCypher queries and single GSQL SELECT blocks directly*  (xref:4.2@gsql-ref:querying:query-modes.adoc[non-procedural interpreted queries])

** *xref:4.2@gsql-ref:querying:operators-and-expressions.adoc#_comparison_operators_and_conditions[comparison operators `=` and `<>`]*  as alternatives to `==` and `!=` in WHERE conditions.

** *link:https://github.com/tigergraph/ecosys/blob/master/tutorials/Cypher.md#optional-match[OPTIONAL MATCH], COALESCE, and IS [NOT] NULL* (OpenCypher)

** *xref:4.2@gsql-ref:openCypher-in-gsql:index.adoc#_opencypher_features_in_gsql[type() and labels() functions]* (OpenCypher)

* *xref:4.2@gsql-ref:querying:data-types.adoc#_query_parameter_types[Map and List query parameter types]* are now supported.

* *LIKE: xref:4.2@gsql-ref:querying:operators-and-expressions.adoc#_like[<string1> LIKE <string pattern>]* can be used anywhere a condition is allowed, and <string pattern> can include functions.

* *xref:4.2@gsql-ref:querying:operators-and-expressions.adoc#_case_expressions[Simple CASE expressions and Searched CASE expressions]*

* *Bitwise Accumulators*: official support for xref:4.2@gsql-ref:querying:accumulators.adoc#_bitwise_comparison_and_logic_operators[comparison and bitwise logic operators].

* *xref:4.2@gsql-ref:querying:func/query-user-defined-functions.adoc#_use_github_to_store_udfs[Configuation parameter `GSQL.Github.Enabled`]* to enable retrieving UDFs from a Github repository.

* *xref:4.2@gsql-ref:querying:query-optimizer/query-profiling.adoc[Query Profiler]* to analyze query execution and performance.

* [4.2.1] Added support for the *xref:4.2@tigergraph-server:API:gsql-endpoints.adoc#_run_a_loading_job["configs"]* object in loading jobs, enabling additional configuration *xref:4.2@gsql-ref:ddl-and-loading:running-a-loading-job.adoc#_parameters[parameters]* via the REST API.

* [4.2.1] Added two new timestamp conversion functions, *xref:4.2@gsql-ref:ddl-and-loading:functions/token/gsql_ts_to_epoch_legacy.adoc[gsql_ts_to_epoch_seconds_legacy()]* and *xref:4.2@gsql-ref:ddl-and-loading:functions/token/gsql_ts_to_epoch_signed.adoc[gsql_ts_to_epoch_seconds_signed()]*, providing enhanced flexibility for date handling in loading jobs, including support for pre-1970 dates.

* [4.2.1] Added support for the xref:4.2@gsql-ref:querying:output-statements-and-file-objects.adoc#_printing_csv_to_a_file_object[`PRINT vt TO_CSV f` syntax] to allow printing a vertex set directly to a CSV file.

* [4.2.1] File objects can now be created with an optional xref:4.2@gsql-ref:querying:declaration-and-assignment-statements.adoc#_file_objects[file permission parameter], allowing users to specify permissions using a Linux octal-encoded file permission code.

=== Data Streaming/Connector Enhancements

* *xref:4.2@tigergraph-server:data-loading:load-from-kafka.adoc[Improved connector for loading from external Kafka source]*: new configuration details. Older connector to
xref:4.2@tigergraph-server:data-loading:load-from-kafka-mm.adoc[] is still available.

* *xref:4.2@gsql-ref:ddl-and-loading:creating-a-loading-job.adoc#_using_clause[Multi-character separators between data fields]* in loading jobs.

//* [TBD] *Spark Connector support for OAuth2 authentication*.

* *xref:4.2@gsql-ref:ddl-and-loading:modifying-a-graph-schema.adoc#_run_schema_change_options[Schema Change options]* `-force` and `-warn` to specify the behavior when loading jobs run during a schema change.

* *Introduced xref:4.2@gsql-ref:ddl-and-loading:modifying-a-graph-schema.adoc#_side_effects_of_schema_change[`DISABLED` Loading Job status]* for jobs which have a schema conflict as a result of a Schema Change.

* Spark Connector supports *xref:4.2@tigergraph-server:data-loading:load-from-spark-dataframe.adoc#_common_options[`OAuth2` authentication]*, enabling seamless JWT token retrieval from third-party IdPs like Azure AD and Auth0 for improved *xref:4.2@tigergraph-server:data-loading:load-from-spark-dataframe.adoc#_authentication_methods[security and token management]*.

=== Performance Improvements

* **xref:4.2@gsql-ref:querying:query-optimizer/query-plan-cache.adoc[Query Plan Caching]**, to speed up the run time of repeated queries.

=== GraphStudio, Admin Portal, and Insights

* Added a new page for changing passwords in **xref:4.2@gui:admin-portal:management/user-management.adoc[TigerGraph Suite]**.
* See the **xref:4.2@insights:release-notes:index.adoc[release notes for Insights 4.2]**.
* [4.2.1] **xref:4.2@gui:graphstudio:export-and-import-solution.adoc#_install_a_pre_built_solution[Added a new entry on the GraphStudio homepage]** to browse and download pre-built solutions, making it easy to import and start projects with common graph use cases.
* [4.2.1] Added support in Insights for global parameters, enabling application-level variables to be defined once and shared across multiple pages.

---

== Fixed issues

=== Fixed and Improved in 4.2.2

==== Functionality

* Fixed schema change failures during retry of DSCApply and restart caused by a schema inconsistency from deprecated or corrupted shared libraries for installed queries (CORE-5250).
* Fixed issue where `/query_status`, `/query_result`, `/showprocesslist`, and `/showprocesslistall` endpoints required requests to specific cluster nodes. These endpoints are now node agnostic for consistent access (CORE-5202).
* Fixed issue where the `pre_upgrade_check_gsql.sh` script failed silently, preventing error messages from being displayed during upgrade checks (GLE-11481).

==== Improvements

* Added the ability to configure file permissions for files generated with the `PRINT TO_CSV` statement in GSQL (GLE-11321).

==== Security

* Fixed the following security vulnerabilities:
CVE-2025-41249, CVE-2025-58056, CVE-2025-58057


=== Fixed and Improved in 4.2.1

==== Functionality


* Fixed missing error message when running a non-procedural GSQL query containing syntax errors at the end (GLE-10295).
* Eliminated false *REST-10015* error message when upserting a single vertex using the `gsql-atomic-level:atomic` flag via REST API (GLE-10680).
* Fixed a GPE crash caused by removing a cluster node or when a Disaster Recovery cluster has fewer replicas than the primary cluster (CORE-4967).
* Fixed the MaxFlow algorithm to return correct results, consistent with documented examples (GLE-10737).
* Fixed a UDF parsing error that failed to detect user-defined function names which conflict with built-in functions (GLE-10326).
* Fixed an issue where the system would throw a NullPointerException and fail to create or install a query during code validation (GLE-10501).
* Fixed an issue where authentication was skipped when replaying requests in a Disaster Recovery cluster (GLE-10702).
* Improved the upgrade process by performing query and token bank compilation checks during pre‑upgrade instead of post-upgrade (GLE‑9459).
* Fixed GSQL startup failures during upgrade caused by errors while verifying dictionary and UDF files (GLE-11224).
* Fixed: If an interpreted non-procedural query contained an error but the text prior to the error was valid, the partial query would run and ignore the error (GLE-10295).
* Fixed an issue that could cause false negatives or false positives during license checks caused by an underflow in the vertex count reporting (CORE-5117).

==== Improvements

* Reduced disk usage by removing on-disk indexes in cloud mode and deleting main files in both cloud and on-prem deployments (CORE-4930).
* Enhanced security for namespace-scoped TigerGraph Operator installations by separating the necessary cluster roles and namespace roles (TP-7024).
* Improved upgrade logs with a clearer message: *Installation of new TigerGraph version* (TP-8249).
* Improved the xref:4.2@tigergraph-server:installation:upgrade.adoc#_rolling_upgrade[Rolling Upgrade] documentation to explain how queries behave during upgrades, how retries are handled, and how to tune timeout settings, so users can plan smoother upgrades.
* Improved the xref:4.2@gsql-ref:vector:index.adoc[Vector Search] documentation to detail known limitations, including unsupported ListAccum patterns, use of the ListAccum operator, and WHERE clause restrictions.
* Added support for configuring file permissions when exporting query results with `PRINT TO_CSV`, instead of using hardcoded defaults (GLE-11322).

==== Security

* Eliminated a security vulnerability that allowed AWS credentials to be read in plain text using the `gadmin config get` command. These values are now masked (TP-8285).
* Fixed unauthorized exposure of graph name and creator information via the `/auth/simple` and `/internal/info` APIs (GLE-10746).
* Eliminated the potential exposure of personally identifiable information (PII) in loading job summary files by replacing detailed data with line numbers for invalid entries (TP-8575).
* Eliminated potential exposure of personally identifiable information (PII) in error messages when a loading job semantic check failed during creation (GLE-11125).
* Addressed multiple upstream and OS-level security vulnerabilities through package upgrades and dependency patching. Fixed the following security vulnerabilities:
** CVE-2016-20013, CVE-2016-2781
** CVE-2017-11164, CVE-2017-7475
** CVE-2018-18064
** CVE-2019-6461
** CVE-2020-8908, CVE-2020-29582
** CVE-2021-31879
** CVE-2022-27943, CVE-2022-3219, CVE-2022-41409, CVE-2022-4899
** CVE-2023-29383, CVE-2023-2976, CVE-2023-34969, CVE-2023-37769,
+
CVE-2023-4039, CVE-2023-45288, CVE-2023-45289, CVE-2023-45290,
+
CVE-2023-45918, CVE-2023-48161, CVE-2023-50495, CVE-2023-7008
** CVE-2024-10041, CVE-2024-2236, CVE-2024-23337, CVE-2024-23454, CVE-2024-23944,
+
CVE-2024-24783, CVE-2024-24784, CVE-2024-24785, CVE-2024-24789, CVE-2024-24790, CVE-2024-24791,
+
CVE-2024-34155, CVE-2024-34156, CVE-2024-34158, CVE-2024-41996, CVE-2024-45336, CVE-2024-45341,
+
CVE-2024-52005, CVE-2024-52615, CVE-2024-52616, CVE-2024-56406, CVE-2024-56433, CVE-2024-6763, CVE-2024-8176

** CVE-2025-0167, CVE-2025-0913, CVE-2025-1352, CVE-2025-1376, CVE-2025-22233, CVE-2025-22234, CVE-2025-22235,
+
CVE-2025-22866, CVE-2025-22870, CVE-2025-22871, CVE-2025-22872, CVE-2025-22874, CVE-2025-23022,
+
CVE-2025-27496, CVE-2025-27613, CVE-2025-27817, CVE-2025-27818, CVE-2025-27819, CVE-2025-29088, CVE-2025-30204,
+
CVE-2025-32728, CVE-2025-32988, CVE-2025-32989, CVE-2025-32990, CVE-2025-3576, CVE-2025-41234, CVE-2025-41242,
+
CVE-2025-4598, CVE-2025-4673, CVE-2025-46701, CVE-2025-46835, CVE-2025-46836, CVE-2025-47907, CVE-2025-48060,
+
CVE-2025-48734, CVE-2025-48924, CVE-2025-48988, CVE-2025-48989, CVE-2025-49125, CVE-2025-49146, CVE-2025-49574,
+
CVE-2025-52520, CVE-2025-53506, CVE-2025-55163, CVE-2025-6069, CVE-2025-6395, CVE-2025-7345, CVE-2025-8176


=== Fixed and Improved in 4.2.0

==== Functionality

* Fixed issue where the loading job status was incorrectly cleaned up in advance due to an inaccurate loading job counter (TP-4741).
* Fixed issue where the loader would fail silently, and now it reports an error directly if the loader fails to start (TP-6420).
* Fixed issue where loading an empty file triggered a failure loop (TP-6530).
* Fixed issue with audit error codes being logged when a CDC message fails to deliver to external Kafka (CORE-4249).
* Fixed critical disk issue caused by the rebuilder getting stuck in a partitioned cluster after dropping vertex or edge attributes (CORE-4303).
* Fixed issue where CDC EDGE messages with "UNKNOWN" ID were not removed when a query deleted a vertex and edge simultaneously (CORE-4457).
* Fixed issue where the primary ID was missing when inserting a vertex implicitly from loading an edge in a single-partition cluster and the target vertex used "primary_id_as_attribute=true" (GLE-7562).
* Fixed issue with running the TigerGraph command `gcollect` on Kubernetes (TP-6353).
* Added namespace as a suffix of the HostName in HostList on Kubernetes (TP-6214).
* Fixed query compilation errors when iterating over `FOREACH` to retrieve an accum type attribute with the `-single` or `distributed` keyword; ensured operations between two different `GroupByAccums` hold the same data types and field names (GLE-8507).
* Fixed issue with double quotes in literal strings during the creation of a loading job (GLE-8630).
* Fixed the inability to fetch dynamic file output policy during query execution (GLE-4847).
* Fixed issue where sensitive information was not removed from the browser localStorage, ensuring better security (APPS-1066)
* Fixed a query installation failure for single-node queries that initialize vertex set variables in conditional branches, such as `if-else` or `case-when` statements (GLE-7369).
* Added a button to refetch real-time graph statistics on the Load Data page in GraphStudio (APPS-2565).
* Added the standard Triangle Counting Algorithm to the built-in query list on the Write Query page in GraphStudio (APPS-3429).
* Fixed the issue where query creation failed with a "query not found" prompt in GraphStudio (APPS-3624).
* Removed the requirement to restart the GSQL service after modifying the SSO settings in Admin Portal (APPS-3167).
* Allowed aborting a query in GraphStudio (APPS-3487).
* Checked that the buffer length is non-negative before reading a file (TP-6690).
* Fixed the issue where unauthorized users could access sensitive data, including superuser info, via the `/gsql/v1/users` API endpoint (GLE-8290).
* Fixed `NoSuchElementException` thrown when removing all authentication tokens (GLE-8937).
* Fixed issue with data source creation failing to sync to Disaster Recovery (DR) due to complex payload handling (GLE-9617).
* Fixed bug with the `to_vertex_set` function (GLE-8083).
* Unblocked the usage of the keyword “function” as a vertex/edge/attribute name (GLE-9803).
* Fixed the backup restoration issue where GSQL was in a warmup state when importing GSQL data (TP-6949).
* Fixed the metrics issue where `tigergraph_cpu_usage` exceeded 100 and `tigergraph_cpu_available` was negative under high load (TP-7127).
* Fixed issue where failed backups in corner cases caused the Engine to pause for an extended period, leading to subsequent query timeouts (CORE-4532).
* Resolved the issue with downloading GSQL output files larger than 3GB in AdminPortal (APPS-3271).
* Fixed an issue where the `GSQL-TIMEOUT` header was not being forwarded in the `/api/graphql/gsql` endpoint (APPS-3648).
* Fixed a bug where local accumulators defined across multiple lines in a query were misinterpreted as a file in the GSQL client (GLE-8261).
* Allowed the `globaldesigner` role to monitor queries in Admin Portal (APPS-3172).


==== Improvements

* Improved performance of GSQL queries containing DELETE statements intended for deleting all vertices of a given type (GLE-8328).
* Added support for debug mode when a pod restart fails due to a PostStartHookError (TP-7228).
* Corrected the logic for the SelectVertex() function so it throws an error if the filePath is not an absolute path.

==== Security

* Fixed the following security vulnerabilities:
CVE-2023-45288, CVE-2024-24790, CVE-2024-34156, and CVE-2024-45337.

== Known Issues and Limitations

[%autowidth, cols="4", separator=¦]
|===
¦ Description ¦ Found In ¦ Workaround ¦ Fixed In


¦If a non-procedural query has a syntax error, the GSQL interpreter ignored the invalid portion and executed the partial query before the error, without raising an error.
¦4.2.0
¦Check the full query before accepting it.
¦4.2.1

¦A NullPointerException occurs when performing a code check for queries using statements other than a = vt.* or a = {vt.*}, causing query creation to fail.
¦4.1.3
a¦TBD
¦TBD

¦When `pulldict` fails, an empty debug log is generated, as the log level for debug is not enabled by default.
¦4.1.3
a¦TBD
¦TBD

¦After upgrading, the system fails to detect `to_string()` in the UDF file, leading to query compilation errors. This issue occurs because the system doesn't report parsing errors during file uploads.
¦4.1.3
a¦TBD
¦TBD

¦When using `set(index, value)` and `flip(index)` with BitwiseOrAccum<1000>, the task fails due to lack of support for bit operators `(&, |, ~)` in bitwise accumulation.
¦4.1.3
a¦TBD
¦TBD

¦Using xref:{page-component-version}@gsql-ref:querying:accumulators.adoc#_bitwiseandaccum_bitwiseoraccum[`.flip()`] on `BitwiseAndAccum` or `BitwiseOrAccum` inside a `PRINT` block may produce different results in UDF mode versus Single/Distributed mode.
¦4.1.3
a¦Move the `.flip()` logic to the POST-ACCUM block for consistent behavior.
¦TBD

¦After a cluster expansion, the GPE service may remain in the warmup state.
¦4.1.1
a¦If this happens, run `gadmin restart gse -y` to release the GPE.
¦TBD

¦The `EXECUTE_QUERY` privilege is not enforced on RESTPP endpoints. That is, users who lack `EXECUTE_QUERY` can still run a query via

 `POST /restpp/query/{graph_name}/{query_name}`
¦4.1
¦Use legacy methods for access control: Define separate graphs which span the same data but have different queries and users.
¦TBD


¦If a RESTPP request is for a graph operation and thus sent to the GPE then fails inside the GPE, the RESTPP will interpret the response from the GPE as success and report SUCCEED in the audit log.
¦4.1
¦Use a `/gsql` endpoint instead of a `/restpp` endpoint.
¦TBD

¦ When xref:installation:upgrade.adoc#_upgrading_from_3_x[upgrading], possible permission error for destination folder.
¦ 3.10.1
¦ Manually grant permission to `/var/tmp`
¦ TBD


¦ xref:{page-component-version}@backup-and-restore:database-import-export.adoc[Export] does not include LDAP proxy groups
¦ 3.9+
¦ Manually recreate the proxy groups on the imported database.
¦
|===
=== Compatibility Issues

[cols="2,^1", separator=¦ ]
|===
¦ Description ¦ Version Introduced

¦Many REST API endpoints were updated, including consolidation, path prefix changes, and token authentication support. See the xref:4.1@tigergraph-server:API:index.adoc[REST API reference] page.
¦v4.1.0

¦Long and dynamic length xref:4.2@gsql-ref:querying:accumulators.adoc#_bitwiseandaccum_bitwiseoraccum[BitwiseAccum] (`BitwiseOrAccum`/`BitwiseAndAccum` with length >64 or variable length) are not supported in distributed mode. Both types are limited to 10,000,000 bits, and comparisons/arithmetic between two such accumulators are blocked.
¦v4.2.1

¦To apply a xref:security:gsql-file-input-policy.adoc[File Input Policy] or xref:security:file-output-policy.adoc[File Output Policy] change, now both `gsql` and `restpp` servers must be restarted: `gadmin restart gsql restpp -y`
¦v4.1.3, v4.2.0

¦The xref:backup-and-restore:incremental-backup.adoc[`--incremental` option for backup] now performs a true incremental backup instead of a differential backup.
¦v4.2.0

¦In xref:system-management:change-data-capture/cdc-message-example.adoc#_message_examples[CDC messages], the format of *tuple values* has changed.
¦v4.2.0

¦SelectVertex() may not be used with a relative filepath but previously this was not enforced. It is now enforced.
¦v4.2.0


¦The 'graph' field is now included in xref:system-management:change-data-capture/cdc-message-example.adoc#_message_examples[CDC messages] generated by the TigerGraph CDC service.
¦v3.11.0, v4.1.1


¦In xref:system-management:change-data-capture/cdc-message-example.adoc#_message_examples[CDC messages], the format of *map values* has changed.
¦v3.11.0, v4.1.1

¦A full export package now includes access policies and template queries.
¦v4.1.0

¦ Users could encounter file input/output policy violations when upgrading a TigerGraph version.
See xref:security:gsql-file-input-policy.adoc#_backward_compatibility[Input policy backward compatibility.]
¦ v3.10.0

¦ When a PRINT argument is an expression, the output uses the expression as the key (label) for that output value.
To better support Antlr processing, PRINT now removes any spaces from that key. For example, `count(DISTINCT @@ids)` becomes `count(DISTINCT@@ids)`.
¦ v3.9.3+

¦ Betweenness Centrality algorithm: `reverse_edge_type (STRING)` parameter changed to `reverse_edge_type_set (SET<STRING>)`, to be consistent with `edge_type_set` and similar algorithms.
¦ v3.9.2+

¦ For vertices with string-type primary IDs, vertices whose ID is an empty string will now be rejected.
¦ v3.9.2+

¦ The default mode for the Kafka Connector changed from EOF="false" to EOF="true".
¦ v3.9.2+

¦ The default retention time for two monitoring services `Informant.RetentionPeriodDays` and `TS3.RetentionPeriodDays` has reduced from 30 to 7 days.
¦ v3.9.2+

¦ The filter for `/informant/metrics/get/cpu-memory` now accepts a list of ServiceDescriptors instead of a single ServiceDescriptor.
¦ v3.9.2+

a¦ Some user-defined functions (UDFs) may no longer be accepted due to xref:security:index.adoc#_udf_file_scanning[increased security screening].

* UDFs may no longer be called `to_string()`. This is now a built-in GSQL function.
* UDF names may no longer use the `tg_` prefix. Any user-defined function that began with `tg_` must be renamed or removed in `ExprFunctions.hpp`.
¦ v3.9+
|===

=== Deprecations and Removals

[cols="2,1,1", separator=¦, heading ]
|===
¦ Description ¦ Deprecated ¦ Removed


¦ The `--meta` option for backup is no longer needed because metadata is now included automatically with backup files.
¦ 3.9.2 ¦ 4.2.0

¦ Streaming connector for external Kafka (3.6 to 3.9.2 version)
¦ 3.9.3 ¦ 4.2.0

¦ The format for tuple structures in CDC messages will change in a future version. The future format is likely to be similar to the
xref:{page-component-version}@tigergraph-server:system-management:change-data-capture/cdc-message-example.adoc#_cdc_message_with_type_edge[new format for maps].
¦ 4.1.1
¦ 4.2

¦ Access Control Lists (ACLs) are no longer supported.
When upgrading from 3.x to 4.x, xref:{page-component-version}@user-access:query-privilege-migration.adoc[ACL privileges will be automatically migrated to object-based privileges].
¦ 4.1.0
¦ 4.1.0

¦ The use of plaintext tokens in xref:{page-component-version}@tigergraph-server:API:authentication.adoc[authentication] is deprecated.
Use xref:{page-component-version}@tigergraph-server:user-access:jwt-token.adoc[] instead.
¦ 3.10.0
¦ TBD

¦ *Vertex-level Access Control* (VLAC) and VLAC Methods are removed and are no longer available.
¦ 3.10.0
¦ 4.1.0

¦ The command `gbar` is removed and is no longer available.
It has been replaced by `gadmin backup`.
¦ 3.7
¦ 3.10

¦ xref:{page-component-version}@tigergraph-server:data-loading:spark-connection-via-jdbc-driver.adoc[Spark Connection via JDBC Driver] is now deprecated and will no longer be supported.
¦ 3.10.0 
¦ TBD

¦ `Build Graph Patterns` is deprecated and will not be updated or supported and instead
we are focusing on xref:{page-component-version}@insights:widgets:index.adoc[Insights] as the tool of choice for building visual queries.
¦ 3.9.3
¦ TBD

¦ Kubernetes classic  mode (non-operator) is deprecated.
¦ 3.9
¦ TBD

¦ The `WRITE_DATA` RBAC privilege is deprecated.
¦ 3.7
¦ 4.1
|===

== Release notes for previous versions

* xref:4.1@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 4.1]
* xref:3.11@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.11]
* xref:3.10@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.10]
* xref:3.9@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.9]
* xref:3.6@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.6]
