= TigerGraph DB Release Notes
:description: Release notes for TigerGraph {page-component-version} LTS.
//:page-aliases: change-log.adoc, release-notes.adoc
:fn-preview: footnote:preview[Features in the preview stage should not be used for production purposes. General Availability (GA) versions of the feature will be available in a later release.]
:pp: {plus}{plus}
:toc:
:toclevels:2

TigerGraph Server 3.10.4 LTS was released on July 10, 2025.

TigerGraph Server 3.10.3 LTS was released on Jan 28, 2025.

TigerGraph Server 3.10.2 LTS was released on Oct 18, 2024.

TigerGraph Server 3.10.1 LTS was released on May 7, 2024.

TigerGraph Server 3.10.0 preview version was released on March 13, 2024.

LTS versions are supported for 24 months from their initial GA release (X.X.1) and should be the choice for production deployments.

== Key New Features

* xref:3.10@tigergraph-server:system-management:change-data-capture/cdc-overview.adoc[Change Data Capture (CDC)] - This equips TigerGraph users with the capability to automatically capture and stream data changes to external Kafka systems maintained by the user.
Additionally, CDC can be xref:3.10@gui:admin-portal:components/cdc.adoc[configured] in xref:3.10@gui:admin-portal:overview.adoc[Admin Portal].

* xref:3.10@tigergraph-server:system-management:workload-management.adoc#_workload_queues[Workload Queue] - Configure workload queues so that queries are routed to the appropriate queues during runtime.

* xref:3.10@tigergraph-server:data-loading:load-from-spark-dataframe.adoc[Spark Connector] - A new dedicated connector used with Apache Spark to read data from a Spark DataFrame and write to TigerGraph.

* xref:3.10@tigergraph-server:backup-and-restore:online-backup.adoc[] - Minimizes blocking time during backups, allowing successful execution of post requests for TigerGraph users.

* xref:3.10@tigergraph-server:backup-and-restore:differential-backups.adoc[] - Ensure data files that have changed since the most recently completed full backup are backed up without any data lost.

* xref:3.10@tigergraph-server:installation:upgrade.adoc#_upgrading_from_3_x[Refined Upgrading process] - Changes to the upgrading process to allow a TigerGraph upgrade without having to upgrade the K8's operator.

* xref:3.10@tigergraph-server:installation:upgrade.adoc#_option_n[Support Non-Interactive Upgrade] - The user can use option `-n` to avoid input ( `y/n` ) to switch to the new version.

* xref:3.10@gsql-ref:ddl-and-loading:modifying-a-graph-schema.adoc#_global_vs_local_schema_changes[Global Schema Restrict to Global Scope] - Users must have the global scope to interact with global schema change jobs (create, delete, run).

== Detailed List of New and Modified Features

=== TigerGraph Server

* [3.10.1] xref:3.10@tigergraph-server:reference:configuration-parameters.adoc#_environment_variables[Two new configurations to help tune re-builder scheduling logic] -  When running `GPE.BasicConfig.Env.` there are two new configurations `SegmentMetaFlushAlways` and `SegmentMetaForceFlushIntervalSec` to help fine tune re-builder scheduling.

* [3.10.1] xref:3.10@tigergraph-server:installation:hw-and-sw-requirements.adoc#_certified_operating_systems[Ubuntu 22.04 is now certified] - Ubuntu 22.04 is now one of TigerGraph's certified OS systems.

* [3.10.1] xref:3.10@tigergraph-server:troubleshooting:audit-log.adoc#_rest_api_call_audit_logs[Audit log support for direct RESTPP API calls] - Audit logs now record direct REST++ API Calls.

* [3.10.1] Added new xref:3.10@tigergraph-server:reference:return-codes.adoc[Return Codes]:
** `REST-4000` - Response time exceeds the timeout limit.
** `REST-10020` - License has expired.
** `REST-10021` - Access to the file has failed.
** `REST-30001` - The parameter is invalid (general error).

* [3.10.1] xref:3.10@tigergraph-server:reference:configuration-parameters.adoc[New configuration field System.Metrics.IncludeHostName] - Users now have the option to include hostname/ip in the metrics output in OpenMetrics format.

* [3.10.1] xref:3.10@tigergraph-server:installation:bare-metal-install.adoc[Nodes can now be paired with hostnames in installation] - Users now can set the node by ip or hostname during installation.
This is supported in both interactive and non-interactive installation.

* [3.10.1] xref:cloud:solutions:access-solution/rest-requests.adoc#_secret_request[Make request with GSQL-Secret] -
users can now use the authorization secret in a request header as a GSQL-Secret.

* [3.10.1] xref:3.10@gsql-ref:appendix:keywords-and-reserved-words.adoc[Four new reserved keywords] - `FUNCTION`, `OPENCYPHER`, `POLICY`, and `ROW` have all been added to the DDL GSQL reserved words and keywords list.

* xref:3.10@tigergraph-server:troubleshooting:audit-log.adoc[] - Audit logs maintain a historical record of activity events, noting the time, responsible user or service, and affected entity.

* xref:3.10@tigergraph-server:backup-and-restore:single-graph-import-export.adoc[] - Users can now import or export individually selected graphs.

* xref:3.10@tigergraph-server:cluster-and-ha-management:set-up-crr.adoc[Updates to the Set Up CRR] - Updates to the Cross-Region Replication (CRR) setup enable this feature to flow into the `gadmin backup restore` process preventing a writable gap.

* xref:3.10@tigergraph-server:data-loading:externalizing-kafka-configs.adoc[Externalizing Kafka Configs using Config Provider] - TigerGraph’s Kafka connector config will use a reference to retrieve the config value from an external source.

* xref:3.10@tigergraph-server:system-management:management-commands.adoc#_gadmin_backup_create[Two new flags for gadmin backup create] - added two parameters to enable data consistency checks during the backup.

* [3.10.4] xref:3.10@tigergraph-server:reference:configuration-parameters.adoc#_zk[New ZK.SnapCount configuration] enables users to fine-tune the number of committed ZooKeeper transactions that trigger a ZK log file, enhancing memory management and stability under high transaction loads.

=== GSQL Command and Querying Language

* xref:3.10@gsql-ref:querying:func/context-functions.adoc[] - Context functions are a set of new built-in functions that provide insights into the user's information and work inside `INSTALLED` queries, `INTERPRET` queries, and xref:3.10@tigergraph-server:user-access:rbac-row-policy/rbac-row-policy.adoc#_gsql_functions[GSQL Functions].

* xref:3.10@tigergraph-server:system-management:management-commands.adoc[Command Updates] - Added new flag `--local` to commands xref:3.10@tigergraph-server:system-management:management-commands.adoc#_gadmin_start[gadmin start] and xref:3.10@tigergraph-server:system-management:management-commands.adoc#_gadmin_stop [gadmin stop] reducing the time required to start/stop local services.

* [3.10.4] Added two new timestamp conversion functions, xref:3.10@gsql-ref:ddl-and-loading:functions/token/gsql_ts_to_epoch_legacy.adoc[gsql_ts_to_epoch_seconds_legacy()] and xref:3.10@gsql-ref:ddl-and-loading:functions/token/gsql_ts_to_epoch_signed.adoc[gsql_ts_to_epoch_seconds_signed()], providing enhanced flexibility for date handling in loading jobs, including support for pre-1970 dates.

==== Loading

* xref:3.10@tigergraph-server:data-loading:load-from-warehouse.adoc[Support for Snowflake Data Warehouse] - Added support for loading data from Snowflake, another popular data warehouse.

* xref:3.10@tigergraph-server:data-loading:load-from-warehouse.adoc[Support for PostgreSql Data Warehouse] - Added support for loading data from PostgreSql, another popular data warehouse.

* xref:3.10@tigergraph-server:data-loading:avro-validation-with-kafka.adoc[] - The KafkaConnect feature flag `ErrorTolerance` enables data loading services to handle malformed data and report errors effectively

* xref:3.10@tigergraph-server:cluster-and-ha-management:ha-overview.adoc#_file_and_kafka_loaders_ha_with_auto_restart[Local file and Kafka loader Auto-Restart] - Local file and Kafka loader will now auto restart if it unexpectedly quits.

==== Schema

* New non-interactive mode GSQL operations - Added four new non-interactive mode for operations xref:3.10@tigergraph-server:user-access:user-management.adoc#_non_interactive_mode[create user], xref:3.10@tigergraph-server:user-access:user-management.adoc#_non_interactive_mode[alter password], xref:3.10@tigergraph-server:backup-and-restore:database-import-export.adoc#_non_interactive_mode_export_graph_all[export graph all], and xref:3.10@tigergraph-server:backup-and-restore:database-import-export.adoc#_non_interactive_mode_import_graph_all[import graph all].

==== Querying and Query Management

* [3.10.1] xref:3.10@gsql-ref:ddl-and-loading:modifying-a-graph-schema.adoc#_impact_warning[New impact warnings when running schema change job] - Added a warning message when running the global or local schema change job so, users can understand the impact of running a global or local schema change on a query.

* xref:3.10@gsql-ref:querying:accumulators.adoc#_edge_accumulators[Support Edge Accumulators] - Support for edge accumulators for a single-hop distributed query.

* xref:3.10@gsql-ref:ddl-and-loading:modifying-a-graph-schema.adoc#_run_global_schema_change_job[Option -N to schema change job] - Added an option to `RUN SCHEMA_CHANGE JOB` that skips recompile and reinstall queries.

=== System Management and Monitoring Enhancements ===

* [3.10.2] **xref:3.10@tigergraph-server:API:built-in-endpoints.adoc#_monitor_system_metrics_openmetrics_format[Enhanced Metrics Reports]**
Total and available capacity for CPU and memory are now reported by the `/informant/metrics` endpoint.

=== Data Streaming/Connector Enhancements

* [3.10.4] *xref:3.10@tigergraph-server:data-loading:load-from-kafka.adoc[Improved connector for loading from external Kafka source]*: new configuration details. Older connector to
xref:3.10@tigergraph-server:data-loading:load-from-kafka-mm.adoc[] is still available.

* [3.10.4] *Spark Connector now supports xref:3.10@tigergraph-server:data-loading:load-from-spark-dataframe.adoc#_configure_the_connector[`OAuth2` authentication]*, enabling seamless JWT token retrieval from third-party IdPs like Azure AD and Auth0 for improved xref:3.10@tigergraph-server:data-loading:load-from-spark-dataframe.adoc#_authentication_methods[security and token management].

=== Kubernetes Operator

* [3.10.1] xref:3.10@tigergraph-server:kubernetes:k8s-operator/index.adoc[Kubernetes Operator is GA]  - The Kubernetes Operator is now in GA with 3.10.1.

* https://github.com/tigergraph/ecosys/blob/master/k8s/docs/07-reference/configure-tigergraph-cluster-cr-with-yaml-manifests.md[Added new fields] - `.spec.tigergraphConfig` in TigerGraph CR and a new option `--tigergraph-config` in kubectl-tg plugin.

* https://github.com/tigergraph/ecosys/blob/k8s-operator/0.1.0/k8s/docs/07-reference/configure-tigergraph-cluster-cr-with-yaml-manifests.md[Updates to cluster creation using YAML] - Improvements to the configurations to align with the database.

* https://github.com/tigergraph/ecosys/blob/k8s-operator/0.1.0/k8s/docs/03-deploy/multiple-persistent-volumes-mounting.md[Support for mounting multiple PVC and PV for pods] - Added two optional fields `additionalStorages` and `spec.storage` to customize the PV for TigerGraph pods.

* https://github.com/tigergraph/ecosys/blob/k8s-operator/0.1.0/k8s/docs/03-deploy/customize-tigergraph-pod.md[Support for customizing of pods] -  Customize the pods or containers, for example, users can add more customized labels and annotations or change the security context of the containers.

* https://github.com/tigergraph/ecosys/blob/k8s-operator/0.1.0/k8s/docs/07-reference/configure-tigergraph-cluster-cr-with-yaml-manifests.md[Pause a running cluster] -
Added a new field `.spec.pause` in TigerGraph CR and a new subcommand `kubectl tg pause` in `kubectl-tg plugin`.
Users scan set `.spec.pause=true` to pause a running cluster and resume it by setting `.spec.pause=false`.

=== Security

* [3.10.1] xref:3.10@tigergraph-server:user-access:sso.adoc#_match_strategy_extensions[SSO Match Strategy Extension] - SSO match strategy has been extended to allow matches via regular expression.

* [3.10.1] xref:3.10@tigergraph-server:user-access:jwt-token.adoc#_optional_configurations[Added a JWT Token config] - `Security.JWT.Audience` added to allow users
to set a JWT Token authentication that verifies if the `aud` (recipient for which the JWT is intended) defined in JWT Token matches the configured one or not.

* xref:3.10@tigergraph-server:user-access:rbac-row-policy/row-policy-overview.adoc[RBAC: Row Policy (Preview Feature)] - is used to control access to specific rows of data in TigerGraph.
See also xref:3.10@tigergraph-server:user-access:rbac-row-policy/row-policy-ebnf.adoc[] for examples.

* xref:3.10@tigergraph-server:user-access:rbac-row-policy/rbac-row-policy.adoc#_object_based_privileges[Object-Based Privileges] - This mechanism allows users to grant or revoke privileges based on specific objects.
See xref:3.10@tigergraph-server:user-access:rbac-row-policy/row-policy-privileges-table.adoc[] for a complete list.

* xref:3.10@tigergraph-server:user-access:jwt-token.adoc[] - Provides token-based authentication in JSON web token (JWT) format, allows TigerGraph users better control over application access.

* xref:3.10@tigergraph-server:security:gsql-file-input-policy.adoc[] - `GSQL.fileInputPolicy` allows users to apply restrictions on the location of local files used to load data to TigerGraph.

* Kafka Security via SSL - Kafka brokers can be secured by SSL including the connections from Kafka clients to Kafka brokers.

== TigerGraph Suite Updates
=== Admin Portal

* xref:3.10@gui:admin-portal:components/cdc.adoc[Change Data Capture (CDC)] can be enabled in xref:3.10@gui:admin-portal:overview.adoc[Admin Portal].

* xref:3.10@gui:admin-portal:security/sso-oidc-okta.adoc[SSO.OIDC via Okta] - Support for Standard OIDC Authorization Code Flow for general purpose adds more security for logins to Admin Portal Users.

=== GraphStudio

* xref:3.10@gui:graphstudio:export-and-import-solution.adoc[Single Graph Import and Export Support]  - Allow users to choose a single graph and the data when they export or import data in GraphStudio.

* xref:3.10@tigergraph-server:reference:configuration-parameters.adoc#_gui[New GUI command to disable concurrent sessions ] - `GUI.EnableConcurrentSession` allows users to disable concurrent sessions so that multiple browsers cannot log in with the same username at the same time, revoking the previous session and warning the user to re-login.

=== TigerGraph Insights

* xref:3.10@insights:widgets:single-value.adoc[Changing Single Value Widget to Value Widget]  - Modified the value element of insights to support the mapping of multiple values.
* xref:3.10@insights:widgets:markdown-widget.adoc[Added Markdown Widget] - This addition allows users to add formatted text, links, images, and other rich content to the dashboards.
* xref:3.10@insights:widgets:conditional-styling.adoc[Conditional Styling Widget Update] - Conditional styling can now be applied to edges, with the addition of an `always` xref:3.10@insights:widgets:conditional-styling.adoc#_always_option[option] in the condition dropdown.
* xref:3.10@insights:widgets:scatter-plot-widget.adoc[Added Scatter Chart Widget] - The scatter chart will provide a visual representation of the relationship between two numerical variables, allowing users to identify patterns or correlations in the data.

== Fixed issues

=== Fixed and Improved in 3.10.4

==== Functionality

* Fixed an issue where incorrect queries with syntax or semantic errors were allowed to be installed (GLE-10432).
* Fixed a backward compatibility issue that caused system unavailability or schema check failures after upgrading when the keyword `function` was used in vertex attributes (GLE-9840).
* Fixed an Out-of-Memory (OOM) issue that occurred during file loading operations (TP-8151).
* Fixed an issue where a loading job inserted invalid vertex attribute values when reducer operators such as `and()`, `ignore_if_exists()`, `max()`, or `min() were used (CORE-4866).
* Fixed a GraphStudio issue where retrieving the query list in Write Queries would get stuck when creating a large query (GLE-10461).
* Fixed an issue where users could not locate a vertex in the GraphStudio result when the executed query only printed edges (APPS-3991).
* Fixed an issue in GraphStudio where an incorrect `query not running` error message appeared when aborting a query in the Admin Portal on multi-node systems (APPS-3962).
* Fixed an issue in GraphStudio where the delete query button was incorrectly enabled for queries that were only saved but not yet installed, causing an error when attempting to delete them (APPS-3917).
* Fixed an issue in GraphStudio where query changes were lost or reverted when clicking the Save button immediately after editing or fixing syntax errors (APPS-3916).
* Fixed issue where queries with certain syntax errors disappeared during installation, because the internal codecheck utility returned an empty result instead of an error message (GLE-10467).
* Fixed an Out-of-Memory (OOM) issue that caused RESTPP to crash during timeout checks on asynchronous queries (CORE-4885).

==== Improvements

* Upgraded Nginx to version 1.26 (TP-8129).
* Removed the authentication step required for replaying requests in the Disaster Recovery (DR) environment during regular Cross-Region Replication (CRR) operations (GLE-10601).

==== Security

* Removed GraphStudio exploration results and loading job sample data from `gui/data.json` to prevent potential leakage of Personally Identifiable Information (PII) during schema export (APPS-3946).
* Masked sensitive user IDs (vertex primary IDs) in system logs to enhance data privacy and prevent potential leakage of PII (CORE-4860).
* Third-party Vulnerabilities NOT impacting TigerGraph: 
+
Fixed the following security vulnerabilities: CVE-2016-20013, CVE-2020-8908, CVE-2023-2976, CVE-2023-7008, CVE-2023-45289, CVE-2024-23454, CVE-2024-23944, CVE-2024-31141, CVE-2024-34155, CVE-2024-34156, CVE-2024-34158, CVE-2024-45336, CVE-2024-45341, CVE-2024-47535, CVE-2024-51744, CVE-2024-56406, CVE-2024-57699, CVE-2024-6763, CVE-2024-24783, CVE-2024-24784, CVE-2024-24785, CVE-2024-24789, CVE-2024-24790, CVE-2024-24791, CVE-2025-0913, CVE-2025-22866, CVE-2025-22870, CVE-2025-22871, CVE-2025-22872, CVE-2025-22874, CVE-2025-23022, CVE-2025-24970, CVE-2025-25193, CVE-2025-27496, CVE-2025-29088, CVE-2025-30204, CVE-2025-32728, CVE-2025-3576, CVE-2025-4673, CVE-2025-46836, and CVE-2025-48734.
+
Third-party Vulnerability impacting TigerGraph: None

=== Fixed and Improved in 3.10.3

==== Functionality

* Fixed issue where query installation failed for single-node queries that initialize vertex set variables in conditional branches (e.g., if-else or case-when statements) (GLE-8845).
* Fixed query compilation error when iterating through a `FOREACH` statement to retrieve an accum type attribute in a query compiled with the `-single` or `distributed` keyword. Ensured operations between two different `GroupByAccums` hold the same data types and field names (GLE-9053).
* Fixed a parsing issue with loading job creation when using double quotes inside a string literal (GLE-8696).
* Fixed an issue where schema changes could fail to occur during the loading process due to a lock not being removed (GLE-7572).
* Fixed disk critical issue caused by the rebuilder getting stuck in a partitioned cluster after dropping vertex or edge attributes (CORE-4356).
* Fixed an issue where failed backups in rare cases could cause the engine to pause for a long time, leading to query timeouts (CORE-4499).
* Fixed issue where CDC EDGE messages with "UNKNOWN" ID were not removed when a query deleted a vertex and its associated edge (CORE-4491).
* Fixed issue where "UNKNOWN" ID appeared in CDC messages under heavy load conditions on GSE (CORE-4443).
* Fixed issue preventing downloading of GSQL output files larger than 3GB in the AdminPortal, impacting the GUS component (APPS-3277).
* Fixed issue preventing downloading of GSQL output files larger than 3GB in the AdminPortal, impacting the EXE component (TP-6745).
* Ensured GSQL and the GUI are online before importing data during the restore process (TP-6947).

==== Improvements

* Improved the performance of GSQL queries containing delete statements intended for deleting all vertices of a given type (GLE-8930).

==== Security

* Third-party Vulnerabilities NOT impacting TigerGraph: 
+
Fixed the following security vulnerabilities: CVE-2024-43382, CVE-2024-45337, CVE-2024-56128, CVE-2024-8184, CWE-1333, CWE-303, CWE-311, and CWE-639.
+
Third-party Vulnerability impacting TigerGraph: None


=== Fixed and Improved in 3.10.2

==== Functionality

* Fixed issue where local accumulators defined across multiple lines in a query were misinterpreted in the GSQL client (GLE-8259).
* Fixed issue in the post-upgrade check that causes the upgrade to abort due to insufficient permissions to the /tmp directory (GLE-8005).
* Fixed issue where loading jobs with a `WHERE` condition would hang after upgrading from an older version (GLE-7953).
* Added an error report if a schema check is requested but cannot be performed because the GPE is in warmup status (GLE-7898).
* Fixed situation where a query containing a `BREAK` or `CONTINUE` statements could produce incorrect results (GLE-7874).
* Fixed regression problem with installing queries which create lists containing mixed types of numeric data (GLE-7928).
* Resolved an intermittent deadlock in Informant that caused `gadmin status` to fail (TP-5930).
* Fixed int64 value underflow error by explicitly type casting uint64 (CORE-4108).
* Restored the ability to run the TigerGraph `gcollect` command on Kubernetes (TP-6351).
* Fixed issue with database import hanging caused by the status of a loading job not being received by Kafka streaming library (TP-5772).
* Allowed installation to continue on Oracle and RedHat Linux, 8 even if the TigerGraph user is not listed in AllowedUsers in /etc/ssh/sshd_config (TP-5105).
* Fixed an issue so IMPORT ALL will no longer fail due to the schema size being very large (GLE-6505).

==== Security

* Third-party Vulnerabilities NOT impacting TigerGraph: 
+
Fixed the following security vulnerabilities: CVE-2020-25649, CVE-2020-36518, CVE-2021-38153, CVE-2021-45046, CVE-2022-41723, CVE-2022-45685, CVE-2023-1346, CVE-2023-34455, CVE-2023-36478, CVE-2023-42363, CVE-2023-42364, CVE-2023-42365, CVE-2023-42366, CVE-2023-50387, CVE-2023-50868, CVE-2023-52428, CVE-2024-25638, CVE-2024-29025, CVE-2024-29131, CVE-2024-29133, CVE-2024-39338, CVE-2024-4067, CVE-2024-4068, CVE-2024-42459, CVE-2024-42460, CVE-2024-42461, CVE-2024-4603, CVE-2024-4741, CVE-2024-47561, CVE-2024-5535, CVE-2024-7254, CWE-295, CWE-400, and CWE-918.
+
Third-party Vulnerability impacting TigerGraph: None

=== Fixed and Improved in 3.10.1

==== Functionality

* Fixed known issue where the attribute name `memberOf` was case-sensitive. It is now case-insensitive (GLE-6660).
* Fixed issue of clarity for error message/log when global `schema_change` failed for adding edge but it's relied on vertex does not exist (GLE-6751).
* Fixed issue where installation was halted due to TigerGraph disks mounted with `noexec` on AppRoot or DataRoot, preventing execution (TP-4929).
* Fixed issue where there was a delay in loading response times due to syntax detection process in GSQL (GLE-6822).
* Fixed issue were there was a GPE failure reported during query execution prompting relocation from `/tmp` to `System.TempRoot` (GLE-5536).
* Fixed issue where incorrect error response occurred when specified graph does not exist (APS-2824).
* Fixed issue where users encountered error `Vertex expansion failed: c.default.post is not a function` during Explore Neighbors operation in Insight (APS-2840).

==== Security
* Enhanced security by disabling unapproved SSL/TLS protocols of `DHE-RSA-AES128-GCM-SHA256` and `DHE-RSA-AES256-GCM-SHA384` and upgrading to TLS 1.3 in Nginx (APPS-2729).
* Third-party Vulnerabilities NOT impacting TigerGraph: 
+
Fixed the following security vulnerabilities: CVE-2023-45288, CVE-2023-6237, CVE-2024-0727, CVE-2024-0793, CVE-2024-1597, CVE-2024-24786, CVE-2024-2511, CVE-2024-25710, CVE-2024-27088, CWE-835.
+
Third-party Vulnerability impacting TigerGraph: None

//==== Crashes and Deadlocks
//==== Improvements
//==== Security
//==== Performance

=== Fixed and Improved in 3.10.0

==== Functionality
* Fixed issue where if the primary node is offline, access to Graph Studio was interrupted, but resumed once the primary node is back online (APPS-258).
* Fixed issue where some `GPR` and `Interpret` queries that specified the built-in `filter()` function would fail installation because of a row policy or tag filter (GLE-6448).
* Fixed issue when restarting Restpp and resulted in the task count being greater than the actual number (TP-4498).
* Fixed Issue in 3.9.3 and 3.10.0 versions could not run a GSQL query when a single node is down in a High Availability cluster. See xref:3.10@tigergraph-server:cluster-and-ha-management:ha-overview.adoc#_3_9_2_and_below[3.9.2 and below] versions workaround for more details.
* Fixed issue when changes would not save when switching to fullscreen and back in Insights (APPS-2197).
* Fixed issues where a vertex would not move after expanding in `Explore Graph` (APPS-2540).
* Fixed issue in Exception statements where if it was placed before any query-body statements, it would cause both branches of an `IF-ELSE` statement to be executed (GLE-3998).
* Fixed issue where an error in how the `ACCUM` clause is transformed, results in a transformed query with a semantic error. See xref:3.10@gsql-ref:querying:accumulators.adoc#_accumulator_types[accumulator types] for more details on valid types (GLE-5695).
* Fixed issue when parsing a negative float parameter to GSQL CLI in `{key:value}` format would create an argument error (GLE-5875).

==== Crashes and Deadlocks

* Fixed GPE crash during query execution when accumulators values are not vaild. See xref:3.10@gsql-ref:querying:accumulators.adoc#_accumulator_types[accumulator types] for more details (GLE-4411).

==== Improvements

* Improved by significantly reducing the CPU usage when a large number of loading jobs are started at the same time (TP-4159).
* Improved the write speed of loading jobs (TP-4159).
* Improved disk usage optimization by restricting a loading job in waiting status to only consumes disk resources when it actually writes data (TP-4474).
* Improved stability and cohesion of the connector and loader, which helps create better synchronization and reduces inconsistencies in the statuses (TP-4158).
* Improved significantly the pause time during backups from a few minutes to a couple of seconds, regardless of the data size. (CORE-3000).
* Improved data consistency during the backup and restore process (Core-3000).
* Improved availability when one KSL server in error state (TP-4378 & TP-4593).
* Improved the required privilege for `/rebuildnow` and `/deleted_vertex_check` making both now `Graph-level “READ DATA”` privilege and now able to run on DR cluster in CRR feature.(CORE-3291).
* Improved exception statements by adding a xref:3.10@gsql-ref:querying:exception-statements.adoc#_exception_format_not_defined_in_query[default exception format] available in cases where the exception is not defined in the query (GLE-5854)
* Improved long-running RESTPP requests and will now use less memory (CORE-3027).
* Improved log files names from `log.AUDIT` to `log.AUDIT-GSQL` (GLE-6496).
* Improved audit log `timestamp` format by extending format from `2023-12-20 14:42:50.25` to this `2023-12-20T14:42:50.243-07:00` (GLE-6395).
* Improved `userAgent` field clarity in audit logs when authenticating failed. Audit log will now record the correct user agent (GLE-6404).
* Improved audit logs by adding operating system's username to the audit log record (GLE-6394).
* Improved SearchFile experience by increasing the `GRPC_CLIENT_TIMEOUT` (APPS-2711).
* Improved functionality of the `ExprFunction` file to automatically remove the leftover “to_string” function in ExprFunction file (GLE-5834).
* Improved retention strategy for `EventQueue` that improved timely monitoring of the utilization of disk space (TP-4920).
* Improved service logs accuracy to show SSO users username in log (APPS-2496).


==== Security

* Fixed the following security vulnerabilities:
CVE-2017-5645, CVE-2019-10202, CVE-2021-44228, CVE-2023-39325, CVE-2023-3978, CVE-2023-4316, CVE-2023-43642, CVE-2023-44487, CVE-2023-44981, CVE-2023-45133, CVE-2023-45857, CVE-2023-48795, and CVE-2023-5072.


//(TP-4472)
//==== Security
//==== Performance

== Known Issues and Limitations

[cols="4", separator=¦ ]
|===
¦ Description ¦ Found In ¦ Workaround ¦ Fixed In

¦ When xref:installation:upgrade.adoc#_upgrading_from_3_x[upgrading], possible permission error for destination folder.
¦ 3.10.1
¦ Manually grant permission to `/var/tmp`
¦ TBD

¦Running either `EXPORT GRAPH ALL` or `IMPORT GRAPH ALL` resets the TigerGraph superuser's password back to its default value.
¦3.9.1
¦ After running either command, change the superuser's password to make it secure again.
¦TBD

¦xref:{page-component-version}@tigergraph-server:backup-and-restore:database-import-export.adoc[EXPORT GRAPH ALL] does not correctly handle loading jobs containing `DELETE` statements nor graph elements with composite keys. `EXPORT GRAPH ALL` may fail if the data includes a `UDT` with a fixed string size.
¦3.2
¦
¦TBD

¦When using xref:{page-component-version}@tigergraph-server:backup-and-restore:database-import-export.adoc[IMPORT ALL] if a users schema size in the `.zip` file is exceedingly large, the import may fail with an error messages like this:

`Large catalog file key: /1/ReplicaList.json`
¦ 3.2
a¦
* 3.9 and below users need to run the import process manually by executing the GSQL scripts in the `.zip`.
* 3.10.0 and above users should xref:{page-component-version}@tigergraph-server:backup-and-restore:single-graph-import-export.adoc[import single or smaller batches of multiple graphs].
¦ TBD

a¦ If importing a role, policy, or function that has a different signature or content from the existing one, the one being imported will be skipped and not aborted.

.For example:
* If the original function is: `create function lib1.func2(int param1, float param2, string param3) returns (bool) {}`.
* And the user imports the new function: `create function lib1.func2(int param1) returns (bool) {}`. This second one will be skipped.
¦ 3.10.0
¦ Users need to re-create (delete and create) the imported role, policy, or function manually, and make sure that the importing one meets the requirements set by the existing one.
¦ TBD

a¦ xref:{page-component-version}@tigergraph-server:user-access:rbac-row-policy/row-policy-overview.adoc[Row Policy (Preview Feature)] does not yet filter or check vertex attribute data in upsert operations, such as:

* A query with insert statements.
* A file or Kafka loading job.
* A DDL loading request.
* Or a standard upsert request.
¦ 3.10.0
¦ Users should restrict the access of creating/running queries and loading jobs for roles related to row policy.
¦ TBD

¦ In the audit log for GraphStudio, `clientHost` field reports an internal IP instead of the client user's IP. The `clientHost` may be missing a port number.
¦ 3.10.0
¦ N/A
¦ 3.10.2


¦ In file INPUT and OUTPUT policy, if there exists 2 path (`path1` and `path2`) in the configured policy list and `path1` is parent path of `path2`, then `path1` may not be effective.
¦ 3.2 and 3.10.0
¦ Users should avoid using paths if they are nested.

For example, avoid this scenario, path2 = `"/tmp/more"` and path1= `"/tmp"`.
¦ 3.10.1

¦ It has been observed that an issue happens when RESTPP will send a request to all gpes, and if one is down, the request sent to it will `timeout`.
Including the `consistency_check` request will also mark as `timeout`.
¦ 3.10.0
a¦
. Run `/rebuildnow` to rebuild all the segments.
+
[NOTE]
====
Running `/rebuildnow` when one gpe is down will result in the request timeout. This does not mean the request failed, instead only the currently running GPE will do the rebuild, and any rebuild requests sent to the down GPEs will result in a timeout.
====
. Run `/data_consistency_check?realtime=false` to check the consistency.
¦ TBD

¦ While running `EXPORT GRAPH` if the disk space is not enough, or the data has not been detected, the export data will get stuck loading.
¦ 3.10.0
¦ Restart all services in Admin Portal or the backend.
¦ TBD

¦ `[tg_]ExprFunction.hpp` will be automatically merged while importing single graphs. In some cases, query compilation may fail.
¦ 3.10.0
¦ See xref:{page-component-version}@tigergraph-server:backup-and-restore:single-graph-import-export.adoc#_known_issues_and_workarounds[Known Issues and Workarounds]
¦ TBD

¦ Upgrading from a previous version of TigerGraph has known issues.
¦ 3.10.0
¦ See section xref:{page-component-version}@tigergraph-server:installation:upgrade.adoc#_known_issues_and_workarounds[Known Issues and Workarounds] for more details.
¦ TBD

¦ Input Policy feature has known limitations.
¦ 3.10.0
¦ See section xref:{page-component-version}@tigergraph-server:security:gsql-file-input-policy.adoc#_limitations[Input Policy Limitations] for more details.
¦ TBD

¦ Change Data Capture (CDC) feature has known limitations.
¦ 3.10.0
¦ See section xref:{page-component-version}@tigergraph-server:system-management:change-data-capture/cdc-overview.adoc#_cdc_limitations[CDC Limitations] for more details.
¦ TBD

¦ If the `FROM` clause pattern is a multi-hop and the `ACCUM` clause reads both primitive and container type attributes or accumulators of a vertex, the internal query rewriting logic may generate an invalid rewritten output.
¦ 3.9.3
¦ This results in the error message: `It is not allowed to mix primitive types and accumulator types in GroupByAccum`.
¦ TBD

¦ Users may see a high CPU usage caused by Kafka prefetching when there is no query or posting request.
¦ 3.9.3
¦ TBD
¦ TBD

¦ GSQL query compiler may report a false error for a valid query using a vertex set variable (e.g. `Ent` in `reverse_traversal_syntax_err`) to specify the midpoint or target vertex of a path in a FROM clause pattern.
¦ TBD
¦ TBD
¦ TBD

¦ If a loading job is expected to load from a large batch of files or Kafka queues (e.g. more than 500), the job’s status may not be updated for an extended period of time.
¦ 3.9.3
¦ In this case, users should check the loader log file as an additional reference for loading status.
¦ TBD

¦ When a GPE/GSE is turned off right after initiating a loading job, the loading job is terminated internally. However, users may still observe the loading job as running on their end.
¦ 3.9.3
¦ Please see xref:{page-component-version}@gsql-ref:ddl-and-loading:running-a-loading-job.adoc[Troubleshooting Loading Job Delays] for additional details.
¦ TBD

¦ For v3.9.1 and v3.9.2 when inserting a new edge in `GPR` and `INTERPRET` mode, the GPE will print out a warning message because a discriminator string is not set for new-inserted edges. Creating an inconsistent problem in delta message for GPR and `INTERPRET` mode.
¦ 3.9.2
¦ Please see xref:{page-component-version}@gsql-ref:ddl-and-loading:running-a-loading-job.adoc[Troubleshooting Loading Job Delays] for additional details.
¦ 3.9.3

¦ GSQL `EXPORT GRAPH` may fail and cause a GPE to crash when UDT type has a fixed STRING size.
¦ TBD
¦ TBD
¦ TBD

¦ After a global loading job is running for a while a fail can be encountered when getting the loading status due to `KAFKASTRM-LL` not being online, when actually the status is online.
Then the global loading process will exit and fail the local job after timeout while waiting the global loading job to finish.
¦ TBD
¦ TBD
¦ TBD

¦ When the memory usage approaches 100%, the system may stall because the process to elect a new GSE leader did not complete correctly.
¦ TBD
¦ This lockup can be cleared by restarting the GSE.
¦ TBD

¦ If the CPU and memory utilization remain high for an extended period during a schema change on a cluster, a GSE follower could crash, if it is requested to insert data belonging to the new schema before it has finished handling the schema update.
¦ TBD
¦ TBD
¦ TBD

¦ When available memory becomes very low in a cluster and there are a large number of vertex deletions to process, some remote servers might have difficulty receiving the metadata needed to be aware of all the deletions across the full cluster. The mismatched metadata will cause the GPE to go down.
¦ TBD
¦ TBD
¦ TBD

¦ Subqueries with SET<VERTEX> parameters cannot be run in Distributed or Interpreted mode.
¦ TBD
¦ (xref:{page-component-version}@gsql-ref:querying:operators-and-expressions.adoc#_subquery_limitations[Limited Distributed model support] is added in 3.9.2.)
¦ TBD

¦ Upgrading a cluster with 10 or more nodes to v3.9.0 requires a patch.
¦ 3.9
¦ Please contact TigerGraph Support if you have a cluster this large. Clusters with nine or fewer nodes do not require the patch.
¦ 3.9.1

¦ Downsizing a cluster to have fewer nodes requires a patch.
¦ 3.9.0
¦ Please contact TigerGraph Support.
¦ TBD

¦ During peak system load, loading jobs may sometimes display an inaccurate loading status.
¦ 3.9.0
¦ This issue can be remediated by continuing to run `SHOW LOADING STATUS` periodically to display the up-to-date status.
¦ TBD

¦ When managing many loading jobs, pausing a data loading job may result in longer-than-usual response time.
¦ TBD
¦ TBD
¦ TBD

¦ Schema change jobs may fail if the server is experiencing a heavy workload.
¦ TBD
¦ To remedy this, avoid applying schema changes during peak load times.
¦ TBD

¦ User-defined Types (UDT) do not work if exceeding string size limit.
¦ TBD
¦ Avoid using UDT for variable length strings that cannot be limited by size.
¦ TBD

¦ Unable to handle the tab character `\t` properly in AVRO or Parquet file loading. It will be loaded as `\\t`.
¦ TBD
¦ TBD
¦ TBD

¦ If `System.Backup.Local.Enable` is set to `true`, this also enables a daily full backup at 12:00am UTC.
¦ 3.9.0
¦ TBD
¦ 3.9.1

¦ The data streaming connector does not handle NULL values; the connector may operate properly if a NULL value is submitted.
¦ TBD
¦ Users should replace NULL with an alternate value, such as empty string "" for STRING data, 0 for INT data, etc.  (NULL is not a valid value for the TigerGraph graph data store.)
¦ TBD

¦ Automatic message removal is an Alpha feature of the Kafka connector. It has several xref:{page-component-version}@tigergraph-server:data-loading:load-from-cloud.adoc#_known_issues_with_loading[known issues].
¦ TBD
¦ TBD
¦ TBD

¦ The `DATETIME` data type is not supported by the `PRINT … TO CSV` statement.
¦ 3.9.0
¦ TBD
¦ 3.9.1

¦ The LDAP keyword `memberOf` for declaring group hierarchy is case-sensitive.
¦ 3.9
¦ Check the case of the keywords for `memberOf`. This has been fixed in versions 3.10.1 and above.
¦ 3.10.1

¦ After performing a backup and restoring it, all vertex IDs (v_ids) may become "UNKNOWN." This occurs when the local schema is deleted before restoring the backup. This issue results in a mismatch between the Graph Processing Engine (GPE) and the Graph Schema Engine (GSE), which causes data inconsistency.
¦ 3.10.1
a¦ To fix this issue, users can do one of the following:

* Run the `gsql drop all` command before restoring the backup.
* Alternatively, run the backup restore again.
¦ 3.10.2 and 4.1.0 and later.

¦ A GPE crash occurs when a `DELETE` operation is performed on multi-edge types in CDC without specifying a discriminator. This happens when no `filter` or `limit` is applied to constrain the operation, causing the Graph Processing Engine (GPE) to crash.
¦ 3.10.0
¦ Delete multi-edge types one at a time to avoid causing a GPE crash.
¦ 4.1.1

|===

=== Compatibility Issues

[cols="2", separator=¦ ]
|===
¦ Description ¦ Version Introduced

¦ Users could encounter file input/output policy violations when upgrading a TigerGraph version.
See xref:3.10@tigergraph-server:security:gsql-file-input-policy.adoc#_backward_compatibility[Input policy backward compatibility.]
¦ v3.10.0

¦ When a PRINT argument is an expression, the output uses the expression as the key (label) for that output value.
To better support Antlr processing, PRINT now removes any spaces from that key. For example, `count(DISTINCT @@ids)` becomes `count(DISTINCT@@ids)`.
¦ v3.9.3+

¦ Betweenness Centrality algorithm: `reverse_edge_type (STRING)` parameter changed to `reverse_edge_type_set (SET<STRING>)`, to be consistent with `edge_type_set` and similar algorithms.
¦ v3.9.2+

¦ For vertices with string-type primary IDs, vertices whose ID is an empty string will now be rejected.
¦ v3.9.2+

¦ The default mode for the Kafka Connector changed from EOF="false" to EOF="true".
¦ v3.9.2+

¦ The default retention time for two monitoring services `Informant.RetentionPeriodDays` and `TS3.RetentionPeriodDays` has reduced from 30 to 7 days.
¦ v3.9.2+

¦ The filter for `/informant/metrics/get/cpu-memory` now accepts a list of ServiceDescriptors instead of a single ServiceDescriptor.
¦ v3.9.2+

a¦ Some user-defined functions (UDFs) may no longer be accepted due to xref:{page-component-version}@security:index.adoc#_udf_file_scanning[increased security screening].

* UDFs may no longer be called `to_string()`. This is now a built-in GSQL function.
* UDF names may no longer use the `tg_` prefix. Any user-defined function that began with `tg_` must be renamed or removed in `ExprFunctions.hpp`.
¦ v3.9+
|===

=== Deprecations

[cols="3", separator=¦ ]
|===
¦ Description ¦ Deprecated ¦ Removed

¦ The use of plaintext tokens in xref:3.10@tigergraph-server:API:authentication.adoc[authentication] is deprecated.
Use xref:3.10@tigergraph-server:user-access:jwt-token.adoc[] instead.
¦ 3.10.0
¦ 4.1


¦ The command `gbar` is removed and is no longer available.
It has been replaced by `gadmin backup`.
If you are using a version of TigerGraph before 3.10.0, you can use `gbar` to create a backup file and restore it in 3.10 with `gadmin backup restore`.

¦ 3.7
¦ 3.10.0

¦ xref:3.10@tigergraph-server:user-access:vlac.adoc[Vertex-level Access Control (VLAC)] and xref:3.10@gsql-ref:querying:func/vertex-methods.adoc[VLAC Methods] are now deprecated.
¦ 3.10.0
¦ 4.0

¦ xref:3.10@tigergraph-server:data-loading:spark-connection-via-jdbc-driver.adoc[Spark Connection via JDBC Driver] is now deprecated and will no longer be supported.
¦ 3.10.0 
¦ TBD

¦ `Build Graph Patterns` is deprecated and will not be updated or supported and instead
we are focusing on xref:3.10@insights:widgets:index.adoc[Insights] as the tool of choice for building visual queries.
¦ v3.9.3
¦ TBD

¦ Kubernetes classic  mode (non-operator) is deprecated.
¦ v3.9
¦ TBD

¦ The `WRITE_DATA` RBAC privilege is deprecated.
¦ v3.7
¦ TBD
|===

== Release notes for previous versions
* xref:3.9@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.9]
* xref:3.6@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.6]
