= Release Notes
:description: Release notes for TigerGraph {page-component-version} LTS.
:page-aliases: change-log.adoc, release-notes.adoc
:fn-preview: footnote:preview[Features in the preview stage should not be used for production purposes. General Availability (GA) versions of the feature will be available in a later release.]
:toc:
:toclevels:2

TigerGraph Server {page-component-version}.2 LTS was released on June 29, 2023.

TigerGraph Server {page-component-version}.1 LTS was released on March 22, 2023.

TigerGraph Server {page-component-version}.0 LTS was released on February 28th, 2023.

LTS versions are supported for 24 months from their initial release (X.X.0) and should be the choice for production deployments.



== Key New Features

* *xref:3.9@gsql-ref:ddl-and-loading:defining-a-graph-schema.adoc#_discriminator[Multiple edges of the same type between vertices]* - Simplifies application design for time series data and other complex large data sets
* *xref:3.9@tigergraph-server:data-loading:data-streaming-connector/index.adoc[Data streaming connector]* - Simplifies and unifies setup for data loading, employs robust Kafka-based design, supports cloud-hosted data sources in many formats, including Parquet
* *Improved monitoring and logging* - Facilitates better workload management for xref:3.9@gui:admin-portal:monitoring/queries.adoc[queries] and xref:3.9@gsql-ref:ddl-and-loading:managing-loading-job.adoc[loading jobs].

== Detailed List of New and Modified Features

=== TigerGraph Server
* xref:3.9@tigergraph-server:data-loading:data-streaming-connector/index.adoc[]:
** Added support for the xref:3.9@tigergraph-server:data-loading:data-streaming-connector/index.adoc#_define_the_parameters[Parquet file format], widely used for big data.
** Moved data connector setup from `gadmin` to xref:3.9@tigergraph-server:data-loading:data-streaming-connector/[GSQL commmands], to better align with user personas and privileges.
** Added xref:3.9@tigergraph-server:data-loading:data-streaming-connector/index.adoc#_continuous_file_loading [auto-detection of new files] when in Stream mode.
** Significantly improved CPU usage after connector finishes data loading.
** Documented additional xref:3.9@tigergraph-server:reference:configuration-parameters.adoc#_system[S3 authentication configuration parameters].

* Added new xref:3.9@tigergraph-server:API:built-in-endpoints.adoc[REST Endpoints]:
** `/library` is a set of endpoints for showing and running template queries.
** `/showdelayedlistall` shows how many queries are in the Workflow Manager's delay queue.
** `:14240/informant/metrics` replaces `:9167/metrics`
** `/informant/metrics/get/{metrics_category}` provides filterable JSON formatted system performance metrics.
** [3.9.2] The filter for `/informant/metrics/get/cpu-memory` now accepts a list of ServiceDescriptors instead of a single ServiceDescriptor.
** [3.9.2] `/gsqlserver/gsql/clear-store` is equivalent to `GSQL CLEAR GRAPH STORE -HARD`

* Added or changed xref:3.9@tigergraph-server:reference:configuration-parameters.adoc[configuration parameters]:
** `KafkaConnect.AllowedTaskPerCPU` limits the number of concurrent kafka loading tasks.
** The GSQL environment variable `GPE_DSC_APPLY_TIMEOUT_MINUTE` is the maximum allowed time for dynamic schema changes (DSC).

* Added a new command for `gadmin backup` to xref:3.9@tigergraph-server:backup-and-restore:backup-cluster.adoc#_back_up_a_database_cluster[control the number of backups], for better storage space management.
* Expanded the list of xref:3.9@tigergraph-server:reference:error-codes.adoc[system response codes] to include one for an invalid vertex ID.
* Improved the backend security infrastructure for the Kafka loader.
* [3.9.2] Changed the default retention times for the
xref:3.9@tigergraph-server:reference:configuration-parameters.adoc#_informant[Informant.RetentionPeriodDay] and
xref:3.9@tigergraph-server:reference:configuration-parameters.adoc#_ts3[TS3.RetentionPeriodDay] configuration parameters from 30 days to 7 days, to reduce disk consumption and improve system history query performanace.

=== GSQL Command and Querying Language

==== Loading

* Moved xref:3.9@tigergraph-server:data-loading:data-streaming-connector/index.adoc[data connector] setup from `gadmin` to GSQL.
Streamlined the user experience for creating loading jobs for data stored in AWS, GCP, and Azure, directly integrating the data streaming connector with GSQL and reducing the steps needed to load data.
** Introduced a new `STREAM` data loading type that simplifies the xref:3.9@tigergraph-server:data-loading:index.adoc[data loading process] from remote data storage.
* Added a new set of loading job xref:3.9@gsql-ref:ddl-and-loading:functions/token/index.adoc[token functions for string manipulation].
* [3.9.2] Added configuration parameter xref:tigergraph-server:reference:configuration-parameters.adoc#_kafkaconnect[`KafkaConnect.AllowedTaskPerCPU`] to set a maximum number of concurrent connector tasks.
* [3.9.2] The default mode for the Kafka Connector is `EOF="true"`

==== Schema
* Full support for xref:3.9@gsql-ref:ddl-and-loading:defining-a-graph-schema.adoc#_discriminator[
multiple edges of the same type] between vertices, to simplify application design for time series data and other complex large data sets.

==== Querying and Query Management
* `to_string()` is now a built-in GSQL function, supporting all xref:3.9@gsql-ref:ddl-and-loading:attribute-data-types.adoc#_primitive_types[primitive] and xref:3.9@gsql-ref:querying:accumulators.adoc#_vertex_attached_accumulators
[scalar accumulator] data types. This means xref:3.9@gsql-ref:querying:func/query-user-defined-functions.adoc[user-defined functions] in `Exprfunctions.hpp` may no longer use the name `to_string()` (case-insensitive).
* Added support for batch deletion of multiple edges between vertices, both with GSQL `DELETE` and as a xref:3.9@tigergraph-server:API:built-in-endpoints.adoc#_delete_an_edge_by_source_target_edge_type_and_discriminator[REST endpoint].
* Standardized `SHOW PACKAGE` for xref:3.9@graph-ml:using-an-algorithm:index.adoc[packaged queries] to follow the same behavior as other `SHOW` catalog commands.
* [3.9.2] `outdegree`
xref:gsql-ref:querying:func/vertex-methods.adoc[vertex function]
vertex function can also be used with vertex input parameters in the query-body statements, not only with SELECT block vertex aliases.

//=== JDBC Spark Connector
//
//* [Alex] Added support for loading job monitoring on xref:3.9@data-loading:spark-connection-via-jdbc-driver.adoc[JDBC Spark connector] loading jobs.
//* [Alex] Added the ability to assign a specific job ID to a JDBC loading job.
//* [Alex] Added error limiting parameters to JDBC loading jobs to cancel loading automatically when errors surpass a certain threshold.

=== Kubernetes Operator

* Enhanced the functionality of the xref:3.9@kubernetes:k8s-operator/index.adoc[] so it is now the standard way to perform cluster operations with Kubernetes.
* Added support for xref:3.9@kubernetes:k8s-operator/backup-and-restore.adoc[], xref:3.9@kubernetes:k8s-operator/cluster-operations.adoc#_upgrade_cluster_version[upgrading the version of the TigerGraph server], and xref:3.9@kubernetes:k8s-operator/cluster-operations.adoc#_update_cluster_resources[updating cluster resources].
* [3.9.2] Support for xref:tigergraph-server:kubernetes:k8s-operator/custom-containers.adoc[].

=== Security

* Improved the backend security infrastructure for the Kafka loader.
* Added xref:3.9@tigergraph-server:security:index.adoc#_udf_file_scanning[configurable security scanning for UDFs].
* Updated our response to xref:master@home::cve-2022-30331.adoc[CVE-2022-30331].

== TigerGraph Suite Updates
=== Admin Portal

* Reworked the xref:3.9@gui:admin-portal:dashboard.adoc[Admin Portal dashboard] to show the relationship hierarchy and status of all TigerGraph components for at-a-glance understanding of the TigerGraph system.
* [3.9.2] Added support for xref:gui:admin-portal:components/README.adoc[configuring two additional components]: GPE and Kafka.

=== GraphStudio

* [3.9.2] Enabled GraphStudio to run on any node in a cluster, whether or not the node hosts a GUI server.
* [3.9.2] Removed the *All Paths* option from the Explore Graph page, as this feature is not practical for large graphs.

=== GDS Library and ML Workbench

* Added xref:1.3@pytigergraph:gds:dataloaders.adoc#nodepieceloader[NodePiece] node embedding algorithm.
* Added pyTigerGraph support for xref:1.3@pytigergraph:core-functions:query.adoc#_runinstalledquery[running queries asynchronously] (i.e., running in the background).
* [3.9.2] Added xref:graph-ml:using-an-algorithm:packaged-template-algorithms.adoc[packaged templated versions] of four xref:3.9@graph-ml:link-prediction:index.adoc[topological link prediction algorithms].
* [3.9.2] Characterized each algorithm by readiness: Alpha, Beta, or Production.
* [3.9.2] In the documentation, added a xref:graph-ml:intro:algorithm-table.adoc[table for Algorithm Availability and Dependencies].
* [3.9.2] In the documentation, added a fuller explanation of how to xref:graph-ml:using-an-algorithm:index.adoc[install and run algorithms] using Python.
* [3.9.2] The node2vec node embedding algorithm has been retired because better alternatives are now available.


=== TigerGraph Insights

* Added support for multi-user editing and sharing of the same xref:3.9@insights:intro:applications.adoc[applications].
* Added the ability for users to xref:3.9@insights:widgets:index.adoc#_save_a_widget[save a widget] independently instead of tying it to an application.
* Added a mini-map to the xref:3.9@insights:widgets:graph-widget.adoc[graph widgets] for easier navigation.

== Fixed issues

=== Fixed and Improved in 3.9.2-1

==== Crashes and Deadlocks
* Fixed GPE crash caused by aborted query still being used by running thread.
* Fixed crash issue after RESTPP auth refresh.
* Fixed GSE crash due to check failure when refreshing leader info after 60 minute timeout.
* Fixed GPE crash and non-recovery due to Kafka retention to a higher offset.

==== Functionality
* Fixed data inconsistency while loading data and post-processing operations
via write queries when running `data_consitency_check` with GPE and GSE.
* Fixed command fail when user with only graph scope privilege runs a command that only requires graph scope privilege.
* Fixed failed to compile query when using edge variables in DML-sub delete statement.
* Fixed `subtypeid` error message inconsistency for GPR and interpret mode.
* Fixed `/deleted_vertex_check` false alert when GSE doesn't have a segment.

==== Security
* Security: Updated JDK to 11.0.20 to address vulnerability scan issues.

==== Performance
* Improved performance of GPE abort function.

=== Fixed and Improved in 3.9.2

==== Crashes and Deadlocks
* Fixed a GPE crash caused by GetVertexTypeId failing to get the type of a vertex.
* Fixed a RESTPP/WorkloadManager deadlock when multiple queries are waiting to execute.
* Fixed a deadlock-like state when free disk space became very low during data loading.
* Fixed a problem with GSQL not responding because no GSQL leader was elected.

==== Functionality
* Fixed importing pre-3.7 user-defined tuple (UDT) data which uses default-width INT or UINT fields.
The import process will set pre-3.7 default-width fields to be 4 bytes.  3.7+ default-width fields are explicitly
* Fixed GSQL not installing queries with certain collection accumulator expressions.
* Restored the functionality of the -`-ssl` option of the GSQL Client.
* Fixed a situation that can result in different cluster nodes having differently compiled versions of the same query, resulting in an MD5 check error.
* Fixed a situation where a request to install one query results in several other queries also being installed.
* Removed an exclusive lock when Interpret Query is running, which had been preventing concurrent GSQL operations
* Fixed a null pointer error when attempting to import into GraphStudio a Solution tarball of a tag-based graph.
* Fixed a case where a schema change did not run because not all libudf.so files had been cleared out.
* Fixed an internal classification error for `FIXED_BINARY` data, which caused a schema_check test failure.
* Fixed a bug where if a loading job used `TEMP_TABLE` and `VERTEX_MUST_EXIST`, then the VERTEX_MUST_EXIST option would not be displayed (by `LS` or `SHOW JOB`), nor would it included in a database export.
* Fixed a GSQL query bug where it did not handle string parameters properly if they contained “&”.
* Fixed a bug when upgrading to 3.9 that caused the old installation’s default `QueryUDF` files to be copied and overwrite the new 3.9 default QueryUDF files, so that queries using UDFs could not be installed.
* Fixed a GSQL log bug where the `PermissionUtil.java` function was logging a stale Command Type rather than the current Command Type.
* Restored limited ability to run xref:gsql-ref:querying:operators-and-expressions.adoc#_subquery_limitations[
subqueries having a SET<VERTEX> parameter].
* Modified the `/deleted_vertex_check` and `/data_consistency_check` endpoints to be global, not associated with any particular graph.
* Fix a SET type attribute bug in which the set’s values were not being deduplicated.
* Patched a user authorization issue that prevented a user registered on a primary cluster from running a query on the secondary cluster.
* Provided a more comprehensive fix to a node sorting issue when upgrading a cluster with 10 or more nodes to v3.9.
* Removed a restriction when load data into an edge defined for multiple FROM-TO vertex type pairs. The load statement no longer must have a USING clause.
* Fixed a signed integer overflow error in loader status report messages, if more than 2^31 lines of data were loaded.
set to 8 bytes.
* Improved the display of FLOAT and DOUBLE numbers so they have the correct number of digits of precision (max. 7 or 16, respectively).
* Fixed a GraphStudio bug in which a vertex attribute which had been deleted was still showing until the browserpage was refreshed.
* When adding a UDF with PUT, check that the UDF is defined as an inline function, as required.

==== Security
* Security: Updated JDK to 11.9.18-10 to address some vulnerability scan issues.
* Security: Updated JSON to 20230227 to address some vulnerability scan issues.
* Improved system security by applying more restrictive file permissions to several files.
* No longer include examples of the data being loading in the Kafka loader log file, for better data security.

==== Performance
* Added lazy initialization of vertex data, for large graphs with more that 20K segments in the gstore.
* Improved query installation memory usage and speed by optimizing gcc9 options.
* Fixed a GraphStudio slowness issue when creating or editing vertices with hundreds of attributes.
* Removed the 5-minute wait that the streaming loader used to decide if all the input data had been consumed.

=== Fixed and Improved in 3.9.1
* Fixed sorting issue in a script for upgrading a cluster with more than 9 nodes.
* If a user runs gadmin and the  `~/.tg.cfg` link is missing, display an error message with guidance on how to recreate the link.
* Fixed: GraphStudio not displaying queries for users with the QueryReader role.
* Removed extraneous automatic backup at 12:00am UTC if the user sets `System.Backup.Local.Enable` to `true`.
* Fixed accidental erasure of the `UserCatalog.yaml` file, which caused users to lose access to the database.
* Added support for `DATETIME` datatype in `PRINT … TO_CSV` statements.
* Added error handling in the case of a name conflict or use of reserved query names among UDF functions.
* Fixed an issue with nested group access in LDAP.
* Fixed an issue with perceived "schema error", which then causes an upgrade to abort.
* Fixed issue with `DISTRIBUTED QUERY` not able to insert on edge.
* Removed C++ headers not on the allowlist from default UDF files.
* Fixed a GSE crash in rare synchronization circumstances in HA clusters.
* Fixed an issue with a query syntax error not being detected at the root cause stage where a clear error message could be issued.
* Added options to configure the frequency of checking for license key violations
* Fixed: GSE does not start or restart after upgrading to 3.9.0 due to change in log synchronization.
* Fixed an issue with lost attribute of a local vertex having `PRIMARY_ID_AS_ATTRIBUTE` =`true`.
* Fixed inability to enable SSL in an HA cluster via the AdminPortal.
* Fixed issue with GPE crashing during heavy workload of a backup retore operation.

=== Fixed in 3.9.0

* Improved stability and security across all components.
* Fixed an issue with the GSQL `SELECT * FROM` and `PRINT` functions converting some special characters from UTF-8 to UTF-16.
Previously affected character sets included the Unicode range `0080` to `00A0` and `2000` to `2100` (Near Eastern scripts and some special typographical marks).
* The `SELECT * FROM` and `PRINT` functions no longer convert large integers to strings before printing, which had resulted in quotation marks printed along with the number.
* xref:3.9@tigergraph-server:cluster-and-ha-management:expand-a-cluster.adoc[Cluster resizing] no longer requires a graph schema.
* Extended the timeout length for queries in the wait queue so that they are not timed out early.

== Known issues

* When the memory usage approaches 100%, the system may stall because the process to elect a new GSE leader did not complete correctly.
This lockup can be cleared by restarting the GSE.
* If the CPU and memory utilization remain high for an extended period during a schema change on a cluster, a GSE follower could crash, if it is requested to insert data belonging to the new schema before it has finished handling the schema update. 
* When available memory becomes very low in a cluster and there are a large number of vertex deletions to process, some remote servers might have difficulty receiving the metadata needed to be aware of all the deletions across the full cluster. The mismatched metadata will cause the GPE to go down.
* Subqueries with SET<VERTEX> parameters cannot be run in Distributed or Interpreted mode.
(xref:3.9@gsql-ref:querying:operators-and-expressions.adoc#_subquery_limitations[Limited Distributed model support] is added in 3.9.2.)
* Upgrading a cluster with 10 or more nodes to v3.9.0 requires a patch. Please contact TigerGraph Support if you have a cluster this large. Clusters with nine or fewer nodes do not require the patch. (This issue is fixed in 3.9.1)
* Downsizing a cluster to have fewer nodes requires a patch. Please contact TigerGraph Support.
* During peak system load, loading jobs may sometimes display an inaccurate loading status. This issue can be remediated by continuing to run `SHOW LOADING STATUS` periodically to display the up-to-date status.
* When managing many loading jobs, pausing a data loading job may result in longer-than-usual response time.
* Schema change jobs may fail if the server is experiencing a heavy workload. To remedy this, avoid applying schema changes during peak load times.
* User-defined Types (UDT) do not work if exceeding string size limit. Avoid using UDT for variable length strings that cannot be limited by size.
* Unable to handle the tab character `\t` properly in AVRO or Parquet file loading. It will be loaded as `\\t`.
* If `System.Backup.Local.Enable` is set to `true`, this also enables a daily full backup at 12:00am UTC (fixed in 3.9.1)
* The data streaming connector does not handle NULL values; the connector may operate properly if a NULL value is submitted. Users should replace NULL with an alternate value, such as empty string "" for STRING data, 0 for INT data, etc.  (NULL is not a valid value for the TigerGraph graph data store.)
* Automatic message removal is an Alpha feature of the Kafka connector.  It has several xref:tigergraph-server:data-loading:data-streaming-connector/index.adoc#_known_issues[known issues].
* The `DATETIME` data type is not supported by the `PRINT … TO CSV` statement (fixed in 3.9.1).
* The LDAP keyword `memberOf` for declaring group hierarchy is case-sensitive.

=== Compatibility Issues
* v3.9.2+
** Betweenness Centrality algorithm: `reverse_edge_type (STRING)` parameter changed to `reverse_edge_type_set (SET<STRING>)`, to be consistent with `edge_type_set` and similar algorithms.
** For vertices with string-type primary IDs, vertices whose ID is an empty string will now be rejected.
** The default mode for the Kafka Connector changed from EOF="false" to EOF="true".
** The default retention time for two monitoring services `Informant.RetentionPeriodDays` and `TS3.RetentionPeriodDays` has reduced from 30 to 7 days.
** The filter for `/informant/metrics/get/cpu-memory` now accepts a list of ServiceDescriptors instead of a single ServiceDescriptor.

* v3.9+:
** Some user-defined functions (UDFs) may no longer be accepted due to xref:security:index.adoc#_udf_file_scanning[increased security screening].
*** UDFs may no longer be called `to_string()`. This is now a built-in GSQL function.
*** UDF names may no longer use the `tg_` prefix. Any user-defined function that began with `tg_` must be renamed or removed in `ExprFunctions.hpp`.


=== Deprecations
* Kubernetes classic  mode (non-operator) is deprecated, as of v3.9.
* The `WRITE_DATA` RBAC privilege is deprecated, as of v3.7.

== Release notes for previous versions
* xref:3.8@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.8]
* xref:3.7@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.7]
* xref:3.6@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.6]
* xref:3.5@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.5]
* xref:3.4@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.4]
* xref:3.3@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.3]
* xref:3.2@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.2]
