= Release Notes
:description: Release notes for TigerGraph {page-component-version}.
:page-aliases: change-log.adoc, release-notes.adoc

TigerGraph Server {page-component-version}.0 was released on June 15th, 2022.

== New Features

Below is a list of new features and improvements:

=== Elasticity
* Added support for provisioning xref:ha:elastic-cluster.adoc[Elastic Read-only (ER) clusters] with different partitions than the primary cluster.
** Note: This feature is currently in the preview stage only available for enterprise TigerGraph Cloud customers.
If you are a paid TigerGraph Cloud enterprise customer and want to set up an ER cluster for your environment, please https://tigergraph.zendesk.com/hc/en-us/[open a support ticket].

=== Manageability
* Introduced TigerGraph xref:kubernetes:k8s-operator/index.adoc[].
TigerGraph Kubernetes Operator allows you to automate operations such as the creation, status checking and deletion of TigerGraph clusters.

=== Security
* Sensitive data such as user credentials in log and configuration files are now encrypted.

=== Ecosystem integration
* Added the ability to stream data in formats such as AVRO and JSON from external Kafka clusters to xref:data-loading:data-streaming-connector.adoc[Data Streaming Connector].

=== Performance
* Improved data loading speed and reliability.
* Improved the speed and reliability of database catalog operations such as vertex and edge definition, schema changes, and query installation

=== Query Language Enhancement
* Reducer function `add()` now accumulates values when loading to a `MAP` attribute.

=== GraphStudio Enhancement
* Added the ability to xref:gui:graphstudio:write-queries.adoc#_graph_data_science_library_queries[one-click install built-in Graph Data Science Library algorithms].
* Added the ability to xref:gui:graphstudio:map-data-to-graph.adoc#_create_a_gcs_data_source[load data from Google Cloud Storage] through GraphStudio UI.



[#_fixed_issues]
== Fixed issues




== Known Issues


== Release notes for previous versions
* xref:3.5@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.5]
* xref:3.4@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.4]
* xref:3.3@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.3]
* xref:3.2@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.2]

== Compatibility with TigerGraph 3.4
* A single `POST-ACCUM` clause can no longer reference more than one vertex alias in Syntax V1.
* `GET /requesttoken` endpoint is dropped.
Please use `POST /requesttoken` to request authentication tokens instead.
** Using request body to store credentials is more secure than using query string.
If you have a create a token request that puts the credentials in the query string, all you need to do is use the `POST` endpoint and move your credentials to the request body. 
* `GET /gsqlserver/gsql/queryinfo` endpoint on port 14240 now returns the query input parameters in the same order as they are in the query instead of an unordered list.
* Deploying TigerGraph in Kubernetes now requires more service account permissions than previous versions.
For details, see Prerequisites section in xref:kubernetes:quickstart-with-gke.adoc[], xref:kubernetes:quickstart-with-aks.adoc[], and xref:kubernetes:quickstart-with-eks.adoc[].

== Compatibility with TigerGraph 3.1

The following changes were made to the built-in roles in TigerGraph's Role-based Access Control

* The built-in role `queryreader` can no longer run queries that include updates to the database.
** To emulate the old `queryreader` role, create a role with all `queryreader` privileges, and also grant the `WRITE_DATA` privilege to the new role.
* The built-in role `admin` can no longer create users
** To emulate the old `admin` role, create a global role with all `admin` privileges, and also grant the `WRITE_USER` privilege to the new role.
* To learn more about role management and the privileges of built-in roles, see:
** xref:user-access:role-management.adoc[]
** xref:reference:list-of-privileges.adoc[]

== Compatibility with TigerGraph 2

Major revisions (e.g., from TigerGraph 2 to TigerGraph 3) are the opportunity to deliver significant improvements. While we make every effort to maintain backward compatibility, in selected cases APIs have changed or deprecated features have been dropped, in order to advance the overall product.

*Data migration*: A tool is available to migrate the data in TigerGraph 2.6 to TigerGraph 3.0. Please contact TigerGraph Support for assistance.

*Query and API compatibility*:

* Some gadmin syntax has changed. Notably. `gadmin set config` is now `gadmin config set`.  Please see xref:gadmin:management-with-gadmin.adoc[Managing with gadmin].
* Some features which were previously deprecated have been dropped. Please see xref:release-notes:v3.0-removal-of-previously-deprecated-features.adoc[V3.0 Removal of Previously Deprecated Features] for a detailed list.

include::v3.0-removal-of-previously-deprecated-features.adoc[]