= Release Notes
:description: Release notes for TigerGraph 3.5.
:page-aliases: change-log.adoc, release-notes.adoc

TigerGraph Server 3.5.0 was released on Feb 8th, 2022.


== Maintenance releases

=== 3.5.3

TigerGraph 3.5.3 was released on May 12th, 2022 and is available on https://tgcloud.io[TigerGraph Cloud].

Issues fixed:

* Fixed security issues that could have allowed users to access local files on the local server file system.
* Fixed a security issue that could have allowed unprivileged users to change their access privileges or configuration settings.

Improvements:

* Enabled configurability for Executor file transfer concurrency.

=== 3.5.2

TigerGraph 3.5.2 was released on April 25th, 2022 and is available on https://tgcloud.io[TigerGraph Cloud].

Issues fixed:

* Fixed an issue that could cause `Tokenbank.so` to be lost after restoring a backup in rare cases.
* Fixed an issue that could cause schema to become empty after cluster shrinking in rare cases.
* Fixed an issue that could cause the Graph Processing Engine (GPE) to crash after getting invalid responses from Zookeeper in rare cases.
* Fixed an issue that could cause the Graph Storage Engine (GSE) to crash during leader election in rare cases.
* Upgraded the dependencies of GUI server, GSQL server, Kafka, Kafka-connect, and Zookeeper to resolve related security issues.
* Fixed an issue that prevented failed `CREATE VERTEX` or `CREATE EDGE` commands from being properly rolled back.
* Fixed an issue that caused errors when a query's path pattern included edge wildcards.
* Fixed an issue that slowed the semantic checker when editing queries written in syntax V2 on GraphStudio.
* Fixed an issue that prevented GPE's memory protection from recognizing when memory usage enters the critical stage.
* Fixed an issue that could prevent vertex upsertions after the Graph Storage Engine (GSE) restarts on a single-partition (including single-node) TigerGraph instance in rare cases.

=== 3.5.1

TigerGraph 3.5.1 was released on March 31st, 2022.

Issues fixed:

* Resolved https://nvd.nist.gov/vuln/detail/CVE-2022-23302[CVE-2022-23302] and https://nvd.nist.gov/vuln/detail/CVE-2022-23305[CVE-2022-23305] by removing JDBCappender and JMSsink classes from ZK and Kafka log4j jar.
* Fixed an issue that caused GraphStudio to issue too many expensive requests if the user stays on the Load Data page.
* Fixed an issue that in rare cases prevented the Graph Processing Engine (GPE) process from restarting after being terminated.
* Fixed an issue that in rare cases caused data upsert operations to cause queries to time out.
* Fixed an issue that impacted upsert performance when upserting data to `STRING COMPRESS` data type.
* Fixed an issue that in rare cases prevented a TigerGraph cluster from recovering from a Kafka failure.
* Resolved SQL injection risks in GraphStudio.
* Added an error message when a query written in syntax V2 uses the xref:gsql-ref:querying:select-statement/index.adoc#_sample_clause[`SAMPLE` clause] of a `SELECT` statement.
`SAMPLE` clauses are currently not supported in syntax V2.
* Fixed an issue that impacted performance when a query writes results to a file.
* Fixed an issue that prevented loading jobs from loading data from other disks in a file system.
* Fixed an issue that in some cases prevented GraphStudio from displaying the entire query if the query is too long.

Improvements:

* Added support for generic vertices in xref:gsql-ref:querying:data-modification-statements.adoc#_insert_into_statement[`INSERT INTO <edge_type>` statements].

'''

The rest of this page provides the 3.5.0 release notes.

== New Features

Below is a list of new features and improvements in TigerGraph 3.5.0:

=== Elasticity
* Added support for provisioning xref:ha:elastic-cluster.adoc[Elastic Read-only (ER) clusters] to provide computation on demand.
** Note: This feature is currently in the preview stage only available for enterprise TigerGraph Cloud customers.
If you are a paid TigerGraph Cloud enterprise customer and want to set up an ER cluster for your environment, please https://tigergraph.zendesk.com/hc/en-us/[open a support ticket].

=== Manageability
* Added support for xref:ha:remove-failed-node.adoc[removing one or more failed nodes] from a cluster.
After removal, users can xref:cluster-resizing:expand-a-cluster.adoc[expand the cluster] back to its original size.
* Added support for backup and restore to xref:kubernetes:index.adoc[TigerGraph deployments on Kubernetes].
* Added xref:reference:configuration-parameters.adoc#_kafkastreamll[`gadmin configuration` parameter] `KafkaStreamLL.MaxPartitionFetchBytes` to adjust Kafka Stream max partition fetch size.

=== Security
* Added xref:user-access:access-control-model.adoc#_access_control_lists[Access Control Lists] to queries for fine-grain access control.
* Added xref:data-loading:kafka-loader/kafka-ssl-sasl.adoc[SSL/SASL support for Kafka loader].
* Masked secrets and user credentials in RESTPP logs.

=== Ecosystem integration
* Introduced the xref:data-loading:data-streaming-connector.adoc[Data Streaming Connector] with Google Cloud Storage data streaming support.

=== Observability
* Improved error messaging when the maximum graph size allowed by license is reached.

=== Reliability
* Added the `gsql-atomic-level` header to the endpoint xref:API:built-in-endpoints.adoc#_upsert_data_to_graph[`POST /graph/\{graph_name}`] to allow users to set atomicity levels in upsert requests.


=== Query Language Enhancement
* Changed default GSQL syntax to syntax V2.
See xref:gsql-ref:querying:syntax-versions.adoc[] for a summary of the differences between V1 and V2.
* Added V2 support for single-hop `UPDATE` and `DELETE` statements.
* Added support for xref:gsql-ref:querying:declaration-and-assignment-statements.adoc#_local_tuple_variable[local tuple variables].
* Added support for multiple `POST-ACCUM` clauses in `SELECT` statements in syntax V1.
* Added 10 methods to xref:gsql-ref:querying:accumulators.adoc#_bitwiseandaccum_bitwiseoraccum[`BitwiseAndAccum` and `BitwiseOrAccum`] and increased their length limit.

=== GraphStudio Enhancement
* Added pagination support to AdminPortal metric charts.

=== Other tools
* Added xref:API:built-in-endpoints.adoc#_install_a_query[`POST /gsql/queries/install` endpoint] to install queries.
* Added xref:API:built-in-endpoints.adoc#_check_query_installation_status[`GET /gsql/queries/install/\{request_id}` endpoint] to check the status of query installation requests.


[#_fixed_issues]
== Fixed issues
* Fixed an issue where the installer did not check `AllowerUser` on all nodes for installation on OEL8.
* Fixed an issue that in rare cases led to GPE crash when the database is empty.
* Fixed an issue that caused large parallel loading to trigger race conditions.
* Fixed an issue that threw out-of-range errors when a 64-bit `BitwiseAccum` flips all bits with its `flip()` method.
* Fixed an issue where `PRINT` statements printed vertex accumulators declared after the `PRINT` statement.
* Improved the error message of the `/requesttoken` endpoint.
* Fixed an issue where in rare cases clusters with over 10 partitions fail to elect a GSE leader.
* Fixed an issue that caused connection refused errors when connecting to a TigerGraph cluster behind a load balancer through a remote GSQL client.
* Fixed an issue that caused the `getAttr()` function of vertices and edges to invalidate a clause even if it doesn't get called.
* Fixed an issue that caused the `edgeAttribute()` method of a vertex to erroneously throw type check errors in syntax V2.
* Fixed an issue in GraphStudio query editor that produced inconsistent indentation when indents are autogenerated.
* Fixed an issue in GraphStudio where some metadata of a graph isn't deleted after the graph is dropped




== Known Issues

=== Applications

* *GraphStudio*
 ** xref:gui:graphstudio:known-issues.adoc[Known Issues for GraphStudio]
 ** The No-Code Data Migration feature is in Alpha release. Your feedback would be appreciated.
 ** The No-Code Visual Query Builder is in Beta release. Your feedback would be appreciated.
* *Admin Portal*
 ** xref:gui:admin-portal:known-issues.adoc[Known Issues for AdminPortal]

=== *GSQL*

* *Multiple (Conjunctive) Path Patterns*:
 ** There are no known functional problems, but the performance has not been optimized. Your feedback would be appreciated.
* *DML type check error in V2 Syntax:*
 ** GSQL will report a wrong type check error for Query block with multiple POST-ACCUM clauses and Delete/Update attribute operation.
* *Turn on GSQL HA manually when upgrading from 3.0.x*
 ** Users who are upgrading from 3.0.X need to manually start GSQL HA service. Please reach out to support for help with the process documented in: https://tigergraph.freshdesk.com/a/solutions/articles/5000865072
* *Stale data visible after Deletes using index*
 ** Queries that use secondary index may still see the vertices being deleted until after the snapshots are fully rebuilt.
* *Concurrent read and write on the same vertex during loading*
 ** Concurrent read and write operations on the same vertex and its connected edges during data loading could cause Graph Processing Engine (GPE) dysfunction in rare cases



== Release notes for previous versions
* xref:3.4@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.4]
* xref:3.3@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.3]
* xref:3.2@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.2]

== Compatibility with TigerGraph 3.4
* A single `POST-ACCUM` clause can no longer reference more than one vertex alias in Syntax V1.
* `GET /requesttoken` endpoint is dropped.
Please use `POST /requesttoken` to request authentication tokens instead.
** Using request body to store credentials is more secure than using query string.
If you have a create a token request that puts the credentials in the query string, all you need to do is use the `POST` endpoint and move your credentials to the request body. 
* `GET /gsqlserver/gsql/queryinfo` endpoint on port 14240 now returns the query input parameters in the same order as they are in the query instead of an unordered list.
* Deploying TigerGraph in Kubernetes now requires more service account permissions than previous versions.
For details, see Prerequisites section in xref:kubernetes:quickstart-with-gke.adoc[], xref:kubernetes:quickstart-with-aks.adoc[], and xref:kubernetes:quickstart-with-eks.adoc[].

== Compatibility with TigerGraph 3.1

The following changes were made to the built-in roles in TigerGraph's Role-based Access Control

* The built-in role `queryreader` can no longer run queries that include updates to the database.
** To emulate the old `queryreader` role, create a role with all `queryreader` privileges, and also grant the `WRITE_DATA` privilege to the new role.
* The built-in role `admin` can no longer create users
** To emulate the old `admin` role, create a global role with all `admin` privileges, and also grant the `WRITE_USER` privilege to the new role.
* To learn more about role management and the privileges of built-in roles, see:
** xref:user-access:role-management.adoc[]
** xref:reference:list-of-privileges.adoc[]

== Compatibility with TigerGraph 2

Major revisions (e.g., from TigerGraph 2 to TigerGraph 3) are the opportunity to deliver significant improvements. While we make every effort to maintain backward compatibility, in selected cases APIs have changed or deprecated features have been dropped, in order to advance the overall product.

*Data migration*: A tool is available to migrate the data in TigerGraph 2.6 to TigerGraph 3.0. Please contact TigerGraph Support for assistance.

*Query and API compatibility*:

* Some gadmin syntax has changed. Notably. `gadmin set config` is now `gadmin config set`.  Please see xref:gadmin:management-with-gadmin.adoc[Managing with gadmin].
* Some features which were previously deprecated have been dropped. Please see xref:release-notes:v3.0-removal-of-previously-deprecated-features.adoc[V3.0 Removal of Previously Deprecated Features] for a detailed list.

include::v3.0-removal-of-previously-deprecated-features.adoc[]
