= TigerGraph DB Release Notes
:description: Release notes for TigerGraph {page-component-version}
//:page-aliases: change-log.adoc, release-notes.adoc
:fn-preview: footnote:preview[Features in the preview stage should not be used for production purposes. General Availability (GA) versions of the feature will be available in a later release.]
:pp: {plus}{plus}
:toc:
:toclevels:2

TigerGraph Server 4.1.0 preview version was released on August 28, 2024.

//LTS versions are supported for 24 months from their initial release (X.X.0) and should be the choice for production deployments.

== Key New Features

//text to comment out

== Detailed List of New and Modified Features

=== Backup and Restore Enhancements

* **xref:tigergraph-server:backup-and-restore:point-in-time-restore.adoc[Point in Time Restore]**: 
Users can roll back the database to a moment they select, not only the time of an available backup snapshots.

* **xref:tigergraph-server:backup-and-restore:configurations.adoc#_configure_backup_to_aws_s3_endpoint[Role ARN for Backup to AWS S3 buckets]**: 
Users can use AWS Role ARNs (Amazon Resource Names) for convenient and secure management of backups.

* See also xref:_high_availability_ha_enhancements[]

=== Security Enhancements

[#finer_grain_query_privileges]
* **xref:tigergraph-server:user-access:fine-grained-query-privileges.adoc[Fine-grained Privileges on Queries]**:
gives adminstrators finer control over who may do what actions with which objects:
- Allows privileges to be granted/revoked at the query level.
- Adds new query privileges OWNERSHIP, INSTALL and EXECUTE, and splits  WRITE to CREATE, UPDATE and DROP.

* **xref:tigergraph-server:user-access:jwt-token.adoc#_usage_of_gsql_jwt_token[JWT Authentication]**:
JWT authorization/authentication is more secure than the plaintext tokens used in earlier TigerGraph versions.
Users can generate and use JWT tokens when sending REST requests to the GSQL or REST servers.

* **xref:tigergraph-server:security:password-policy.adoc[Password Complexity and Rotation Rules]**: 
Administrators can specify rules for the complexity of passwords and how long or how many times a password may be used, in order to improve security and help organizations to satisfy compliance requirements.

* **xref:tigergraph-server:troubleshooting:audit-log.adoc[Expanded Audit Log Coverage]**: 
Audit logs now include `gadmin` activity, for more complete audit coverage.

=== High Availability (HA) Enhancements

* **xref:tigergraph-server:data-loading:data-loading-v2.adoc[Data Loading HA (Beta)]**:
If the database is replicated, this data loading mode offers faster loading, reduced disk usage, and HA with automatic failover.
Available for TigerGraph's xref:tigergraph-server:data-loading:manage-data-source.adoc[data streaming connectors] for cloud storage, Kafka, data warehouses, and Spark.

* **xref:tigergraph-server:system-management:change-data-capture/cdc-overview.adoc#_cdc_ha[Change Data Capture (CDC) HA]**:
CDC continues to function as long as at least one replica per partition is online.
Previously, Replica 1 needed to remain operational.

* **Backup HA**:
Backups remain available even if a node fails.
Previously, backups were unavailable if a node failed.

=== Data Streaming/Connector Enhancements

* **xref:gsql-ref:ddl-and-loading:managing-loading-job.adoc#_show_loading_error[Malformed Loading Data Inspector]**:
`SHOW LOADING ERROR` presents a sample of malformed data lines and their error types to an authorized user,
enabling them to quickly locate and diagnose loading problems.

* **xref:tigergraph-server:data-loading:read-to-spark-dataframe.adoc[Stream Data into Spark]**:
Using the Spark data source reader API, users can run TigerGraph queries and stream the output to Spark as DataFrames.
Streaming the output lifts the 2GB query response size limitation for non-streaming output.

* **Notification for Stuck Loader**:
If loading is stuck or acting abnormally, the loader sends an alert message to the console,
including a diagnosis, enabling users to take timely action.

* See also xref:_high_availability_ha_enhancements[]

=== Kubernetes Operator Enhancements

* TigerGraph Operator 1.2.0 introduces several significant new features, including the ability to create services for sidecar containers, support for cluster storage resizing, new lifecycle hooks for TigerGraph CR, and enhanced Multi-AZ cluster resiliency.
+
.TigerGraph K8s Operator 1.2.0 details
[%collapsible]
====
- **https://github.com/tigergraph/ecosys/blob/k8s-operator/1.2.0/k8s/docs/03-deploy/region-awareness-with-pod-topology-spread-constraints.md[Region Awareness with Pod Topology Spread Constraints]**: +
Improve workload distribution and availability by enabling region awareness.

- **https://github.com/tigergraph/ecosys/blob/k8s-operator/1.2.0/k8s/docs/04-manage/expand-storage.md[Automatic Expansion of PVCs for TigerGraph CR]**: +
Simplify storage management with automated Persistent Volume Claim (PVC) resizing.

- **https://github.com/tigergraph/ecosys/blob/k8s-operator/1.2.0/k8s/docs/03-deploy/lifecycle-of-tigergraph.md[New Lifecycle Hooks for TigerGraph CR]**: +
Utilize preDeleteAction and prePauseAction lifecycle hooks for better control and automation during cluster operations.

- **https://github.com/tigergraph/ecosys/blob/k8s-operator/1.2.0/k8s/docs/03-deploy/configure-services-of-sidecar-containers.md[Service Creation for Sidecar Containers]**: +
Easily create services for sidecar containers with TigerGraph CR.

- **https://github.com/tigergraph/ecosys/blob/k8s-operator/1.2.0/k8s/docs/04-manage/debug-mode.md[Enhanced Debugging Mode]**: +
Debug more effectively with the newly introduced debugging mode in the operator.

- **https://github.com/tigergraph/ecosys/blob/k8s-operator/1.2.0/k8s/docs/03-deploy/tigergraph-on-eks.md#install-tigergraph-operator[Customization of MaxConcurrentReconciles for the operator]**: +
Fine tune TigerGraph operator's performance by customizing the maximum number of concurrent reconciles.

====

=== Language Enhancements

////
* **GSQL OpenCypher additions**
- *It is annoying to me as a writer and to readers that these are listed as separate bullet points without a logical reason for the separation. It is actually 5 separate doc tickets. Working incrementally without a top-down view leads to poor results.*
- https://graphsql.atlassian.net/browse/DOC-2249 to *WRITE*

- Adds elementId() function to GSQL and GSQL OpenCypher.
- Adds head, last, size, tail, and reversedlist functions to GSQL and GSQL OpenCypher.
- Adds StartNode and EndNode functions to GSQL for use in GSQL OpenCypher.
- Introduces Range() and Split() functions to GSQL and OpenCypher.
- Introduces stDevP() function for population standard deviation in GSQL and OpenCypher.
////

* **xref:API:gsql-rest/gsql-rest-intro.adoc[REST APIs for Programmatic Use]**:
Introduces a more complete and standard set of REST APIs:
- provides coverage for database commands previously only available as GSQL commands.
- allows developers and AI to more easily control and use TigerGraph programmatically.

////
* **xref:gsql-ref:querying:accumulators.adoc#_edge_attached_accumulators[Edge Accumulators in Multi-hop Queries]**
- Edge accumulators can now be using in multi-hop pattern matching queries.
- Query writers can save and retreive intermediate results using edge-based containers, enhancing the capabilities of the GSQL language for comprehensive graph data analysis.
////

== TigerGraph Suite

=== GraphStudio

* **Highlight Connected Edges When Hovering Over a Vertex**: +
to show users the relationships and structure at a glance.
Also available in Insights.

* **Collapsible Sidebar**: +
to let users use their screen space more effiently.

////
* **Implement query_status Endpoint in GUI**

A new query_status endpoint has been added to the GUI for tracking the status of asynchronous query calls. This allows users to monitor the progress and completion of their queries without blocking their workflow.
Users can now manage and track their async queries more effectively, improving the efficiency of their workflow and resource management.
////
* **Mandatory Password Change upon Expiration**: +
A password must be changed when it expires or reaches a time/usage limit, enhancing security protocols.
Not available on TigerGraph Cloud.

* **Customizable Naming of Reverse Edges**: +
enables data modelers to apply more intuitive and domain-specific names.

////
* ** User-Customizable Layout**:
I don't get this. Also applies to Insights.
////

=== TigerGraph Insights

* **Downloadable Query Output**: +
as CSV or JSON

* **"Tree" View Respects Direction of Directed Edges**: +
to depict hierarchical structures and dependencies more meaningfully

* **Support for Variables in Markdown Widget**: +
for more context-aware and interactive dashboard displays

=== AdminPortal

* **Health Check Tool**:
The Health Check Tool in TigerGraph AdminPortal provides administrators with a comprehensive set of checks and diagnostics to ensure the system is running optimally.

* **Fine-grained Query Privileges in RBAC**:
AdminPortal UI for the xref:#finer_grain_query_privileges[fine-grained query privileges] described above.

== Fixed issues
=== Fixed and Improved in 4.1.0

//==== Functionality

////
* Fixed known issue where the attribute name `memberOf` was case-sensitive. It is now case-insensitive (GLE-6660).
* Fixed issue of clarity for error message/log when global `schema_change` failed for adding edge but it's relied on vertex does not exist (GLE-6751).
* Fixed issue where installation was halted due to TigerGraph disks mounted with `noexec` on AppRoot or DataRoot, preventing execution (TP-4929).
* Fixed issue where there was a delay in loading response times due to syntax detection process in GSQL (GLE-6822).
* Fixed issue were there was a GPE failure reported during query execution prompting relocation from `/tmp` to `System.TempRoot` (GLE-5536).
* Fixed issue where incorrect error response occurred when specified graph does not exist (APS-2824).
* Fixed issue where users encountered error `Vertex expansion failed: c.default.post is not a function` during Explore Neighbors operation in Insight (APS-2840).
////

//==== Crashes and Deadlocks
//==== Improvements
//==== Security
//==== Performance

== Known Issues and Limitations

[cols="4", separator=¦ ]
|===
¦ Description ¦ Found In ¦ Workaround ¦ Fixed In

¦When using xref:tigergraph-server:backup-and-restore:database-import-export.adoc[Import All] if a users schema size in the `.zip` file is exceedingly large, the import may fail with an error messages like this:

`Large catalog file key: /1/ReplicaList.json`

¦ 3.2
a¦
* 3.9 and below users need to run the import process manually by executing the GSQL scripts in the `.zip`.
* 3.10.0 and above users should xref:tigergraph-server:backup-and-restore:single-graph-import-export.adoc[import single or smaller batches of multiple graphs].
¦ TBD

a¦ If importing a role, policy, or function that has a different signature or content from the existing one, the one being imported will be skipped and not aborted.

.For example:
* If the original function is: `create function lib1.func2(int param1, float param2, string param3) returns (bool) {}`.
* And the user imports the new function: `create function lib1.func2(int param1) returns (bool) {}`. This second one will be skipped.
¦ 3.10.0
¦ Users need to re-create (delete and create) the imported role, policy, or function manually, and make sure that the importing one meets the requirements set by the existing one.
¦ TBD

a¦ xref:tigergraph-server:user-access:rbac-row-policy/row-policy-overview.adoc[Row Policy (Preview Feature)] does not yet filter or check vertex attribute data in upsert operations.

Such as,

* A query with insert statements.
* A file or Kafka loading job.
* A DDL loading request.
* Or a standard upsert request.
¦ 3.10.0
¦ Users should restrict the access of creating/running queries and loading jobs for roles related to row policy.
¦ TBD

¦ In file INPUT and OUTPUT policy, if there exists 2 path (`path1` and `path2`) in the configured policy list and `path1` is parent path of `path2`, then `path1` may not be effective.
¦ 3.2 and 3.10.0
¦ Users should avoid using paths if they are nested.

For example, avoid this scenario, path2 = `"/tmp/more"` and path1= `"/tmp"`.
¦ 3.10.1

¦ It has been observed that an issue happens when RESTPP will send a request to all gpes, and if one is down, the request sent to it will `timeout`.
Including the `consistency_check` request will also mark as `timeout`.
¦ 3.10.0
a¦
. Run `/rebuildnow` to rebuild all the segments.
+
[NOTE]
====
Running `/rebuildnow` when one gpe is down will result in the request timeout. This does not mean the request failed, instead only the currently running GPE will do the rebuild, and any rebuild requests sent to the down GPEs will result in a timeout.
====
. Run `/data_consistency_check?realtime=false` to check the consistency.
¦ TBD

¦ While running `export graph` if the disk space is not enough, or the data has not been detected, the export data will get stuck loading.
¦ 3.10.0
¦ Restart all services in Admin Portal or the backend.
¦ TBD

¦ `[tg_]ExprFunction.hpp` will be automatically merged while importing single graphs. In some cases, query compilation may fail.
¦ 3.10.0
¦ See xref:tigergraph-server:backup-and-restore:single-graph-import-export.adoc#_known_issues_and_workarounds[Known Issues and Workarounds]
¦ TBD

¦ Upgrading from a previous version of TigerGraph has known issues.
¦ 3.10.0
¦ See section xref:tigergraph-server:installation:upgrade.adoc#_known_issues_and_workarounds[Known Issues and Workarounds] for more details.
¦ TBD

¦ Input Policy feature has known limitations.
¦ 3.10.0
¦ See section xref:tigergraph-server:security:gsql-file-input-policy.adoc#_limitations[Input Policy Limitations] for more details.
¦ TBD

¦ Change Data Capture (CDC) feature has known limitations.
¦ 3.10.0
¦ See section xref:tigergraph-server:system-management:change-data-capture/cdc-overview.adoc#_cdc_limitations[CDC Limitations] for more details.
¦ TBD

¦ If the `FROM` clause pattern is a multi-hop and the `ACCUM` clause reads both primitive and container type attributes or accumulators of a vertex, the internal query rewriting logic may generate an invalid rewritten output.
¦ 3.9.3
¦ This results in the error message: `It is not allowed to mix primitive types and accumulator types in GroupByAccum`.
¦ TBD

¦ Users may see a high CPU usage caused by Kafka prefetching when there is no query or posting request.
¦ 3.9.3
¦ TBD
¦ TBD

¦ GSQL query compiler may report a false error for a valid query using a vertex set variable (e.g. `Ent` in `reverse_traversal_syntax_err`) to specify the midpoint or target vertex of a path in a FROM clause pattern.
¦ TBD
¦ TBD
¦ TBD

¦ If a loading job is expected to load from a large batch of files or Kafka queues (e.g. more than 500), the job’s status may not be updated for an extended period of time.
¦ 3.9.3
¦ In this case, users should check the loader log file as an additional reference for loading status.
¦ TBD

¦ When a GPE/GSE is turned off right after initiating a loading job, the loading job is terminated internally. However, users may still observe the loading job as running on their end.
¦ 3.9.3
¦ Please see xref:gsql-ref:ddl-and-loading:running-a-loading-job.adoc[Troubleshooting Loading Job Delays] for additional details.
¦ TBD

¦ For v3.9.1 and v3.9.2 when inserting a new edge in `GPR` and `INTERPRET` mode, the GPE will print out a warning message because a discriminator string is not set for new-inserted edges. Creating an inconsistent problem in delta message for GPR and `INTERPRET` mode.
¦ 3.9.2
¦ Please see xref:gsql-ref:ddl-and-loading:running-a-loading-job.adoc[Troubleshooting Loading Job Delays] for additional details.
¦ 3.9.3

¦ GSQL `EXPORT GRAPH` may fail and cause a GPE to crash when UDT type has a fixed STRING size.
¦ TBD
¦ TBD
¦ TBD

¦ After a global loading job is running for a while a fail can be encountered when getting the loading status due to `KAFKASTRM-LL` not being online, when actually the status is online.
Then the global loading process will exit and fail the local job after timeout while waiting the global loading job to finish.
¦ TBD
¦ TBD
¦ TBD

¦ When the memory usage approaches 100%, the system may stall because the process to elect a new GSE leader did not complete correctly.
¦ TBD
¦ This lockup can be cleared by restarting the GSE.
¦ TBD

¦ If the CPU and memory utilization remain high for an extended period during a schema change on a cluster, a GSE follower could crash, if it is requested to insert data belonging to the new schema before it has finished handling the schema update.
¦ TBD
¦ TBD
¦ TBD

¦ When available memory becomes very low in a cluster and there are a large number of vertex deletions to process, some remote servers might have difficulty receiving the metadata needed to be aware of all the deletions across the full cluster. The mismatched metadata will cause the GPE to go down.
¦ TBD
¦ TBD
¦ TBD

¦ Subqueries with SET<VERTEX> parameters cannot be run in Distributed or Interpreted mode.
¦ TBD
¦ (xref:3.9@gsql-ref:querying:operators-and-expressions.adoc#_subquery_limitations[Limited Distributed model support] is added in 3.9.2.)
¦ TBD

¦ Upgrading a cluster with 10 or more nodes to v3.9.0 requires a patch.
¦ 3.9
¦ Please contact TigerGraph Support if you have a cluster this large. Clusters with nine or fewer nodes do not require the patch.
¦ 3.9.1

¦ Downsizing a cluster to have fewer nodes requires a patch.
¦ 3.9.0
¦ Please contact TigerGraph Support.
¦ TBD

¦ During peak system load, loading jobs may sometimes display an inaccurate loading status.
¦ 3.9.0
¦ This issue can be remediated by continuing to run `SHOW LOADING STATUS` periodically to display the up-to-date status.
¦ TBD

¦ When managing many loading jobs, pausing a data loading job may result in longer-than-usual response time.
¦ TBD
¦ TBD
¦ TBD

¦ Schema change jobs may fail if the server is experiencing a heavy workload.
¦ TBD
¦ To remedy this, avoid applying schema changes during peak load times.
¦ TBD

¦ User-defined Types (UDT) do not work if exceeding string size limit.
¦ TBD
¦ Avoid using UDT for variable length strings that cannot be limited by size.
¦ TBD

¦ Unable to handle the tab character `\t` properly in AVRO or Parquet file loading. It will be loaded as `\\t`.
¦ TBD
¦ TBD
¦ TBD

¦ If `System.Backup.Local.Enable` is set to `true`, this also enables a daily full backup at 12:00am UTC.
¦ 3.9.0
¦ TBD
¦ 3.9.1

¦ The data streaming connector does not handle NULL values; the connector may operate properly if a NULL value is submitted.
¦ TBD
¦ Users should replace NULL with an alternate value, such as empty string "" for STRING data, 0 for INT data, etc.  (NULL is not a valid value for the TigerGraph graph data store.)
¦ TBD

¦ Automatic message removal is an Alpha feature of the Kafka connector. It has several xref:3.9@tigergraph-server:data-loading:load-from-cloud.adoc#_known_issues_with_loading[known issues].
¦ TBD
¦ TBD
¦ TBD

¦ The `DATETIME` data type is not supported by the `PRINT … TO CSV` statement.
¦ 3.9.0
¦ TBD
¦ 3.9.1

¦ The LDAP keyword `memberOf` for declaring group hierarchy is case-sensitive.
¦ 3.9
¦ Check the case of the keywords for `memberOf`. This has been fixed in versions 3.10.1 and above.
¦ 3.10.1

|===

=== Compatibility Issues

[cols="2", separator=¦ ]
|===
¦ Description ¦ Version Introduced

¦ Users could encounter file input/output policy violations when upgrading a TigerGraph version.
See xref:tigergraph-server:security:gsql-file-input-policy.adoc#_backward_compatibility[Input policy backward compatibility.]
¦ v3.10.0

¦ When a PRINT argument is an expression, the output uses the expression as the key (label) for that output value.
To better support Antlr processing, PRINT now removes any spaces from that key. For example, `count(DISTINCT @@ids)` becomes `count(DISTINCT@@ids)`.
¦ v3.9.3+

¦ Betweenness Centrality algorithm: `reverse_edge_type (STRING)` parameter changed to `reverse_edge_type_set (SET<STRING>)`, to be consistent with `edge_type_set` and similar algorithms.
¦ v3.9.2+

¦ For vertices with string-type primary IDs, vertices whose ID is an empty string will now be rejected.
¦ v3.9.2+

¦ The default mode for the Kafka Connector changed from EOF="false" to EOF="true".
¦ v3.9.2+

¦ The default retention time for two monitoring services `Informant.RetentionPeriodDays` and `TS3.RetentionPeriodDays` has reduced from 30 to 7 days.
¦ v3.9.2+

¦ The filter for `/informant/metrics/get/cpu-memory` now accepts a list of ServiceDescriptors instead of a single ServiceDescriptor.
¦ v3.9.2+

a¦ Some user-defined functions (UDFs) may no longer be accepted due to xref:security:index.adoc#_udf_file_scanning[increased security screening].

* UDFs may no longer be called `to_string()`. This is now a built-in GSQL function.
* UDF names may no longer use the `tg_` prefix. Any user-defined function that began with `tg_` must be renamed or removed in `ExprFunctions.hpp`.
¦ v3.9+
|===

=== Deprecations

[cols="3", separator=¦ ]
|===
¦ Description ¦ Deprecated ¦ Removed

¦ The use of plaintext tokens in xref:tigergraph-server:API:authentication.adoc[authentication] is deprecated.
Use xref:tigergraph-server:user-access:jwt-token.adoc[] instead.
¦ 3.10.0
¦ TBD


¦ The command `gbar` is removed and is no longer available.
However, if you are using a version of TigerGraph before 3.10.0 you can still use `gbar` to xref:tigergraph-server:backup-and-restore:gbar-legacy.adoc[create a backup with gbar] of the primary cluster.
See also xref:tigergraph-server:backup-and-restore:gbar-legacy.adoc[Backup and Restore with gbar] on how to create a backup.

¦ 3.7
¦ 3.10.0

¦ xref:tigergraph-server:user-access:vlac.adoc[Vertex-level Access Control (VLAC)] and xref:gsql-ref:querying:func/vertex-methods.adoc#_vlac_vertex_alias_methods_deprecated[VLAC Methods] are now deprecated and will no longer be supported.
¦ 3.10.0
¦ 4.0

¦ xref:tigergraph-server:data-loading:spark-connection-via-jdbc-driver.adoc[Spark Connection via JDBC Driver] is now deprecated and will no longer be supported.
¦ 3.10.0 
¦ TBD

¦ `Build Graph Patterns` is deprecated and will not be updated or supported and instead
we are focusing on xref:insights:widgets:index.adoc[Insights] as the tool of choice for building visual queries.
¦ v3.9.3
¦ TBD

¦ Kubernetes classic  mode (non-operator) is deprecated.
¦ v3.9
¦ TBD

¦ The `WRITE_DATA` RBAC privilege is deprecated.
¦ v3.7
¦ TBD
|===

== Release notes for previous versions
* xref:3.10@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.10]
* xref:3.9@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.9]
* xref:3.8@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.8]
* xref:3.7@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.7]
* xref:3.6@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.6]
* xref:3.5@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.5]
* xref:3.4@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.4]
* xref:3.3@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.3]
* xref:3.2@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.2]
