= TigerGraph DB Release Notes
:description: Release notes for TigerGraph {page-component-version}
//:page-aliases: change-log.adoc, release-notes.adoc
:fn-preview: footnote:preview[Features in the preview stage should not be used for production purposes. General Availability (GA) versions of the feature will be available in a later release.]
:pp: {plus}{plus}
:toc:
:to

TigerGraph Server 4.2.0 Preview was released on April XX, 2025.

TigerGraph Server 4.2.0 Alpha was released on March 4, 2025.

[NOTE]
====
TigerGraph 4.2's feature set is an enhancement of what was available in 4.1.2.
Therefore, features that were  in 4.1.2 are not considered New Features.
====

== Key New Features

* *xref:4.2@gsql-ref:vector:index.adoc[Hybrid Vector Search]*:
Scalable storage and similarity search for vector attributes associated with vertices.

** New `VECTOR` attribute data type with real-time updates
** Fast approximate nearest neighborhood (ANN), with automatic indexing, incremental indexing
** hybrid graph {plus} vector search in GSQL

* *xref:4.2@tigergraph-server:backup-and-restore:incremental-backup.adoc[Incremental Backup]* which efficiently backs up only what has changed since the last backup/restore event.

* [TBD] *Rolling Upgrades of maintenance versions* for HA clusters (Preview).

* *xref:4.2@tigergraph-server:intro:comparison-of-editions.adoc[Community Edition of TigerGraph Database]*:

** Up to 200GB graph data + 100GB vector data, single server only
** Some enterprise features not included. Community support only
** See the full xref:intro:comparison-of-editions.adoc[comparison of editions].

== Detailed List of New and Modified Features

=== System Management Enhancements

* *xref:4.2@tigergraph-server:backup-and-restore:incremental-backup.adoc[Incremental Backup]* which efficiently backs up only what has changed since the last backup/restore event.

* [TBD] *Rolling Upgrades of maintenance versions* for HA clusters (Preview).

* *xref:4.2@tigergraph-server:backup-and-restore:restore-backup-same.adoc#_options_for_restore[Restore option `--keepusers`]* to keep the database users in the current database, not the ones from the backup file.

* *Backup to xref:4.2@tigergraph-server:backup-and-restore:configurations.adoc#_backup_to_abs_azure_blob_storage[Azure] and xref:4.2@tigergraph-server:backup-and-restore:configurations.adoc#_backup_to_gcs_google_cloud_storage[GCP] cloud storage*, analogous to  existing support for backup to AWS S3.

* [TBD] *More graceful xref:system-management:management-commands.adoc#_gadmin_stop[user-initiated shutdown]* of RESTPP and GPE services.

* [TBD] *Schema Change options* `-force` and `warn` to specify the behavior when loading jobs run during a schema change.

=== Security and Access Control Enhancements

* *xref:4.2@tigergraph-server:user-access:jwt-token.adoc#_user_guide_overview[
JWT authentication] for all REST endpoints*, including GSQL endpoints.

* *New xref:4.2@tigergraph-server:user-access:access-control-model.adoc#_built_in_roles[built-in role]: globalobserver*, used in Savanna, for minimal privileges: `READ_SCHEMA` and `READ_LOADINGJOB`.
* *Two new xref:4.2@tigergraph-server:user-access:rbac-row-policy/row-policy-privileges-table.adoc[access privileges]: READ_LOG and APP_ACCESS_LOG* to grant read-only access to log files. `APP_ACCESS_LOG` is specifically designed for xref:4.2@gui:admin-portal:monitoring/log-viewer.adoc#_privilges[
 access from GraphStudio or Savanna].

=== Integration Enhancements

* *xref:4.2@gsql-ref:querying:data-types.adoc#_s3_object[Writing query output to an S3 object]* can now be configured at the user session level instead at the system administration level, for better alignment of roles and privileges.

* Updated Kafka from 2.5.1 to 3.6.2. Updated Zookeeper from 3.6.3 to 3.8.4.

=== API Enhancements

* *New endpoints to xref:4.2@tigergraph-server:API:gsql-endpoints.adoc#_get_schema_information_from_a_snowflake_data_source[fetch schema information and sample data from Snowflake]*.

* Added a **REST endpoint to xref:4.2@tigergraph-server:API:gsql-endpoints.adoc#_delete_udt_files[delete user-defined function files]**.

* The *Interpret Query endpoint `POST /gsql/v1/queries/interpret`* can now be used with queries that have a xref:4.2@gsql-ref:querying:query-operations.adoc#_complex_type_parameter_passing[datetype parameter].

* The *Edge Upsert endpoint* now supports xref:4.2@tigergraph-server:API:upsert-rest.adoc#_upserting_multi_edges_with_discriminators[upserting the multiple edges of a discriminated edge] in a single API request.

=== Query Language Enhancements

* Multiple enhancements to *Syntax V3*, which combines GSQL + OpenCypher + GQL Pattern Matching:
** [TBD] *GQL and OpenCypher standard path pattern syntax* support, in GSQL syntax
** *Run ad hoc OpenCypher queries and single GSQL SELECT blocks directly*  (xref:4.2@gsql-ref:querying:query-modes.adoc[non-procedural interpreted queries])
** *xref:4.2@gsql-ref:querying:operators-and-expressions.adoc#_comparison_operators_and_conditions[comparison operators `=` and `<>`]*  as alternatives to `==` and `!=` in WHERE conditions.
** *link:https://github.com/tigergraph/ecosys/blob/master/tutorials/Cypher.md#optional-match[OPTIONAL MATCH], COALESCE, and IS [NOT] NULL* (OpenCypher)
** *xref:4.2@gsql-ref:openCypher-in-gsql:index.adoc#_opencypher_features_in_gsql[type() and labels() functions]* (OpenCypher)

* [TBD] *Map and List query parameter types* are now supported.

* *LIKE: xref:4.2@gsql-ref:querying:operators-and-expressions.adoc#_like[<string1> LIKE <string pattern>]* can be used anywhere a condition is allowed, and <string pattern> can include functions.

* *xref:4.2@gsql-ref:querying:operators-and-expressions.adoc#_case_expressions[Simple CASE expressions and Searched CASE expressions]*

* *Bitwise Accumulators*: official support for xref:4.2@gsql-ref:querying:accumulators.adoc#_bitwise_comparison_and_logic_operators[comparison and bitwise logic operators].

* *xref:4.2@gsql-ref:querying:func/query-user-defined-functions.adoc#_use_github_to_store_udfs[Configuation parameter `GSQL.Github.Enabled`]* to enable retrieving UDFs from a Github repository.

* [TBD] *Query Profiler* to analyze query execution and performance.

=== Loading Enhancemnts

* *xref:4.2@gsql-ref:ddl-and-loading:creating-a-loading-job.adoc#_using_clause[Multi-character separators between data fields]* in loading jobs.

* [TBD] *Spark Connector support for OAuth2 authentication*.

* [TBD] *Introduced `DISABLED` Loading Job status* for jobs which have a schema conflict as a result of a Schema Change.

=== Performance Improvements

* [TBD] **Query Planned Caching**, to speed up the run time of repeated queries.

=== GraphStudio, Admin Portal, and Insights

* See the xref:4.2@insights:release-notes:index.adoc[release notes for Insights 4.2].

---

== Fixed issues

=== Fixed and Improved in 4.2.0

==== Functionality

* Fixed issue where the loading job status was incorrectly cleaned up in advance due to an inaccurate loading job counter (TP-4741).
* Fixed issue where the loader would fail silently, and now it reports an error directly if the loader fails to start (TP-6420).
* Fixed issue where loading an empty file triggered a failure loop (TP-6530).
* Added the 'graph' field to CDC messages generated by the TigerGraph CDC service (CORE-4147).
* Fixed issue with audit error codes being logged when a CDC message fails to deliver to external Kafka (CORE-4249).
* Fixed critical disk issue caused by the rebuilder getting stuck in a partitioned cluster after dropping vertex or edge attributes (CORE-4303).
* Fixed issue where CDC EDGE messages with "UNKNOWN" ID were not removed when a query deleted a vertex and edge simultaneously (CORE-4457).
* Fixed issue where the primary ID was missing when inserting a vertex implicitly from loading an edge in a single-partition cluster and the target vertex used "primary_id_as_attribute=true" (GLE-7562).
* Fixed issue with running the TigerGraph command `gcollect` on Kubernetes (TP-6353).
* Added support for debug mode when a pod restart fails due to a PostStartHookError (TP-7228).
* Added namespace as a suffix of the HostName in HostList on Kubernetes (TP-6214).
* Fixed query compilation errors when iterating over `FOREACH` to retrieve an accum type attribute with the `-single` or `distributed` keyword; ensured operations between two different `GroupByAccums` hold the same data types and field names (GLE-8507).
* Fixed issue with double quotes in literal strings during the creation of a loading job (GLE-8630).
* Fixed the inability to fetch dynamic file output policy during query execution (GLE-4847).
* Fixed issue where sensitive information was not removed from the browser localStorage, ensuring better security (APPS-1066)
* Fixed a query installation failure for single-node queries that initialize vertex set variables in conditional branches, such as `if-else` or `case-when` statements (GLE-7369).

==== Improvements

* Improved performance of GSQL queries containing DELETE statements intended for deleting all vertices of a given type (GLE-8328).
* Corrected the logic for the SelectVertex() function so it throws an error if the filePath is not an absolute path.

=== Compatibility Issues

[cols="2", separator=¦ ]
|===
¦ Description ¦ Version Introduced

¦To apply a xref:security:gsql-file-input-policy.adoc[File Input Policy] or xref:security:file-output-policy.adoc[File Output Policy] change, both `gsql` and `restpp` servers much be restarted: `gadmin restart gsql restpp -y`
¦v4.2.0

¦The `--incremental` option for backup performs a true incremental backup instead of a differential backup.
¦v4.2.0

¦The 'graph' field is now included in CDC messages generated by the TigerGraph CDC service.
¦v4.2.0

¦In xref:4.2@tigergraph-server:system-management:change-data-capture/cdc-message-example.adoc#_message_examples[CDC messages], the format of *tuple values* has changed.
¦v4.2.0

¦In xref:4.1@tigergraph-server:system-management:change-data-capture/cdc-message-example.adoc#_message_examples[CDC messages], the format of *map values* has changed.
¦v4.1.1

¦A full export package now includes access policies and template queries.
¦v4.1.0

¦ Users could encounter file input/output policy violations when upgrading a TigerGraph version.
See xref:{page-component-version}@tigergraph-server:security:gsql-file-input-policy.adoc#_backward_compatibility[Input policy backward compatibility.]
¦ v3.10.0

¦ When a PRINT argument is an expression, the output uses the expression as the key (label) for that output value.
To better support Antlr processing, PRINT now removes any spaces from that key. For example, `count(DISTINCT @@ids)` becomes `count(DISTINCT@@ids)`.
¦ v3.9.3+

¦ Betweenness Centrality algorithm: `reverse_edge_type (STRING)` parameter changed to `reverse_edge_type_set (SET<STRING>)`, to be consistent with `edge_type_set` and similar algorithms.
¦ v3.9.2+

¦ For vertices with string-type primary IDs, vertices whose ID is an empty string will now be rejected.
¦ v3.9.2+

¦ The default mode for the Kafka Connector changed from EOF="false" to EOF="true".
¦ v3.9.2+

¦ The default retention time for two monitoring services `Informant.RetentionPeriodDays` and `TS3.RetentionPeriodDays` has reduced from 30 to 7 days.
¦ v3.9.2+

¦ The filter for `/informant/metrics/get/cpu-memory` now accepts a list of ServiceDescriptors instead of a single ServiceDescriptor.
¦ v3.9.2+

a¦ Some user-defined functions (UDFs) may no longer be accepted due to xref:{page-component-version}@tigergraph-server:security:index.adoc#_udf_file_scanning[increased security screening].

* UDFs may no longer be called `to_string()`. This is now a built-in GSQL function.
* UDF names may no longer use the `tg_` prefix. Any user-defined function that began with `tg_` must be renamed or removed in `ExprFunctions.hpp`.
¦ v3.9+
|===

=== Deprecations

[cols="3", separator=¦, heading ]
|===
¦ Description ¦ Deprecated ¦ Removed

¦ The `--meta` option for backup is no longer needed because metadata is now included automatically with backup files.
¦ 3.9.2 ¦ 4.2.0

¦ The format for tuple structures in CDC messages will change in a future version. The future format is likely to be similar to the
xref:4.1@system-management:change-data-capture/cdc-message-example.adoc#_cdc_message_with_type_edge[new format for maps].
¦ 4.1.1
¦ TBD (possibly 4.2)

|===

== Release notes for previous versions

* xref:4.1@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 4.1]
* xref:3.11@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.11]
* xref:3.10@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.10]
* xref:3.9@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.9]
* xref:3.6@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.6]
