= TigerGraph DB Release Notes
:description: Release notes for TigerGraph {page-component-version}
//:page-aliases: change-log.adoc, release-notes.adoc
:fn-preview: footnote:preview[Features in the preview stage should not be used for production purposes. General Availability (GA) versions of the feature will be available in a later release.]
:pp: {plus}{plus}
:toc:
:to

TigerGraph Server 4.2.0 Preview was released on April XX, 2025.

TigerGraph Server 4.2.0 Alpha was released on March 4, 2025.

[NOTE]
====
TigerGraph 4.2's feature set is an enhancement of what was available in 4.1.2.
Therefore, features that were  in 4.1.2 are not considered New Features.
====

== Key New Features

** *xref:4.2@gsql-ref:vector:index.adoc[Hybrid Vector Search]*:
Storage of and similarity search for vector attributes associated with vertices.

* New `VECTOR` attribute data type with real-time updates
* Fast approximate nearest neighborhood (ANN), with automatic indexing, incremental indexing
* hybrid graph {plus} vector search in GSQL

** *xref:tigergraph-server:intro:comparison-of-editions.adoc[Community Edition of TigerGraph Database]*:

* up to 200GB graph data + 100GB vector data, single server only
* some enterprise features are not included
* community support only
+
See a full xref:intro:comparison-of-editions.adoc[comparison of editions].

== Detailed List of New and Modified Features

=== System Management Enhancements

* **Introduced xref:4.2@tigergraph-server:backup-and-restore:incremental-backup.adoc[Incremental Backup]** which efficiently backs up only what has changed since the last backup/restore event.
* **Added xref:4.2@tigergraph-server:backup-and-restore:restore-backup-same.adoc#_options_for_restore[Restore option `--keepusers`]** to keep the database users in the current database, not the ones from the backup file.

=== Security and Access Control Enhancements

* **All REST endpoints now accept xref:4.2@tigergraph-server:user-access:jwt-token.adoc#_user_guide_overview[
JWT tokens for authentication]**, include GSQL endpoints.

* Added two **new xref:user-access:rbac-row-policy/row-policy-privileges-table.adoc[access privileges]: READ_LOG and APP_ACCESS_LOG**.
Both grant read-only access to log files; `APP_ACCESS_LOG` is specifically designed for xref:4.2@gui:admin-portal:monitoring/log-viewer.adoc#_privilges[
 access from GraphStudio or Savanna].

=== Performance Improvements

* [TBD] Introduced **Query Planned Caching**, to speed up the run time for queries which are run multiple times.


=== Language Enhancements

* **xref:4.2@gsql-ref:querying:data-types.adoc#_s3_object[Writing query output to an S3 object]** can now be configured at the user session level instead at the system administration level, for better alignment of roles and privileges.
* The **Interpret Query endpoint `POST /gsql/v1/queries/interpret`** can now be used with queries that have a xref:4.2@gsql-ref:querying:query-operations.adoc#_complex_type_parameter_passing[datetype parameter].
* Added xref:4.2@gsql-ref:querying:func/query-user-defined-functions.adoc#_use_github_to_store_udfs[configuation parameter `GSQL.Github.Enabled`] to **enable retrieving UDFs from a Github repository**.

== Fixed issues

TBA


=== Compatibility Issues

[cols="2", separator=¦ ]
|===
¦ Description ¦ Version Introduced

¦The `--incremental` option for backup performs a true incremental backup instead of a differential backup.
¦v4.2.0

¦In xref:4.2@tigergraph-server:system-management:change-data-capture/cdc-message-example.adoc#_message_examples[CDC messages], the format of tuple values has changed.
¦v4.2.0

¦In xref:4.1@tigergraph-server:system-management:change-data-capture/cdc-message-example.adoc#_message_examples[CDC messages], the format of map values has changed.
¦v4.1.1

¦A full export package now includes access policies and template queries.
¦v4.1.0

¦ Users could encounter file input/output policy violations when upgrading a TigerGraph version.
See xref:{page-component-version}@tigergraph-server:security:gsql-file-input-policy.adoc#_backward_compatibility[Input policy backward compatibility.]
¦ v3.10.0

¦ When a PRINT argument is an expression, the output uses the expression as the key (label) for that output value.
To better support Antlr processing, PRINT now removes any spaces from that key. For example, `count(DISTINCT @@ids)` becomes `count(DISTINCT@@ids)`.
¦ v3.9.3+

¦ Betweenness Centrality algorithm: `reverse_edge_type (STRING)` parameter changed to `reverse_edge_type_set (SET<STRING>)`, to be consistent with `edge_type_set` and similar algorithms.
¦ v3.9.2+

¦ For vertices with string-type primary IDs, vertices whose ID is an empty string will now be rejected.
¦ v3.9.2+

¦ The default mode for the Kafka Connector changed from EOF="false" to EOF="true".
¦ v3.9.2+

¦ The default retention time for two monitoring services `Informant.RetentionPeriodDays` and `TS3.RetentionPeriodDays` has reduced from 30 to 7 days.
¦ v3.9.2+

¦ The filter for `/informant/metrics/get/cpu-memory` now accepts a list of ServiceDescriptors instead of a single ServiceDescriptor.
¦ v3.9.2+

a¦ Some user-defined functions (UDFs) may no longer be accepted due to xref:{page-component-version}@tigergraph-server:security:index.adoc#_udf_file_scanning[increased security screening].

* UDFs may no longer be called `to_string()`. This is now a built-in GSQL function.
* UDF names may no longer use the `tg_` prefix. Any user-defined function that began with `tg_` must be renamed or removed in `ExprFunctions.hpp`.
¦ v3.9+
|===

=== Deprecations

[cols="3", separator=¦, heading ]
|===
¦ Description ¦ Deprecated ¦ Removed

¦ The `--meta` option for backup is no longer needed because metadata is now included automatically with backup files.
¦ 3.9.2 ¦ 4.2.0

¦ The format for tuple structures in CDC messages will change in a future version. The future format is likely to be similar to the
xref:4.1@system-management:change-data-capture/cdc-message-example.adoc#_cdc_message_with_type_edge[new format for maps].
¦ 4.1.1
¦ TBD (possibly 4.2)

|===

== Release notes for previous versions

* xref:4.1@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 4.1]
* xref:3.11@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.11]
* xref:3.10@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.10]
* xref:3.9@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.9]
* xref:3.6@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.6]
