= Release Notes
:description: Release notes for TigerGraph {page-component-version}.
:page-aliases: change-log.adoc, release-notes.adoc
:fn-preview: footnote:preview[Features in the preview stage should not be used for production purposes. General Availability (GA) versions of the feature will be available in a later release.]

TigerGraph Server {page-component-version}.0 was released on Aug 31st, 2022.

== New Features

The following is a list of new features and improvements:

=== Developer tools
* Introduced xref:insights:intro:index.adoc[TigerGraph Insights], a no-code visual graph analyzer that makes building data analytics dashboards intuitive.
* Introduced xref:gsql-shell:web.adoc[GSQL Shell], a web-based version of the GSQL client that allows you to run GSQL commands from your browser.
* Introduced xref:master@home:ROOT:index.adoc#_tigergraph_suite[TigerGraph Suite], a family of applications including GraphStudio, Admin Portal, TigerGraph Insights, GSQL Shell, and GraphQL Service to empower your graph journey.

=== Elasticity
* Added the ability to xref:ha:set-up-elastic-cluster.adoc[launch on-demand elastic clusters for on-prem instances (Preview)].
* Added the ability to xref:kubernetes:expansion.adoc[expand], xref:kubernetes:shrinking.adoc[shrink] and xref:kubernetes:upgrade.adoc[upgrade] a TigerGraph instance running in a Kubernetes cluster.

=== Manageability
* Improved the stability and performance of backup and restore, and added a xref:backup-and-restore:index.adoc[new API for backing up and restoring database clusters].
** The xref:backup-and-restore:gbar-legacy.adoc[legacy Graph Backup and Restore(GBAR)] tool remains available.
* Added Debian 10 & 11 to the xref:installation:hw-and-sw-requirements.adoc#_certified_operating_systems[list of supported operating systems].


=== Security
* Enhanced the xref:user-access:access-control-model.adoc#_role_based_access_control[role-based access control] system to allow data CRUD privileges to be granted at the type and attribute level (Preview).
* Added the ability to enable a xref:security:password-policy.adoc[password policy] to mandate the minimal complexity of passwords.
* TigerGraph Server download packages are now xref:security:index.adoc#_pgp_key[signed with our PGP key].

=== Ecosystem integration
* Added the ability to xref:data-loading:data-streaming-connector/azure-blob.adoc[stream data from Azure Blob Storage] to xref:data-loading:data-streaming-connector/index.adoc[Data Streaming Connector].
* Added the ability to xref:data-loading:data-streaming-connector/aws-s3.adoc[stream data from ]for all supported sources with xref:data-loading:data-streaming-connector/index.adoc[Data Streaming Connector].
* Deleting a Data Streaming Connector now deletes the data in the topics created by the connector.

=== Performance
* Introduced the cost-based query optimizer (Preview), which has the potential to significantly reduce query execution time.

=== Observability


=== Data API service


=== Query Language Enhancement
* Token functions for `WHERE` clause can now also be used for attribute expressions.



[#_fixed_issues]
== Fixed issues
* Fixed a number of security vulnerabilities from package dependencies.
* Improved error messaging when a query uses `TYPEDEF TUPLE` with an unsupported data type.
* Fixed an issue where unauthorized users could access certain local files on the server through a REST endpoint.
* Fixed an issue where running multiple resource-intensive queries simultaneously causes would cause GPE dysfunction due to critical memory level handling.
* Improved error messaging when query installation fails because certain services are not in ready state.
* Fixed an issue that caused users to be unable to terminal an S3 loading job if the loading job did not use end-of-file mode.
* Made folder permissions more restrictive after cluster expansion and shrinking.
* Fixed an issue where creating a secret in a primary cluster could cause sync to stop.
* Fixed an issue that caused restoring a cluster to fail when the backup file is on S3.
* Fixed an issue where a heap accumulators (HeapAccum) might not be sorted when output in a group-by accumulator (GroupByAccum).
* Fixed an issue that caused file permissions to be incorrect after cluster resizing.
* Fixed an issue that caused imbalanced distribution of Kafka data when a cluster has a replication factor of two.
* Fixed an issue where `POST /requesttoken` endpoint did not return `Content-Type`.
* Fixed an issue that caused RESTPP dysfunction when it receives bearer token that is too short.
* Fixed an issue where the database did not properly authorize requests made from JDBC driver.
* Fixed an issue where GraphStudio data mapping would not detect disallowed data mapping to user-defined tuple (UDT) types.
* Fixed an issue where SumAccum in GroupByAccum cannot be converted to a MaxAccum directly
* Fixed an issue where loading large files through Data Streaming Connector might cause out-of-memory issues.
* Fixed an issue where loading jobs created with the Kafka loader could not show accurate progress in GraphStudio data loading.
* Fixed an issue where query installation in GraphStudio fails entirely if one of the queries being installed contains errors, instead of allowing valid queries to continue installation.
* Fixed an issue where the function `instr()` cannot accept certain special characters as substring argument.



== Dropped feature
* The `-OPTIMIZE` flag for `INSTALL QUERY` was deprecated in 3.5 and is dropped in this 3.7 release.

== Known Issues


|===
|In version |Description |Status
|3.7.0
|Frequent backups of large volumes of data could lead to failure during a backup.
|Unresolved

|3.7.0
|If a graph on an instance contains a loading job that uses `gsql_split_by_space()` token function, exporting the graph might lead to GPE dysfunction.
|Unresolved

|3.7.0
|Calling `vertex.edgeAttribute()` function with `STRING COMPRESS` data type causes GPE crash
|Unresolved

|3.7.0
|When vertices are automatically created during edge loading, the primary key of the vertices created are not written to vertex attributes.
|Unresolved

|3.7.0
|Calling the `setAttr()` function in an interpreted query causes GPE dysfunction.
|Unresolved

|===

For a list of known issues for GraphStudio and Admin Portal, please see xref:gui:graphstudio:known-issues.adoc[Known issues for GraphStudio] and xref:gui:admin-portal:known-issues.adoc[Known issues for Admin Portal].


== Release notes for previous versions
* xref:3.5@tigergraph-server:release-notes:index.adoc[Release notes - TigerGraph 3.5]
* xref:3.4@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.4]
* xref:3.3@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.3]
* xref:3.2@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.2]

== Compatibility with TigerGraph 3.4
* A single `POST-ACCUM` clause can no longer reference more than one vertex alias in Syntax V1.
* `GET /requesttoken` endpoint is dropped.
Please use `POST /requesttoken` to request authentication tokens instead.
** Using request body to store credentials is more secure than using query string.
If you have a create a token request that puts the credentials in the query string, all you need to do is use the `POST` endpoint and move your credentials to the request body. 
* `GET /gsqlserver/gsql/queryinfo` endpoint on port 14240 now returns the query input parameters in the same order as they are in the query instead of an unordered list.
* Deploying TigerGraph in Kubernetes now requires more service account permissions than previous versions.
For details, see Prerequisites section in xref:kubernetes:quickstart-with-gke.adoc[], xref:kubernetes:quickstart-with-aks.adoc[], and xref:kubernetes:quickstart-with-eks.adoc[].

== Compatibility with TigerGraph 3.1

The following changes were made to the built-in roles in TigerGraph's Role-based Access Control

* The built-in role `queryreader` can no longer run queries that include updates to the database.
** To emulate the old `queryreader` role, create a role with all `queryreader` privileges, and also grant the `WRITE_DATA` privilege to the new role.
* The built-in role `admin` can no longer create users
** To emulate the old `admin` role, create a global role with all `admin` privileges, and also grant the `WRITE_USER` privilege to the new role.
* To learn more about role management and the privileges of built-in roles, see:
** xref:user-access:role-management.adoc[]
** xref:reference:list-of-privileges.adoc[]

== Compatibility with TigerGraph 2

Major revisions (e.g., from TigerGraph 2 to TigerGraph 3) are the opportunity to deliver significant improvements. While we make every effort to maintain backward compatibility, in selected cases APIs have changed or deprecated features have been dropped, in order to advance the overall product.

*Data migration*: A tool is available to migrate the data in TigerGraph 2.6 to TigerGraph 3.0. Please contact TigerGraph Support for assistance.

*Query and API compatibility*:

* Some gadmin syntax has changed. Notably. `gadmin set config` is now `gadmin config set`.
Please see xref:system-management:management-with-gadmin.adoc[Managing with gadmin].
* Some features which were previously deprecated have been dropped. Please see xref:release-notes:v3.0-removal-of-previously-deprecated-features.adoc[V3.0 Removal of Previously Deprecated Features] for a detailed list.

include::v3.0-removal-of-previously-deprecated-features.adoc[]