= Release Notes
:description: Release notes for TigerGraph 3.5.
:page-aliases: change-log.adoc

TigerGraph Server 3.5.0 was released on Jan 31st, 2022.


== New Features

Below is a list of new features and improvements in TigerGraph 3.5.0:

=== Manageability


=== Observability


=== Reliability
* Added the `gsql-atomic-level` header to the endpoint `POST /graph/\{graph_name}` to allow users to set atomicity levels in upsert requests.

=== Security
* Added xref:user-access:access-control-model.adoc#_access_control_lists[Access Control Lists] to queries for fine-grain access control.
* Added xref:data-loading:kafka-loader/kafka-ssl-sasl.adoc[SSL/SASL support for Kafka loader].
* Masked secrets and user credentials in RESTPP logs.



=== Usability - GSQL


=== Usability - GraphStudio and Admin Portal



== Fixed issues

=== Fixed in 3.5.0





== Known Issues

=== Applications

* *GraphStudio*
 ** xref:gui:graphstudio:known-issues.adoc[Known Issues for GraphStudio]
 ** The No-Code Data Migration feature is in Alpha release. Your feedback would be appreciated.
 ** The No-Code Visual Query Builder is in Beta release. Your feedback would be appreciated.
* *Admin Portal*
 ** xref:gui:admin-portal:known-issues.adoc[Known Issues for AdminPortal]

=== *GSQL*

* *Multiple (Conjunctive) Path Patterns*:
 ** There are no known functional problems, but the performance has not been optimized. Your feedback would be appreciated.
* *DML type check error in V2 Syntax:*
 ** GSQL will report a wrong type check error for Query block with multiple POST-ACCUM clauses and Delete/Update attribute operation.
* *Turn on GSQL HA manually when upgrading from 3.0.x*
 ** Users who are upgrading from 3.0.X need to manually start GSQL HA service. Please reach out to support for help with the process documented in: https://tigergraph.freshdesk.com/a/solutions/articles/5000865072
* *Stale data visible after Deletes using index*
 ** Queries that use secondary index may still see the vertices being deleted until after the snapshots are fully rebuilt.

== Release notes for previous versions
* xref:3.3@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.3]
* xref:3.2@tigergraph-server:release-notes:release-notes.adoc[Release notes - TigerGraph 3.2]

== Compatibility with TigerGraph 3.5

== Compatibility with TigerGraph 3.1

The following changes were made to the built-in roles in TigerGraph's Role-based Access Control

* The built-in role `queryreader` can no longer run queries that include updates to the database.
** To emulate the old `queryreader` role, create a role with all `queryreader` privileges, and also grant the `WRITE_DATA` privilege to the new role.
* The built-in role `admin` can no longer create users
** To emulate the old `admin` role, create a global role with all `admin` privileges, and also grant the `WRITE_USER` privilege to the new role.
* To learn more about role management and the privileges of built-in roles, see:
** xref:user-access:role-management.adoc[]
** xref:reference:list-of-privileges.adoc[]

== Compatibility with TigerGraph 2

Major revisions (e.g., from TigerGraph 2 to TigerGraph 3) are the opportunity to deliver significant improvements. While we make every effort to maintain backward compatibility, in selected cases APIs have changed or deprecated features have been dropped, in order to advance the overall product.

*Data migration*: A tool is available to migrate the data in TigerGraph 2.6 to TigerGraph 3.0. Please contact TigerGraph Support for assistance.

*Query and API compatibility*:

* Some gadmin syntax has changed. Notably. `gadmin set config` is now `gadmin config set`.  Please see xref:gadmin:management-with-gadmin.adoc[Managing with gadmin].
* Some features which were previously deprecated have been dropped. Please see xref:release-notes:v3.0-removal-of-previously-deprecated-features.adoc[V3.0 Removal of Previously Deprecated Features] for a detailed list.

include::v3.0-removal-of-previously-deprecated-features.adoc[]