= Changing Ports
:description: Learn how to change default ports in TigerGraph. Note that default ports have changed since version 4.1.

[NOTE]
====
Starting with *TigerGraph 4.1*, port usage for REST API requests has changed.

* The *RESTPP service (port 9000)* is no longer publicly accessible.  
* Use the *GSQL server (port 14240)* for API requests on self-managed systems.  
* For *TigerGraph Cloud*, send API requests to **port 443**.  

For more details, see the xref:4.1@tigergraph-server:API:index.adoc[REST API reference].
====

The following ports apply to *TigerGraph versions earlier than 4.1*:

* *9000* – serves RESTPP, which accepts upstream TigerGraph Nginx requests.  
* *14240* – serves TigerGraph Nginx.

If the above ports are restricted in your environment and cannot be enabled (for whatever reason) you can change them once TigerGraph is up and running by running the following commands as tigergraph user:

For changing port 9000 (RESTPP) to something else (e.g. 9090)

[source,bash]
----
$ gadmin config set RESTPP.NginxPort 9090
$ gadmin config apply
$ gadmin restart
----

For changing the port 14240 (Nginx) to something else (e.g. 8080)

[source,bash]
----
$ gadmin config set Nginx.Port 8080
$ gadmin config apply
$ gadmin restart
----
