= Hardware and Software Requirements
:description: System requirements for running TigerGraph in a production or development environment.
:pp: {plus}{plus}

This page details the system requirements for running TigerGraph in a production or development environment.

TigerGraph can be used for different scopes and the system requirements largely depend on the use of the software.
This page provides a good reference, but actual hardware requirements will vary based on your data size and workload.

== Hardware Requirements

NOTE: The actual needs depend on data size and application requirements. Consult our solution architects for an estimate of memory and storage needs.

Choosing the right Hardware, that is going to host the TigerGraph nodes, is crucial for a balanced cost/perfomance ratio. Below you can find our general suggestions:

=== For personal use only (e.g. playground)
|===
| Component | Specification 

| CPU
| 4 cores (≥ 2.10GHz)

| RAM
| 8 GB

| Storage
| ≥ 50 GB (SSD)

| Network
| 1 Gigabit Ethernet adapter
|===

=== For enviroments like DEV, UAT, SIT
|===
| Component | Specification 

| CPU
| ≥ 16 cores (≥ 3.00GHz)

| RAM
| ≥ 32 GB

| Storage
| ≥ 300 GB (SSD)

| Network
| 1 Gigabit Ethernet adapter
|===

=== For PROD environemnt 
|===
| Component | Specification 

| CPU
| ≥ 32 cores (≥ 3.40GHz)

| RAM
| ≥ 64 GB

| Storage
| ≥ 500 GB (SSD)

| Network
| 10 Gigabit Ethernet adapter
|===


== Key point

=== CPU

NOTE: The supported architeture is x84_64


Choosing the right CPU type/model is important, for example *Intel Core i5* is good enough for lower enviroments like DEV, SIT, UAT. Instead for PRODUCTION you need more performat processors like *Intel Core i7*, *Intel Xeon Gold*, *AMD Epyc*.

Another important point in chosing the CPU, is the clock speed. We highly reccomend using *≥ 3.00GHz* (if possible opt for ≥ 3.40GHz for PROD)

Below is a good suggestion for PROD evinroment 
```bash
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              24
On-line CPU(s) list: 0-23
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           24
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
Stepping:            7
CPU MHz:             2992.969
```

=== RAM (Memory)

RAM size is crucial in TigerGraph for exeptional performance in Read and Writes. The RAM size is based on multiple factors:

* Dataset partitioning (number of partition in your TigerGraph Cluster)
* Type of workload (e.g. OLAP/OLTP queries, intensive CRUD operation....)
* Query SLAs

Given the fact that TigerGraph is a modern technology, therefore we *do not* reccomend using less than 8GB RAM. Most of our users use above 32GB RAM. 

RAM is not only size but also type, in fact we *strongly* reccomend using types of DDR SDRAM family, e.g. DDR4 SDRAM is a suggested type.

=== Disk 

Using Solid-State-Drive (SSD) is *mandatory* for TigerGraph as its designed to run on Solid-State-Drive (SSD).

Using spinning disks (HDD) can cause several issues like:

* Timeouts between internal components of TigerGraph
* Issue when taking backups
* Issues when restring TigerGraph
* Low performance 

NOTE: TigerGraph is not resposible for any issues caused by using spinning disk (HDD)

Another important point when choosing the Disk type is the disk IOPS capacity, we *strongly* suggest opting for ≥3000 IOPS


[#_certified_operating_systems]
== Certified Operating Systems

The TigerGraph Software Suite is built on 64-bit Linux.
It can run on a variety of Linux 64-bit distributions.
The software has been tested on the operating systems listed below:

.List of supported OS

|===
| Distro | Supported 

| RedHat 7.0 to 8.3
| ✓

| CentOs 6.5 to 8.0
| ✓

| Amazon Linux 2016.03 to 2018.03
| ✓

| Ubuntu 16.04 LTS
| ✓

| Ubuntu 18.04 LTS
| ✓

| Ubuntu 20.04 LTS
| ✓

| Debian 8
| ✓

| Suse 12
| ✓

| Oracle Linux 8.0 to 8.4
| ✓

| Windows (all version)
| X

| MacOS (Intel and M1 chip)
| X
|===


When a range of versions is given, it means that the software has been tested on the oldest and newest versions.
We continually evaluate the operating systems on the market and work to update our set of supported operating systems as needed.

The TigerGraph installer installs its own copies of Java JDK and GCC, accessible only to the TigerGraph Linux user, to avoid interfering with any other applications on the same server.

== Prerequisite Software

=== Shell

Please use a bash shell for the installation process.

=== Utilities

Before offline installation, the TigerGraph system needs a few basic software packages to be present:

* `crontab`
* `curl`
* `ip`
* `more`
* `netcat`
* `netstat`
* `net-tools`
* `ssh`/`sshd` (Only required for cluster installation)
* `sshpass`
* `tar`

NOTE: If they are not present, the TigerGraph installer will exit with an error reporting which package/s are missing. Contact your system administrator to have them installed on your target system. For example, they can be installed with one of the following commands.

[source,console]
----
# Centos or RedHat:
sudo yum install tar curl cronie iproute util-linux-ng net-tools nc coreutils openssh-clients openssh-server sshpass

# Ubuntu or Debian (Except Ver 18.04):
sudo apt install tar curl cron iproute util-linux net-tools netcat coreutils openssh-client openssh-server sshpass

# Ubuntu or Debian (Ver. 18.04):
sudo apt install tar curl cron iproute2 util-linux net-tools netcat coreutils openssh-client openssh-server sshpass
----

[#_ntp]
=== NTP

If you are running TigerGraph on a multi-node cluster, you *must* install, configure and run the NTP (Network Time Protocol) daemon service. This service will synchronize system time among all cluster nodes.

[#_fw]
=== Firewall

If you are running TigerGraph on a multi-node cluster, you *must* configure the iptables/firewall rules to make all TCP ports open among all cluster nodes.

=== Browser

In an on-premises installation, the system is fully functional without a web browser. To run the optional browser-based TigerGraph GraphStudio User Interface or Admin Portal, you need an appropriate browser:

|===
| Browser | Chrome | Safari | Firefox | Opera | Edge | Internet Explorer

| Supported version
| 54.0+
| 11.1+
| 59.0+
| 52.0+
| 80.0+
| 10+
|===
