= TigerGraph installer 

TigerGraph package comes with a bash installation script that can be run either in interactive mode or non-interactive mode

The installer script (`install.sh`) takes care on installing all TigerGraph required components and packages and provide an up and running TigerGraph environment once completed.

== NTP and Firewall

The setup and configurations for xref:installation:hw-and-sw-requirements.adoc#_ntp[NTP] and xref:installation:hw-and-sw-requirements.adoc#_fw[Firewall] will be taken care by the TigerGraph Installer.

== Installer pre-check

The first task that the TigerGraph Installer will run is the pre-check step


== Non-interactive installation

This is the preferred way for installing TigerGraph, as it allows you to visualize the entire configuration in one place.

The `install.sh` scripts relies on its configuration JSON file called `install_conf.json` which holds all the configuration information required for installing TigerGraph. 

In this installation mode, you need to edit the `install_conf.json` and manually pass all your configuration information.

This is an example of a *manually modified* `install_config.json` configuration file

[#_install_conf_example]
[,javascript]
----
{
  "BasicConfig": {
    "TigerGraph": {
      "Username": "mark",
      "Password": "markpassword",
      "SSHPort": 22,
      "PrivateKeyFile": "",
      "PublicKeyFile": ""
    },
    "RootDir": {
      "AppRoot": "/home/tigergraph/tigergraph/app",
      "DataRoot": "/home/tigergraph/tigergraph/data",
      "LogRoot": "/home/tigergraph/tigergraph/log",
      "TempRoot": "/home/tigergraph/tigergraph/tmp"
    },
    "License": "<license>",
    "NodeList": [
      "m1: 123.456.78.99",
      "m2: 123.456.78.98",
      "m3: 123.456.78.97",
      "m4: 123.456.78.96"
    ]
  },
  "AdvancedConfig": {
    "ClusterConfig": {
      "LoginConfig": {
        "SudoUser": "tom",
        "Method": "K",
        "P": "<sudo_user_password>",
        "K": "/home/tom/mykey.pem"
      },
      "ReplicationFactor": 2
    }
  }
}
----

The above `install_conf.json` configuration file will install TigerGraph as:

* Cluster mode with 4 machines, using Replication Factor of 2
** Which means that my dataset will be partitioned over 2 machines and each partiton will have its own copy (replica). In TigerGraph we call this topology as 2x2
* It will use port 22 for SSH connectivity
* It will create a user named `mark` with password `markpassword` that will own and manage TigerGraph 
* It will use the sudo user `bob` and it's `pem` key to access all the machines (provided in the `"NodeList"`) to install TigerGraph

In order to let the `install.sh` script use the modifed `install_conf.json` file while installing you need to pass the flag `-n` for the `install.sh` script, see below:

[,console]
----
$ cd tigergraph-<version>-offline

#sudo not requried for standalone installation
$ sudo ./install.sh -n
----

=== Here is a description of all the fields in the install_conf.json file:

* `"BasicConfig"`
 ** `"TigerGraph"` : Information about the Linux user that will be created by the installer who owns and manages the TigerGraph platform.
  *** `"Username"`: Username of the Linux user. If you have an existing user that you want to use for managing TigerGraph you can pass that here
  *** `"Password"`: Password of the Linux user.
  *** `"SSHPort"`: Port number used to establish SSH connections. 
  *** `"PrivateKeyFile"` (*optional*):  Absolute path to a valid private key file. If left empty, TigerGraph will generate one named `tigergraph.rsa` automatically.
  *** `"PublicKeyFile"`(*optional*): Absolute path to a valid public key file. If left empty, TigerGraph will generate one named `tigergraph.pub` automatically.
 ** `"RootDir"`
  *** `"AppRoot"`: Absolute path to where application folder will be.
  *** ``"DataRoot``": Absolute path to where the data folder will be.
  *** `"LogRoot"`: Absolute path to where the log folder will be.
**** For production systems, it’s recommended that you use a separate disk partition to store log files to prevent out-of-space issues.
  *** `"TempRoot"`: Absolute path to where the temp folder will be.
 ** `"License"`: Your TigerGraph license string.
 ** `"Node List"`:  A JSON array of the nodes in the cluster. Each machine in the cluster is defined as a key-value pair, where the key is a machine alias (m1, m2, m3, etc.) and the value is the IP address of the node.
* `"AdvancedConfig"`
 ** `"ClusterConfig"`: Cluster configurations
  *** `"LoginConfig"`: Login configurations
   **** `"SudoUser"`: Username of the sudo user who will be used to execute the installation on all nodes.
   **** `"Method"`: Authentication method for SSH.
Enter `"P"` to use password authentication and `"K"` to use key-based authentication.
If you use key-based authentication, the sudo user you are providing must have password-less sudo access on all nodes in the cluster.
   **** `"P"`: Password of the sudo user.
   **** `"K"`: Absolute path to the SSH key to be used to authenticate the sudo user.
  *** `"ReplicationFactor"`: xref:intro:continuous-availability-overview.adoc#_continuous_availability__definitions[Replication factor] of the cluster.
   **** If you would like to enable the High Availability (HA) feature, please make sure you have at least 3 nodes in the cluster and set the replication factor to be greater than 1. For example, if your cluster has 6 nodes, you could set the replication factor to be 2 or 3. If you set the replication factor to be 2, then the partitioning factor will be  6 / 2 = 3.  Therefore, 3 nodes will be used for one copy of the data, and the other 3 nodes will be used as a replica copy of the data.
   **** Ensure that the total number of nodes can be fully divided by the replication factor.  Otherwise, some nodes may not be utilized as parts of the HA cluster.

WARNING: If you alter the `RootDir` folder paths, make sure the new user created to manage the platform has the appropriate permissions.
The user needs read/write/execute permissions on `AppRoot` and read/write permissions on the other folders at a minimum.
