= Post installation checks

After installation is complete, you can switch to the Linux user who owns the platform (e.g. tigergraph) with the following command :

[,console]
----
$ su <username>  # default username: tigergraph
----

After switching to the correct user, you now have access to xref:system-management:management-with-gadmin.adoc[`gadmin` commands]. Confirm successful installation by running `gadmin status`. If the system is installed correctly and the license is activated, the command should report that all services are up and ready.

[,console]
----
$ gadmin status
+--------------------+-------------------------+-------------------------+
|    Service Name    |     Service Status      |      Process State      |
+--------------------+-------------------------+-------------------------+
|       ADMIN        |         Online          |         Running         |
|        CTRL        |         Online          |         Running         |
|        DICT        |         Online          |         Running         |
|        ETCD        |         Online          |         Running         |
|        EXE         |         Online          |         Running         |
|        GPE         |         Warmup          |         Running         |
|        GSE         |         Warmup          |         Running         |
|        GSQL        |         Online          |         Running         |
|        GUI         |         Online          |         Running         |
|        IFM         |         Online          |         Running         |
|       KAFKA        |         Online          |         Running         |
|     KAFKACONN      |         Online          |         Running         |
|    KAFKASTRM-LL    |         Online          |         Running         |
|       NGINX        |         Online          |         Running         |
|       RESTPP       |         Online          |         Running         |
|        TS3         |         Online          |         Running         |
|      TS3SERV       |         Online          |         Running         |
|         ZK         |         Online          |         Running         |
+--------------------+-------------------------+-------------------------+
----

NOTE: Since there is no graph data loaded yet, GSE and GPE will show `"Warmup"`.

=== Check SSH connectivity between the TigerGraph nodes

After installation is done, you want to check that you are able to "move" via ssh between all the TigerGraph nodes. To do so you can use the command `gssh` which is a wrapper aroud the `ssh` command. 

The usage is pretty simple, just pass the node you want to connect to like this `gssh m3` and you will be connected to it. 

If this check fails, then you need to address it. Feel free to reach out to our Technical Support Team by opening a https://tigergraph.zendesk.com/hc/en-us/[support ticket] to request assistance.


=== Port check

WARNING: The checks described below require a TigerGraph Cluster stop and restart.

Another important task to perform after installing TigerGraph Cluster is to make sure that all the required TigerGraph ports are open and allowing communication. 

Run the following two bash scripts to perform an extensive port check

==== For services port check

[,bash]
----
#!/bin/bash

echo "Collecting nodes IPs..."
ipAddr=$(echo $(gadmin config get System.HostList) | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')
PEM=$(gadmin config get System.SSH.User.Privatekey)

PORTS=("2888" "2892" "3888" "3892" "5400" "5500" "6500" "7500" "7501" "7502" "8123" "8124" "8400" "8401" "8500" "8501" "8900" "9000" "9166" "9167" "9177" "9178" "9188" "9400" "9401" "9500" "9501" "12471" "14240" "14241" "14242" "14243" "17797" "19000" "19001" "19999" "20000" "20001" "30002" "30004" "30003")

echo "Stopping TigerGraph for this test..."
gadmin stop all -y

for p in ${PORTS[@]} 
    do
        for i in ${ipAddr[@]} 
            do 
                ssh -i $PEM tigergraph@$i /var/tmp/netcat/nc -l $p&
                sleep 1
                /var/tmp/netcat/nc -zv $i $p 
         done    
done 

echo "Starting TigerGraph again...."
gadmin start all
----

===== Usage:

1. Save the above script as `service_port_check.sh`

2. Give it executable permission with `sudo chmod +x service_port_check.sh` 

3. Run it with `bash service_port_check.sh >> service_port.out`

==== For dynamic port check

WARNING: This will take a while before completing, it's recommended you run this in the background to avoid session timeout. 

[,bash]
----
#!/bin/bash

echo "Collecting nodes IPs..."
ipAddr=$(echo $(gadmin config get System.HostList) | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')
PEM=$(gadmin config get System.SSH.User.Privatekey)

echo "Stopping TigerGraph for this test..."
gadmin stop all -y
echo "Dynamic port check, this will take a while...."

for dyn in {49152..65535} 
    do
        for i in ${ipAddr[@]}
            do 
               ssh -i $PEM tigergraph@$i /var/tmp/netcat/nc -l $dyn&
                sleep 1
                /var/tmp/netcat/nc -zv $i $dyn
         done    
done

echo "Starting TigerGraph again...."
gadmin start all
----

===== Usage:

1. Save the above script as `dynamic_port.sh`

2. Give it executable permission with `sudo chmod +x dynamic_port.sh` 

3. Run it with `bash dynamic_port.sh >> dynamic_port.out`

Once done check both `service_port_check.out` and `dynamic_port.out` and make sure that all connection attempts are successful. 

NOTE: Any unsuccessful connection attempt *must* be addressed. Feel free to reach out to our Technical Support Team by opening a https://tigergraph.zendesk.com/hc/en-us/[support ticket] to request assistance.


  
