= Upgrading an Existing Installation
:toc:
This page describes the steps to upgrade an existing installation of
TigerGraph to TigerGraph {page-component-version}.

== Before you begin

===  Check release notes for changes in functionality

IMPORTANT: Always check the xref:release-notes:index.adoc[] for all the versions between your current version and your target version, for deprecated features, known issues, or other behavioral changes.
You may need to make migration changes to your TigerGraph application either before or after the upgrade.
If you have any questions or uncertainty, please contact TigerGraph Support.

=== Upgrading from a version older than 3.2

. First perform a backup xref:backup-and-restore:index.adoc[using GBAR (Graph Backup and Restore)] on your existing installation.
. *Restore* your installation with GBAR to rebuild it.
This step is necessary because TigerGraph 3.2 made major changes to the Graph Storage Engine and a restore is needed to remove certain files that would make the upgrade operation fail.
. Ensure that the restore is completely finished and there are no pending graph modifications (schema change, insert, update, or delete) before starting the upgrade.
You can do this by calling the xref:tigergraph-server:API:built-in-endpoints.adoc#_rebuild_graph_engine[/rebuildnow] endpoint and waiting until there are no more PullDelta messages being printed in the logs.

=== Upgrading a CRR system
To upgrade the TigerGraph software on a CRR system, follow this sequence of steps.

1. Disable CRR on your DR cluster.

[source.wrap,console]
----
$ gadmin config set System.CrossRegionReplication.Enabled false
$ gadmin config apply -y
$ gadmin restart all -y
----

2. Upgrade both the primary cluster and DR cluster, according to the instructions on this page.

3. Enable CRR on the DR cluster.

[[upgrading-from-v3x]]
== Upgrading from v3.x

Any 3.x version of TigerGraph can be upgraded to another v3.x version by
running the installation script with the upgrade(`+-U+`) flag.

. Download the latest version of TigerGraph to your system.
. Extract the tar file.
. Run the installation script under the Linux user created during
installation with the upgrade flag (`+-U+`) that was extracted from the
tar file:

....
$ ./install.sh -U
....

[NOTE]
====
Please upgrade from the most recent maintenance version in any minor release.
If you are upgrading from a version that does not have the most recent patches applied to its minor version, upgrade to the most recent patches first before upgrading to another minor or major version.
For example, if you are upgrading from 3.5.0 to {page-component-version}, upgrade to 3.5.3 first using the installation script and then upgrade to {page-component-version}.

Additionally, versions upgrading from 3.0 or 3.1 must first go through 3.2.4.
For example, if you are running version 3.1.3, you must first upgrade to 3.1.6, then 3.2.4, then to {page-component-version}.
====


[[upgrading-from-v2x]]
== Upgrading from v2.x

Please contact TigerGraph Support to coordinate upgrading to TigerGraph version {page-component-version} if you are currently using a 2.x version of TigerGraph.
Even though all the steps are documented, it is strongly
recommended that you review the process with the TigerGraph
Support team.

Upgrading the Developer Edition or migrating to another edition are not supported.

For detailed upgrade procedures, see our support article on the
link:https://tigergraph.zendesk.com/hc/en-us/articles/8173584319892-2-6-x-to-3-x-upgrade-flow[2.6.x to 3.x upgrade flow]

[[upgrading-cloud-marketplace-image]]
== Upgrading Cloud Marketplace images

=== Upgrading from 3.x

. xref:backup-and-restore:backup-and-restore.adoc[Back up] your TigerGraph instance using GBAR.
. Start a new instance from the latest cloud marketplace listing.
. Use the backup files you generated earlier to xref:backup-and-restore:backup-and-restore.adoc[restore] the new instance.

=== Upgrading from 2.x

If you want to upgrade your Cloud Marketplace image from v2.x on any cloud platform, please https://tigergraph.zendesk.com/hc/en-us/[open a support ticket]. for instructions and assistance.
