= Upgrading an Existing Installation

This page describes the steps to upgrade an existing installation of
TigerGraph to TigerGraph 3.2.

== Before you begin

* xref:backup-and-restore:backup-and-restore.adoc[Use GBAR to perform a backup *and restore*] on your existing installation. This step is necessary because TigerGraph 3.2 made major changes to the Graph Storage Engine and a restore is needed to remove certain files that would make the upgrade operation fail.
* After restoring the backup, ensure that there are no vertex inserts or deletions before starting the upgrade.

[[upgrading-from-v3x]]
== Upgrading from v3.x

Any 3.x version of TigerGraph can be upgraded to another v3.x version by
running the installation script with the upgrade(`+-U+`) flag.

[arabic]
. Download the latest version of TigerGraph to your system.
. Extract the tarball.
. Run the install script under the Linux user created during
installation with the upgrade flag (`+-U+`) that was extracted from the
tarball:

....
$ ./install.sh -U
....

[[upgrading-from-v2x]]
== Upgrading from v2.x

Please contact TigerGraph Support to coordinate migration to TigerGraph
3.2 version if you are currently using a v2.x version of TigerGraph.
Even though all the steps for Migration are documented, it is strongly
recommended that you review the migration process with the TigerGraph
Support team.

Migration from versions later than 2.6 is supported. To migrate from
versions prior to 2.6, users are advised to contact TigerGraph Support
to check the feasibility of support the range of earlier versions.

Upgrade or migration from the Developer Edition is not supported.

For detailed upgrade procedures, see
https://tigergraph.freshdesk.com/support/solutions/articles/5000859240-2-x-to-3-0-0-upgrade-flow