= Upgrading an Existing Installation
:toc:
This page describes the steps to upgrade an existing installation of
TigerGraph to TigerGraph {page-component-version}.

== Before you begin

===  Check release notes for changes in functionality

[IMPORTANT]
Always check the xref:release-notes:index.adoc[] for all the versions between your current version and your target version, for deprecated features, known issues, or other behavioral changes.
You may need to make migration changes to your TigerGraph application either before or after the upgrade.
If you have any questions or uncertainty, please contact TigerGraph Support.

==== User-defined function (UDF) compatibility

TigerGraph version 3.9 introduced changes in the way user-defined functions are accepted by the system.

* Some UDFs may no longer be accepted due to xref:security:index.adoc#_udf_file_scanning[increased security screening].
* UDFs may no longer be called `to_string()`. This is now a built-in GSQL function.
* UDF names may no longer use the `tg_` prefix.

If any UDFs do not satisfy these restrictions, then they will not be installed. GSQL will return these errors:

.Reserved `tg_` prefix error
[source, console]
----
The following function name(s) contain errors:
  [reserved 'tg_']: tg_myFunction

Please rename the corresponding functions in: ExprFunctions.hpp
----

.Reserved `to_string()` function name
[source, console]
----
Following GSQL built-in function name(s): [to_string] can not be used again for user defined function name(s)!
GSQL built-in functions are case-insensitive. Please rename corresponding user defined functions in ExprFunctions.hpp.
----

Any user-defined function previously used in an older TigerGraph version that does not comply with these requirements must be renamed or removed in `ExprFunctions.hpp`.

=== Make a Backup

[IMPORTANT]
====
As a precaution, it is always a good idea to make a full backup before performing a major system change like an upgrade.
System upgrade does not support version rollback at this time.
====

=== Prepare a pre-3.2 database

. First perform a backup xref:backup-and-restore:index.adoc[using GBAR (Graph Backup and Restore)] on your existing installation.
. *Restore* your installation with GBAR to rebuild it.
This step is necessary because TigerGraph 3.2 made major changes to the Graph Storage Engine and a restore is needed to remove certain files that would make the upgrade operation fail.
. Ensure that the restore is completely finished and there are no pending graph modifications (schema change, insert, update, or delete) before starting the upgrade.
You can do this by calling the xref:tigergraph-server:API:built-in-endpoints.adoc#_rebuild_graph_engine[/rebuildnow] endpoint and waiting until there are no more PullDelta messages being printed in the logs.

=== Ensure that the database is inactive

[IMPORTANT]
Ensure that the database will be inactive throughout the upgrade process.

. Stop any new database requests.
. Ensure that all previous operations such as queries, loading jobs, schema changes, and data updates and deletions are completely finished.
Check the appropriate logs.
Call the xref:tigergraph-server:API:built-in-endpoints.adoc#_rebuild_graph_engine[/rebuildnow] endpoint to force the data store to consume all pending updates and then wait until there are no more PullDelta messages being printed in the logs.

== Upgrading a CRR system
To upgrade the TigerGraph software on a CRR system, follow this sequence of steps.

1. Disable CRR on your DR cluster.

[source.wrap,console]
----
$ gadmin config set System.CrossRegionReplication.Enabled false
$ gadmin config apply -y
$ gadmin restart all -y
----

2. Upgrade both the primary cluster and DR cluster, according to the instructions on this page.

3. Enable CRR on the DR cluster.



[[upgrading-from-v3x]]
== Upgrading from v3.x

Any 3.x version of TigerGraph can be upgraded to another v3.x version by
running the installation script with the upgrade(`+-U+`) flag.

. Download the latest version of TigerGraph to your system.
. Extract the tar file.
. Run the installation script under the Linux user created during
installation with the upgrade flag (`+-U+`) that was extracted from the
tar file:

....
$ ./install.sh -U
....

[NOTE]
====
Please upgrade from the most recent maintenance version in any minor release.
If you are upgrading from a version that does not have the most recent patches applied to its minor version, upgrade to the most recent patches first before upgrading to another minor or major version.
For example, if you are upgrading from 3.5.0 to {page-component-version}, upgrade to 3.5.3 first using the installation script and then upgrade to {page-component-version}.

Additionally, versions upgrading from 3.0 or 3.1 must first go through 3.2.4.
For example, if you are running version 3.1.3, you must first upgrade to 3.1.6, then 3.2.4, then to {page-component-version}.
====


[[upgrading-from-v2x]]
== Upgrading from v2.x

Please contact TigerGraph Support to coordinate upgrading to TigerGraph version {page-component-version} if you are currently using a 2.x version of TigerGraph.
Even though all the steps are documented, it is strongly
recommended that you review the process with the TigerGraph
Support team.

Upgrading the Developer Edition or migrating to another edition are not supported.

For detailed upgrade procedures, see our support article on the
link:https://tigergraph.zendesk.com/hc/en-us/articles/8173584319892-2-6-x-to-3-x-upgrade-flow[2.6.x to 3.x upgrade flow]

[[upgrading-cloud-marketplace-image]]
== Upgrading Cloud Marketplace Images

=== Upgrading from 3.x

. xref:backup-and-restore:backup-and-restore.adoc[Back up] your TigerGraph instance using GBAR.
. Start a new instance from the latest cloud marketplace listing.
. Use the backup files you generated earlier to xref:backup-and-restore:backup-and-restore.adoc[restore] the new instance.

=== Upgrading from 2.x

If you want to upgrade your Cloud Marketplace image from v2.x on any cloud platform, please https://tigergraph.zendesk.com/hc/en-us/[open a support ticket]. for instructions and assistance.

== Known Issues and Workarounds

When coming from older releases, we want to take as many preventative steps to update our UDF files to 3.9.0.

Several things may have changed between your current release and 3.9.0 and these steps should help to upgrade the UDF file before starting the upgrade process or prepare you to address anything that may come up as a result of the upgrade.


=== UDF file policy

possible links

Security - TigerGraph Server

In addition to the above changes, there is a new UDF File Policy.
It is recommended that users consult with the entire policy.
This policy is enforced through UDF file scanning to ensure there are none of the following (see the link above for more details on the file output policy):

Macros with replacement

Headers/Includes from potentially vulnerable C++ features

Users can, at their own discretion, add C++ headers to an allow list through a config in gadmin

they can also just disable the policy after upgrade, so the restrictions won’t take effect.

=== ExprFunctions.hpp defined following GSQL built-in functions:[to_string] ,

(fixed with auto remove, user don't need extra work in 3.10)
Insert Workaround for previous releases and any applicable links to current documentation

this is current behavior.
step 1 the original ExprFunctions.hpp produces a copy under same folder named with ExprFunctions.hpp+timestamp
step 2 the to_string functions (including the function header and body) will be completely deleted from ExprFunctions.hpp
That's what's been done for to_string functions during upgrade.
previously the customer will stuck at upgrade process since to_string is not allowed to use in ExprFunctions.hpp starting from 3.9.x version
Please feel free to contact me if you any other questions. Thanks.


=== Input/output file policy

Insert Workaround and any applicable links to current documentation

this will require user to either modify existing queries/loading jobs, or modify file input/output policy after upgrade

=== Other issues
{Insert Workaround and any applicable links to current documentation}