= Upgrading an Existing Installation

This page describes the steps to upgrade an existing installation of
TigerGraph to TigerGraph {page-component-version}.

== Before you begin
If you are upgrading from a version older than 3.2:

* First perform a backup *and a restore* xref:backup-and-restore:index.adoc[using GBAR (Graph Backup and Restore)] on your existing installation.
This step is necessary because TigerGraph 3.2 made major changes to the Graph Storage Engine and a restore is needed to remove certain files that would make the upgrade operation fail.
* After restoring the backup, ensure that there are no vertex inserts or deletions before starting the upgrade.


[[upgrading-from-v3x]]
== Upgrading from v3.x

Any 3.x version of TigerGraph can be upgraded to another v3.x version by
running the installation script with the upgrade(`+-U+`) flag.

. Download the latest version of TigerGraph to your system.
. Extract the tar file.
. Run the installation script under the Linux user created during
installation with the upgrade flag (`+-U+`) that was extracted from the
tar file:

....
$ ./install.sh -U
....

[NOTE]
Please upgrade from the most recent patch version in any minor release. 
If upgrading from a version that does not have the most recent patches applied to its minor version, upgrade to the most recent patches first before upgrading the major version.
For example, if upgrading from 3.1.3 to 3.5, upgrade to 3.1.6 first using the installation script and then upgrade to 3.5.

[[upgrading-from-v2x]]
== Upgrading from v2.x

Please contact TigerGraph Support to coordinate upgrading to TigerGraph version {page-component-version} if you are currently using a 2.x version of TigerGraph.
Even though all the steps are documented, it is strongly
recommended that you review the process with the TigerGraph
Support team.

Upgrading the Developer Edition or migrating to another edition are not supported.

For detailed upgrade procedures, see our support article on the
link:https://tigergraph.freshdesk.com/support/solutions/articles/5000859240-2-x-to-3-0-0-upgrade-flow[2.6.x to 3.x upgrade flow]

[[upgrading-cloud-marketplace-image]]
== Upgrading Cloud Marketplace images

=== Upgrading from 3.x

. xref:backup-and-restore:backup-and-restore.adoc[Back up] your TigerGraph instance using GBAR.
. Start a new instance from the latest cloud marketplace listing.
. Use the backup files you generated earlier to xref:backup-and-restore:backup-and-restore.adoc[restore] the new instance.

=== Upgrading from 2.x

If you want to upgrade your Cloud Marketplace image from v2.x on any cloud platform, Please contact mailto:support@tigergraph.com[TigerGraph Support] for instructions and assistance. 