==== Specify parsing rules
The streaming connector supports the following file types:

* CSV files.
* Parquet files.
* JSON files.
Each JSON object must be on a separate line.
* Directories.
* tar files.
* zip files.

For URIs that point to directories and compressed files, the connector looks for all files inside the directory or the compressed file that match the `file.regexp` parameter.
By default, this includes both CSV and JSON files.

If you set `file.recursive` to true, the connector looks for files recursively.


The following parsing options are available:


|===
|Name |Description |Default

|`file.regexp`
|The regular expression to filter which files to read.
The default value matches all files.
|`.*`

|`file.recursive`
|Whether to retrieve files recursively if the URI points to a directory.
|`true`

|`file.reader.type`
a|The type of file reader to use.

* Use `text` for text files and `parquet` for Parquet files.
|`text`

|`file.reader.delimited.separator`
|The character that separates columns.
This parameter does not affect JSON files.
|`,`

|`file.reader.delimited.quote`
a|The explicit boundary markers for string tokens, either single or double quotation marks.
This parameter does not affect JSON files.

The parser will not treat separator characters found within a pair of quotation marks as a separator.

Accepted values:

* `single`: single quotes `'` are boundary markers.
* `double`: double quotes `"` are boundary markers.
* Empty string `""`: Quotation marks are treated as ordinary characters.
| Empty string `""`

|`file.reader.delimited.value.default`
|The default value for a column when its value is null.
This parameter does not affect JSON files.
| Empty string `""`

|`file.reader.batch.size`
|The maximum number of lines to include in a single batch.
|`1000`

|`file.reader.text.eol`
|End of line character.
|`\n`

|`file.reader.text.header`
|Whether the first line of the files is a header line.
If the value is set to true, the first line of the file is ignored during data loading.
If you are using JSON files, set this parameter to false.
|`false`

|`file.reader.text.archive.type`
a|File type for archive files.
Setting the value of this configuration to `auto` will allow the connector to decide file types automatically based on the file extensions.
Accepted values:

* `tar`
* `zip`
* `gzip`
* `none`
* `auto`
|`auto`

|`file.reader.text.archive.extensions.tar`
|If a file has this extension, treat it as a tar file
|`tar`

|`file.reader.text.archive.extensions.zip`
|If a file has this extension, treat it as a zip file
|`zip`

|`file.reader.text.archive.extensions.gzip`
|If a file has this extension, treat it as a gzip file
|`gz`

|`file.reader.text.archive.extensions.tar.gz`
|If a file has this extension, treat it as a `tar.gz` file
|`tar.gz`,`tgz`
|===