=== Configure the Kafka source

To configure the data source object for Kafka, the minimum requirement is the address of the external source Kafka cluster:

[source,json,linenum]
.Data source configuration for an external Kafka source
----
{
  "type": "kafka",
  "bootstrap.servers": "{broker-addresses}"
}
----

==== Additional Configurations

These configurations are consistent with the Java Kafka consumer client settings.

To customize the consumer for authentication or advanced configurations, refer to the official Kafka documentation: link:https://kafka.apache.org/documentation/#consumerconfigs[Kafka Consumer Configurations].

==== Examples for SSL Encryption and Authentication

Each configuration must include the `type` and `bootstrap.servers` properties to specify the Kafka data source type and broker addresses.

===== SSL Configuration
To configure SSL for secure communication with the Kafka cluster, include the following properties:

[source,json]
----
{
  "type": "kafka",
  "bootstrap.servers": "{broker-addresses}",
  "security.protocol": "SSL",
  "ssl.truststore.location": "{truststore-location}",
  "ssl.truststore.password": "{truststore-password}",
  "ssl.keystore.location": "{keystore-location}",
  "ssl.keystore.password": "{keystore-password}",
  "ssl.key.password": "{key-password}"
}
----

===== SASL_PLAINTEXT Configuration
For SASL authentication over plaintext, use the following configuration:

[source,json]
----
{
  "type": "kafka",
  "bootstrap.servers": "{broker-addresses}",
  "security.protocol": "SASL_PLAINTEXT",
  "sasl.mechanism": "PLAIN",
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"{username}\" password=\"{password}\";"
}
----

===== SASL_SSL Configuration
For SASL authentication over SSL, use the following configuration:

[source,json]
----
{
  "type": "kafka",
  "bootstrap.servers": "{broker-addresses}",
  "security.protocol": "SASL_SSL",
  "sasl.mechanism": "PLAIN",
  "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"{username}\" password=\"{password}\";",
  "ssl.truststore.location": "{truststore-location}",
  "ssl.truststore.password": "{truststore-password}"
}
----

===== Amazon MSK Configuration
For Amazon MSK with IAM authentication, use the following configuration:

[source,json]
----
{
  "type": "kafka",
  "bootstrap.servers": "{broker-addresses}",
  "security.protocol": "SASL_SSL",
  "sasl.mechanism": "AWS_MSK_IAM",
  "sasl.jaas.config": "software.amazon.msk.auth.iam.IAMLoginModule required;",
  "sasl.client.callback.handler.class": "software.amazon.msk.auth.iam.IAMClientCallbackHandler",
  "ssl.truststore.location": "{truststore-location}",
  "ssl.truststore.password": "{truststore-password}"
}
----

===== Google Cloud Kafka Configuration
For Kafka on Google Cloud with SASL authentication, use the following configuration:

[source,json]
----
{
  "type": "kafka",
  "bootstrap.servers": "{broker-addresses}",
  "security.protocol": "SASL_SSL",
  "sasl.mechanism": "OAUTHBEARER",
  "sasl.jaas.config": "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;",
  "sasl.login.callback.handler.class": "com.google.cloud.hosted.kafka.auth.GcpLoginCallbackHandler",
  "ssl.truststore.location": "{truststore-location}",
  "ssl.truststore.password": "{truststore-password}"
}
----

==== Schema Registry Service
To load Avro data through a https://docs.confluent.io/platform/current/schema-registry/index.html[schema registry service], include the schema registry details in the data source configuration:

[source,json]
{
  "type": "kafka",
  "bootstrap.servers": "{broker-addresses}",
  "value.converter.schema.registry.url": "{schema-registry-url}",
  "value.converter.schema.registry.basic.auth.credentials.source": "USER_INFO",
  "value.converter.schema.registry.basic.auth.user.info": "{username}:{password}",
  "value.converter":"com.tigergraph.kafka.connect.converters.TigerGraphAvroConverter"
}

[NOTE]
Currently, only Avro schema is supported.