NOTE: While a loading job may have multiple `FILENAME` variables, they must all refer to the same `DATA_SOURCE` object.

==== Filename Descriptors
The file descriptor has three valid formats.
You can simply provide the Kafka topic name and use default settings. Or, you can provide configuration details including the topic, either in a JSON file or as inline JSON content.

[source,php,linenum]
DEFINE FILENAME file_name = "$[data source name]:[topic]";
DEFINE FILENAME file_name = "$[data source name]:[json config file]";
DEFINE FILENAME file_name = "$[data source name]:[inline json content]";

For example:

[source,go]
----
// Format 1: topic only
DEFINE FILENAME file_Person = "$s1:topic_Person";

// Format 2: topic and configuration file
DEFINE FILENAME file_Person = "$s1:myfile.json";

// Format 3: topic and inline configuration
DEFINE FILENAME file_Person="""$s1:{
    "topic": "topic_Person",
    "partition.offsets": "0:0,1:3,2:-1"
}""";
----

To load a topic with more granular control, you can define the filename in JSON format using the parameters described in the following "Filename parameters" section.

==== Filename parameters

These are the required and optional configuration parameters:

[%header,cols="1,4,1,4"]
|===
|Parameter |Description |Required? |Default value

| topic
| The source topic name
| Required
| N/A

| time
| The start timestamp to consume from. -1 means consume from the latest offset, -2 means consume from the beginning. If unset, consume from the beginning. If 'partition_offsets' is set, this setting will be ignored.
| Optional
| -2

| partition.offsets
| Specifies the partition offsets to consume from, separated by commas. For example, `0:0,1:3,2:-1` indicates that partition 0 starts at offset 0, partition 1 starts at offset 3, and partition 2 starts at the latest offset. The format is `partition_number:offset`. Here, `-1` represents the latest offset, and `-2` represents the beginning of the partition. If not specified, all partitions are consumed from the beginning.
| Optional
| N/A

| tasks.max
| The maximum number of tasks used to consume the source topic.
You can increase this value when the source topic contains multiple partitions.
| Optional
| 1
|===

For example:

[source,go]
----
// Example 1: Specify the start timestamp to consume from
DEFINE FILENAME file_Person="""$s1:{
    "topic": "topic_Person",
    "time": "1745203693324"
}""";

// Example 2: Specify partition offsets: partition 0 starts at offset 200, partition 1 starts at offset 100, and partition 2 starts at the latest offset
DEFINE FILENAME file_Person="""$s1:{
    "topic": "topic_Person",
    "partition.offsets": "0:200,2:100,3:-1"
}""";
----


[NOTE]
For Avro data with schema registry, you must set both `value.converter.schema.registry.url` when defining the DATA_SOURCE and `value.converter` when defining a FILENAME.