=== Configure the Kafka source

The TigerGraph connector to external Kafka sources makes use of https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=27846330[Apache Kafka Mirrormaker].

[NOTE]
====
Users can additionally utilize external sources, including files, Vault, and environment variables, to provide configurations for Kafka connectors. See xref:tigergraph-server:data-loading:externalizing-kafka-configs.adoc[].
====

To configure the data source object, the minimum requirement is the address of the external source Kafka cluster:

[source,json,linenum]
.Data source configuration for external Kafka
----
{
  "type": "mirrormaker",
  "source.cluster.bootstrap.servers": "<broker_addrs>"
}
----

* If the source cluster uses SSL, see our documentation xref:tigergraph-server:data-loading:kafka-ssl-security-guide.adoc[]

If there is a https://docs.confluent.io/platform/current/schema-registry/index.html[schema registry service] containing the record schema of the source topic, please add it to the data source configuration:

[source,json]
"value.converter.schema.registry.url": "schema_registry_url"

[NOTE]
Currently, only Avro schema is supported.

