= Get Started on Microsoft Azure

This tutorial will show you how to start TigerGraph Enterprise Edition from an image on Microsoft Azure.

== *Deploying Your Instance*

. Go to link: https://portal.azure.com/#blade/Microsoft_Azure_Marketplace/MarketplaceOffersBlade/selectedMenuItemId/home[Microsoft Azure Marketplace] and search for "TigerGraph".
. Select your software plan and Click "Create". Select the latest plan (with the highest version number) to access the latest features.

image::create-page (1).png[Create Page]

. Fill out the "Resource group", "Virtual machine name", "Username" and "SSH Public key" fields. The default values should work for the rest of the fields. Then click "*Next: Disks >*".

image::basic-settings-page (1).png[Basic Settings Page]

. Keep the default values for all other settings and click "Next" until you see the "Review + Create" page below. Check all your settings and click "Create" when you are satisfied.

*Notes:* +
The instance type needs to have at least 4 CPUs and 16GB RAM for TigerGraph to work properly.

The "NIC network security group" must allow inbound TCP traffic to port 14240 if you want to access GraphStudio (TigerGraph's visualization platform). For more about GraphStudio, see the xref:gui:graphstudio:overview.adoc[GraphStudio UI Guide].

The "NIC network security group" must allow inbound TCP traffic to port 9000 if you want to send RESTful requests to TigerGraph from outside the instance (this includes configuring the GSQL client on a remote machine). For more about the REST API, see the xref:API:intro.adoc[TigerGraph RESTful API User Guide].

For more about the TigerGraph Platform, see the xref:intro:introduction.adoc[TigerGraph Platform Overview].

image::review-page (1).png[Review Page]

. That's it!  The TigerGraph instance has been successfully deployed on Microsoft Azure.

image::deployment-successful-page (1).png[Deploying Page]

== *Starting TigerGraph on Your Instance*

. Log on to the instance and switch to user `tigergraph` using the following command:

[,console]
----
sudo su - tigergraph
----

image::login-to-tigergraph (7).png[TigerGraph Login]

. Run the following command to check the current status of TigerGraph. The services *"ADMIN", "CTRL", "ETCD", "IFM", "KAFKA", and "ZK" are started automatically* and should be up at this point. If any of them are not or you get the following error message, *please wait for 30 to 60 seconds and check the status again* before reporting it to TigerGraph support.

[,console]
----
gadmin status
----

image::gadmin-status (1).png[Output of gadmin status]

image::gadmin-status-error-message (1).png[Gadmin status error message]

. Run the following command to start TigerGraph:

[,console]
----
gadmin start
----

image::gadmin-start (9).png[Output of gadmin status]

. Check the status again. All services should be up at this point:

[,console]
----
gadmin status
----

image::gadmin-status-after-start (1).png[Gadmin status after running gadmin start]

. TigerGraph has been successfully started on your cloud instance.

== TigerGraph License on *Microsoft Azure* Images

The TigerGraph Enterprise edition image comes with *a perpetual license* that will *only work on the Microsoft Azure instance it's installed on*. Please run the following command to see it:

[,console]
----
gadmin license status
----

image::gadmin-license-status (2).png[Gadmin license status output]
