= Get Started on Google Cloud

This tutorial will show you how to start TigerGraph from an image on Google Cloud. Please select your edition from below:

== *Deploying Your Instance*

. Go to Google Cloud Marketplace https://console.cloud.google.com/marketplace and search for  "TigerGraph Enterprise Edition". Choose the latest edition to access the most up-to-date features.
. Click on "Launch"​‌.

image::console-page (9).png[]

. The default settings are fine for most users, but feel free to modify them. When ready, click on "Deploy".

*Notes:* +
The instance type needs to have at least 4 CPUs and 16GB RAM for TigerGraph to work properly.

The "Allow TCP port 14240 traffic from the Internet" checkbox must be checked if you want to access GraphStudio (TigerGraph's visualization platform). For more about GraphStudio, see the xref:gui:graphstudio:[GraphStudio UI Guide].

For information on how to set up authentication please see xref:user-access:README.adoc[User access management].

The "Allow TCP port 9000 traffic from the Internet" checkbox must be checked if you want to send RESTful requests to TigerGraph from outside the instance (this includes configuring the GSQL client on a remote machine). For more about the REST API, see the xref:API:intro.adoc[REST API Reference].‌

For more about the TigerGraph Platform, see the xref:intro:introduction.adoc[TigerGraph Platform Overview].​

image::deployment-form (9).png[]

. That's it! The TigerGraph instance has been successfully deployed on Google Cloud.​‌

image::deploying-page (9).png[]

== *Starting TigerGraph on Your Instance*

‌1. Log on to the instance and switch to user `tigergraph` using the following command:

[,text]
----
sudo su - tigergraph
----

image::login-to-tigergraph (8).png[]

. Run the following command to check the current status of TigerGraph. The services *"ADMIN", "CTRL", "ETCD", "IFM", "KAFKA", and "ZK" are started automatically* and should be up at this point. If any of them are not or you get the following error message, *please wait for 30 to 60 seconds and check the status again* before reporting it to TigerGraph support.

[,text]
----
gadmin status
----

image::gadmin-status (3).png[]

image::gadmin-status-error-message (3).png[]

. Run the following command to start TigerGraph:

[,text]
----
gadmin start
----

image::gadmin-start (11).png[]

. Check the status again. All services should be up at this point:

[,text]
----
gadmin status
----

image::gadmin-status-after-start (3).png[]

. TigerGraph has been successfully started on your cloud instance.‌

== TigerGraph License on Google Cloud Images

The TigerGraph Enterprise edition image comes with *a perpetual license* that will *only work on the Google Cloud instance it's installed on*. Please run the following command to see it:

[,text]
----
gadmin license status
----

image::gadmin-license-status (4).png[]
