= Stream from an External Kafka Cluster (Deprecated)
//:page-aliases: data-loading:kafka-loader:load-data.adoc
:sectnums:

[NOTE]
This describes support for data loading from an External Kafka Cluster for v3.9.2 and earlier.
If you have v3.9.3 or higher, we recommend that you use xref:data-loading:load-from-kafka.adoc[].

You can create a data connector to stream data from an external Kafka cluster (source cluster) to a destination cluster, which is often TigerGraph's internal Kafka cluster.
If the data from the source cluster is in AVRO format, the connector can transform the data into JSON format.
You can then create and run a loading job to load data from the destination cluster into graphs in your database using the Kafka loader.

== Prerequisites

* Your TigerGraph instance has access to your external Kafka cluster

== Procedure

=== Specify connector configurations
Before creating the connector, you must provide the required connector configurations.
This includes <<_basic_configurations, basic configurations>> and <<_subsection_configurations, subsection configurations>>.

The data streaming connector for external Kafka data is based on Apache Kafka MirrorMaker and shares many configurations as MirrorMaker.

[#_basic_configurations]
==== Basic configurations

The configurations in this subsection specify basic characteristics of the connector such as connector class, the addresses of the source and destination clusters, as well as the converters used to covert Kafka Connect format and the serialized form that is written to Kafka.

The following configurations are *required*:

|===
|Field |Description |Example value

|`connector.class`
|Must be set to `org.apache.kafka.connect.mirror.MirrorSourceConnector`.
This class of connectors connect a source Kafka cluster to a destination Kafka cluster.
|`connector.class=org.apache.kafka.connect.mirror.MirrorSourceConnector`

|`source.cluster.alias`
|Alias of source Kafka cluster in string format
|`source.cluster.alias=source-cluster`

|`target.cluster.alias`
|Alias of destination Kafka cluster in string format
|`target.cluster.alias=tg-cluster`

|`source.cluster.bootstrap.servers`
|Address of the external source Kafka cluster
|`source.cluster.bootstrap.servers=localhost:9092`

|`target.cluster.bootstrap.servers`
|Address of destination Kafka cluster, which is the Kafka component inside TigerGraph. The ip address can be fetched via gmyip, and default port is 30002.
|`target.cluster.bootstrap.servers=localhost:30002`

|`source->target.enabled`
|Enables source-to-target mirroring.
This field must be set to `true`.
|`source->target.enabled=true`

|`topics`
|Topic names to be loaded into TigerGraph, split by comma `,`
|`topics=test-topic`

|`key.converter`
|Converter class used to convert between Kafka Connect format and the serialized form that is written to Kafka.
This controls the format of the keys in messages written to or read from Kafka,
Must be set to `org.apache.kafka.connect.converters.ByteArrayConverter`.

|`key.converter=org.apache.kafka.connect.converters.ByteArrayConverter`

|`header.converter`
|Converter class used to convert between Kafka Connect format and the serialized form that is written to Kafka.
This controls the format of the headers in messages written to or read from Kafka.
Must be set to `org.apache.kafka.connect.converters.ByteArrayConverter`.
|`header.converter=org.apache.kafka.connect.converters.ByteArrayConverter`

|`value.converter`
a|Converter class used to convert between Kafka Connect format and the serialized form that is written to Kafka.
This controls the format of the values in messages written to or read from Kafka.

* If records are in Avro format with Schema Registry service, this field should be `com.tigergraph.kafka.connect.converters.TigerGraphAvroConverter`.

* If records are in Avro format without using Schema Registry service, this field should be `com.tigergraph.kafka.connect.converters.TigerGraphAvroConverterWithoutSchemaRegistry`.

* If records are in plaintext or JSON format, this field should be `org.apache.kafka.connect.converters.ByteArrayConverter`.
|`value.converter=com.tigergraph.kafka.connect.converters.TigerGraphAvroConverter`

|`value.converter.schema.registry.url`|
URL of the schema registry service.
Required if  `value.converter` is `com.tigergraph.kafka.connect.converters.TigerGraphAvroConverter`.
For details, see https://docs.confluent.io/platform/current/schema-registry/connect.html#example-converter-properties[Confluent documentation].|`\http://localhost:8081`

| `sync.topic.configs.enabled`
|Whether to replicate topic configurations from the source cluster. This is set to `true` by default in the Kafka source code.
In a TigerGraph context, set it to `false` as the config of the source Kafka topic is not necessary to sync data.
Only set this to `true` when using Cross-Region Replication (CRR).
| `false`


|===

Other configuration options are available to fine-tune the connector.
All configuration options are in https://kafka.apache.org/documentation/#georeplication-mirrormaker[Kafka MirrorMaker Configurations].

==== SSL/SASL configurations (optional)
If the source cluster has configured SSL or SASL protocols, you need to provide SSL/SASL configurations to the connector in order to communicate with the source cluster.

You need to upload the following credential files to your TigerGraph cluster:

* If the source cluster uses SASL, you need to upload the keytab of each Kerberos principal to every node of your TigerGraph cluster at the same absolute path.
* If the source cluster uses SSL, you need to upload the trust store and key store to every node of your TigerGraph cluster.
Each file must be at the same absolute path on all nodes.
* If the source cluster uses SASL and SSL, you need to upload the keytab of each Kerberos principal, as well as the key store and truststore to every node of your TigerGraph cluster.
Each file must be at the same absolute path on all nodes.

The following configurations are required for admin, producer and consumer.
To supply the configuration for the corresponding component, replace `<prefix>` with `source.admin`, `producer`, or `consumer`.
For example, to specify `GSSAPI` as the SASL mechanism for producer, put `producer.sasl.mecahnism=GSSAPI`:

|===
|Field |Description

|`<prefix>.security.protocol`
|Protocol used to communicate with brokers. Valid values are: `PLAINTEXT`, `SSL`, `SASL_PLAINTEXT`, `SASL_SSL`.


|`<prefix>.sasl.mechanism`
|SASL mechanism used for client connections. This may be any mechanism for which a security provider is available. GSSAPI is the default mechanism


|`<prefix>.sasl.kerberos.service.name`
|The Kerberos principal name that Kafka runs as. This can be defined either in Kafka's JAAS config or in Kafka's config.



|`<prefix>.sasl.jaas.config`
|JAAS login context parameters for SASL connections in the format used by JAAS configuration files.
See link:https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/tutorials/LoginConfigFile.html[JAAS Login Configuration File] for details.


|`<prefix>.ssl.endpoint.identification.algorithm`
|
The endpoint identification algorithm to validate server hostname using server certificate. Default is https. Disable server host name verification by setting `ssl.endpoint.identification.algorithm` to an empty string


|`<prefix>.ssl.keystore.location`
|The location of the key store file.


|`<prefix>.ssl.keystore.password`
|The password of the key store file.


|`<prefix>.ssl.key.password`
|The password of the private key in the key store file or the PEM key specified in `ssl.keystore.key`.


|`<prefix>.ssl.truststore.location`
|The location of the trust store file.

|`<prefix>.ssl.truststore.password`
|The password for the trust store file.

|===

[#_subsection_configurations]
==== Subsection configurations
The subsection configurations come after the other configurations, and specify the names of the connectors you want to create using the provided configurations before the subsections, as well as the maximum number of tasks that can be created for the connector.

You can create one or more connectors from one configuration file by providing a subsection for each connector you want to create.
In the case of the MirrorMaker connector class used in this procedure, *we suggest you only create one connector from each file*, due to limited available configurations in the subsection.
If you create multiple connectors, they will have almost identical properties.

Start a subsection with a section title enclosed in square brackets.
This title has no effect on the connector to be created, but the titles need to be unique in the configuration file.

The following subsection configurations are available:


|===
|Field |Description

|`name`
|Name of the connector.

|`tasks.max`
|
The maximum number of tasks that to be created for this connector.
The connector may create fewer tasks if it cannot achieve this level of parallelism.
The value for this configuration should not be larger than the number of partitions of the topic(s) in source Kafka.
The default value is 1.
|===


==== Example
The following is an example configuration file:

[,text]
----
include::example$config-avro[]
----

The file in the example creates a connector named `avro-test-without-registry` with all configurations specified in the file.

include::partial$create-connector.adoc[]

include::partial$create-data-source.adoc[]

include::partial$create-loading-job-kafka.adoc[]

For example, suppose we have the following graph schema with only one vertex type
and the following JSON line data in the destination Kafka:

[tabs]
====
Schema::
+
--
[.wrap,gsql]
----
CREATE VERTEX Company (primary_id name STRING, employee_num INT)
CREATE GRAPH Company_Graph (Company)
----
--
Data::
+
--
[.wrap,json]
----
{"company":"TigerGraph","employee_num":346}
{"company":"Apple","employee_num":373704}
{"company":"Google","employee_num":277618}
----
--
====

To create the loading job, we start by creating a data source configuration file.
We then point it to the Kafka cluster and create the data source:

[tabs]
====
Data source configuration::
+
--
[.wrap,json]
----
    {
        "broker":"localhost:30002",
        "kafka_config":
            {
                "group.id": "tigergraph"
            }
    }
----
--
Create data source::
+
--
Run the following command in GSQL and replace `<path_to_datasource_file` with the absolute path to your data source file to create the data source.
[.wrap,gsql]
----
CREATE DATA_SOURCE KAFKA k1=<path_to_datasource_file>
----
--
====

Then we create a topic-partition configuration file, and then write the loading job.
In the `LOAD` statement, map the JSON line fields to the corresponding attributes of the vertex types:

[tabs]
====
Topic-partition configuration file::
+
--
[.wrap,json]
----
{
    "topic": "Hello.avro-with-registry-topic",
    "default_start_offset": -2
}
----
--
Loading job::
+
--
[.wrap,gsql]
----
CREATE LOADING JOB load_company FOR GRAPH Company_Graph {
    DEFINE FILENAME f1 =
      "$k1:<path_to_topic_partition_configuration>}";
    LOAD f1 TO VERTEX company VALUES ($"company", $"employee_num")
      USING JSON_FILE="true";
}
----
--
====

Once the loading job is created, run the loading job to load data into the graph:

[.wrap,gsql]
----
RUN LOADING JOB -noprint load_company USING EOF="true"
----

There are two modes for the Kafka Loader: EOF mode and streaming mode.

* In EOF mode, loading stops after consuming the current Kafka messages.
* In streaming mode, loading never stops until the job is aborted.

Starting from v3.9.2, the default mode is EOF mode. +
Prior to v3.9.2, the default mode was streaming mode.

To set streaming mode, an optional parameter, `USING EOF="false"`  is added to the `RUN LOADING JOB` syntax:

[.wrap,gsql]
----
RUN LOADING JOB -noprint load_company USING EOF="false"
----