= Log Files

TigerGraph logs are all stored in the `log` root directory.

This is configured at install time and set to `/home/tigergraph/tigergraph/log` as the default location.

Within this directory are separate directories for the various TigerGraph services:

[source.wrap,bash]
----
$ ls /home/tigergraph/tigergraph/log
admin       dict  executor    gpe  gsql  informant  kafkaconn     nginx   ts3      zk
controller  etcd  fileLoader  gse  gui   kafka      kafkastrm-ll  restpp  ts3serv
----

Additionally, one can use the `gadmin log` command to list log files:

[source,bash]
----
$ gadmin log
ADMIN  : /home/tigergraph/tigergraph/log/admin/ADMIN#1.out
ADMIN  : /home/tigergraph/tigergraph/log/admin/ADMIN.INFO
CTRL   : /home/tigergraph/tigergraph/log/controller/CTRL#1.log
CTRL   : /home/tigergraph/tigergraph/log/controller/CTRL#1.out
DICT   : /home/tigergraph/tigergraph/log/dict/DICT#1.out
DICT   : /home/tigergraph/tigergraph/log/dict/DICT.INFO
ETCD   : /home/tigergraph/tigergraph/log/etcd/ETCD#1.out
EXE    : /home/tigergraph/tigergraph/log/executor/EXE_1.log
EXE    : /home/tigergraph/tigergraph/log/executor/EXE_1.out
GPE    : /home/tigergraph/tigergraph/log/gpe/GPE_1#1.out
GPE    : /home/tigergraph/tigergraph/log/gpe/log.INFO
GSE    : /home/tigergraph/tigergraph/log/gse/GSE_1#1.out
GSE    : /home/tigergraph/tigergraph/log/gse/log.INFO
GSQL   : /home/tigergraph/tigergraph/log/gsql/GSQL#1.out
GSQL   : /home/tigergraph/tigergraph/log/gsql/log.INFO
GUI    : /home/tigergraph/tigergraph/log/gui/GUI#1.out
IFM    : /home/tigergraph/tigergraph/log/informant/IFM#1.log
IFM    : /home/tigergraph/tigergraph/log/informant/IFM#1.out
KAFKA  : /home/tigergraph/tigergraph/log/kafka/controller.log
KAFKA  : /home/tigergraph/tigergraph/log/kafka/kafka-request.log
KAFKA  : /home/tigergraph/tigergraph/log/kafka/kafka.log
KAFKA  : /home/tigergraph/tigergraph/log/kafka/server.log
KAFKA  : /home/tigergraph/tigergraph/log/kafka/state-change.log
KAFKACONN: /home/tigergraph/tigergraph/log/kafkaconn/KAFKACONN#1.out
KAFKACONN: /home/tigergraph/tigergraph/log/kafkaconn/kafkaconn.log
KAFKASTRM-LL: /home/tigergraph/tigergraph/log/kafkastrm-ll/KAFKASTRM-LL_1.out
KAFKASTRM-LL: /home/tigergraph/tigergraph/log/kafkastrm-ll/kafkastrm-ll.log
NGINX  : /home/tigergraph/tigergraph/log/nginx/logs/NGINX#1.out
NGINX  : /home/tigergraph/tigergraph/log/nginx/logs/error.log
RESTPP : /home/tigergraph/tigergraph/log/restpp/RESTPP#1.INFO
RESTPP : /home/tigergraph/tigergraph/log/restpp/RESTPP#1.out
RESTPP-LOADER: /home/tigergraph/tigergraph/log/fileLoader/RESTPP-LOADER_1#1.INFO
TS3    : /home/tigergraph/tigergraph/log/ts3/TS3_1.log
TS3    : /home/tigergraph/tigergraph/log/ts3/TS3_1.out
TS3SERV: /home/tigergraph/tigergraph/log/ts3serv/TS3SERV#1.out
ZK     : /home/tigergraph/tigergraph/log/zk/ZK#1.out
ZK     : /home/tigergraph/tigergraph/log/zk/zookeeper.log
----

Use the command `gadmin log <service name>` to just get the logs for a specific service:

[source,bash]
----
$ gadmin log gpe
GPE    : /home/tigergraph/tigergraph/log/gpe/GPE_1#1.out
GPE    : /home/tigergraph/tigergraph/log/gpe/log.INFO
----

The `log.INFO` file contains messages logged by the application code.
The `.out` log contains the redirection of the process output, and is used for debugging significantly less frequently than `log.INFO`.

[CAUTION]
The log format differs between the `.out` and `INFO` logs. It also differs between certain TigerGraph components. An internal project to unify log formats is ongoing.

Inside each of the log directories for the TigerGraph services are a number of different files:

. log.INFO, log.WARNING, and log.ERROR.
These are all symbolic links to the latest INFO, WARNING, or ERROR level log. There is also a log.DEBUG,
if the log level config for that service is set to DEBUG instead of the default INFO. Additionally, there will be a log.FATAL if any fatal level events are logged.
. INFO, WARNING, ERROR level logs. The filename has the form:
LOGLEVEL.YYYYMMDD-HHMMSS.fffff
For example: INFO.20220621-213945.13651
Note that the warning logs will include all error level messages as well as warning, and the info logs will include all warning and error level messages, as well as info.
. Current and historical .out logs. Current .out log will have the form servicename.out, historical ones will have the form servicename-old-YYYY-MM-DDTHH-MM-SS.fff.out
For example: GPE_1#1.out and GPE_1#1-old-2022-06-28T00-52-24.178.out

Note that the open source components that TigerGraph includes (Kafka, Nginx, ZooKeeper, Kafkaconn, Kafkastream) follow the logging behavior of that project instead of having a INFO/WARNING/ERROR log, in addition to having a .out file for the process output redirection. For example, the Kafka logs have a controller.log, kafka.log, kafka-request.log, state-change.log, and server.log.

Finally, TigerGraph also handles log rotation. When the log is rotated, the log.LEVEL symlink will be updated to point to the newest log. The default configuration is to rotate under the following circumstances:

* Log file max size exceeds 100mb
* Log is older than 90 days
* There are more than 100 files for that service
