= Kubernetes
//:page-aliases: README.adoc, readme.adoc
:description: Overview of running TigerGraph on Kubernetes.

TigerGraph supports deployment on Kubernetes.
You can deploy TigerGraph single servers and clusters using Kubernetes on any cloud provider of your choice.

TigerGraph provides its custom Kubernetes Operator to help you automate TigerGraph operations such as the creation, status checking and deletion of TigerGraph clusters.

//IMPORTANT: Kubernetes Operator support is currently a Preview Feature. Preview Features give users an early look at future production-level features. Preview Features should not be used for production deployments.


The xref:kubernetes/k8s-operator.adoc[Kubernetes Operator]
provides two main benefits over Kubernetes Classic:

* *Custom Resources*: Define custom resources that represent your application's state and behavior.
This allows you to manage a TigerGraph cluster in a more natural and intuitive way.

* *Automation*: Automate many of the tasks involved in managing a cluster, such as deployment, resource updates, upgrades, cluster size changes, backup, and restore.


== Kubernetes Classic (Deprecated)

Previous versions of TigerGraph used a different implementation of Kubernetes.
The older versions may still be functional, but are no longer supported.
For long-term support and enhancement, use the Operator instead.


