= Kubernetes Operator
:page-aliases: k8s-operator:index.adoc
:description: Introduction to TigerGraph Kubernetes Operator.

The TigerGraph Kubernetes Operator provides native integration of TigerGraph Server with Kubernetes.

It enables you to automate operations such as the creation, status checking, resizing and deletion of TigerGraph clusters. By reducing the complexity of running a TigerGraph cluster, it lets you focus on the desired state of your clusters and saves you time from the details of manual deployment and life-cycle management.

//IMPORTANT: Kubernetes Operator support is currently a Preview Feature. Preview Features give users an early look at future production-level features. Preview Features should not be used for production deployments.

NOTE:The documentation for TigerGraph's Kubernetes operator is on our https://github.com/tigergraph/ecosys/tree/master/k8s/README.md[GitHub Repository]. These docs are frequently updated to support operation, troubleshooting, and all other relevant use cases.


== Getting started

To get started go to our https://github.com/tigergraph/ecosys/blob/master/k8s/docs/02-get-started/get_started.md[Get Started] GitHub page where you will install the Operator and provision your first cluster using the Operator.


== Supported cloud platforms
The TigerGraph Kubernetes Operator is platform-agnostic.
You should be able to use the Operator on any cloud platform that provides a Kubernetes service.
TigerGraph has verified the full functionality of the operator on the Kubernetes services of the following platform:

* https://github.com/tigergraph/ecosys/blob/master/k8s/docs/03-deploy/tigergraph-on-gke.md[Google Kubernetes Engine (GKE)]
* https://github.com/tigergraph/ecosys/blob/master/k8s/docs/03-deploy/tigergraph-on-openshift.md[Red Hat OpenShift]
* https://github.com/tigergraph/ecosys/blob/master/k8s/docs/03-deploy/tigergraph-on-eks.md[AWS Elastic Kubernetes Service (EKS)]
* https://github.com/tigergraph/ecosys/blob/master/k8s/docs/03-deploy/tigergraph-on-aks.md[Azure Kubernetes Service (AKS)]

Additionally, TigerGraph Kubernetes Operator can be installed and deployed without internet access

* https://github.com/tigergraph/ecosys/blob/master/k8s/docs/03-deploy/deploy-without-internet.md[Install and Deploy without internet access]
