= Kubernetes Operator
:description: Introduction to TigerGraph Kubernetes Operator.

The TigerGraph Kubernetes Operator provides native integration of TigerGraph Server with Kubernetes.

It enables you to automate operations such as the creation, status checking, resizing and deletion of TigerGraph clusters. By reducing the complexity of running a TigerGraph cluster, it lets you focus on the desired state of your clusters and saves you time from the details of manual deployment and life-cycle management.

IMPORTANT: Kubernetes Operator support is currently a Preview Feature. Preview Features give users an early look at future production-level features. Preview Features should not be used for production deployments.

NOTE: Additionally, we have provided a public GitHub repo (https://github.com/tigergraph/ecosys/tree/master/k8s) to our preview documentation of the Kubernetes Operator. These docs are frequently updated to support operation, troubleshooting, and all other relevant use cases.

The Operator provides the following features:

* Cluster Provisioning
* Cluster Deletion
* Listing Clusters
* Checking Cluster Status
* Shrink or Expand a Cluster
* Backup and Restore

//* xref:k8s-operator/cluster-operations.txt#_create_tigergraph_clusters[Cluster provisioning]
//* xref:k8s-operator/cluster-operations.txt#_delete_tigergraph_clusters[Cluster deletion]
//* xref:k8s-operator/cluster-operations.txt#_list_tigergraph_clusters[Listing clusters]
//* xref:k8s-operator/cluster-operations.txt#_check_cluster_version_and_status[Checking cluster status]
//* xref:k8s-operator/cluster-operations.txt#_shrink_expand_cluster[Shrink or expand a cluster]
//* xref:k8s-operator/backup-and-restore.txt[]

Moreover,

* [3.9.2+] Clusters can contain custom containers and volumes.
//* Clusters can contain xref:tigergraph-server:kubernetes:k8s-operator/custom-containers.txt[custom containers and volumes] [3.9.2+]

== Getting started

To get started go to our xref:https://github.com/tigergraph/ecosys/blob/master/k8s/docs/02-get-started/get_started.md[Get Started] GitHub page where you will install the Operator and provision your first cluster using the Operator.

//* xref:k8s-operator/installation.txt[]
//* xref:k8s-operator/cluster-operations.txt#_create_tigergraph_clusters[Create clusters]

== Supported cloud platforms
The TigerGraph Kubernetes Operator is platform-agnostic.
You should be able to use the Operator on any cloud platform that provides a Kubernetes service.
TigerGraph has verified the full functionality of the operator on the Kubernetes services of the following platform:

* Google Kubernetes Engine (GKE)
* Azure Kubernetes Service (AKS)
* AWS Elastic Kubernetes Service (EKS)


