= Kubernetes Operator
:description: Introduction to TigerGraph Kubernetes Operator.

The TigerGraph Kubernetes Operator provides native integration of TigerGraph Server with Kubernetes.
It enables you to automate TigerGraph operations such as the creation, status checking and deletion of TigerGraph clusters.

By reducing the complexity of running a TigerGraph cluster, it lets you focus on the desired state of your clusters and saves you time from the details of manual deployment and life-cycle management.

The Operator provides the following features:

* xref:k8s-operator/cluster-operations.adoc#_create_tigergraph_clusters[Cluster provisioning]
* xref:k8s-operator/cluster-operations.adoc#_delete_tigergraph_clusters[Cluster deletion]
* xref:k8s-operator/cluster-operations.adoc#_list_tigergraph_clusters[Listing clusters]
* xref:k8s-operator/cluster-operations.adoc#_check_cluster_status[Checking cluster status]

== Getting started

Install the Operator and provision your first cluster using the Operator to get started:

* xref:k8s-operator/installation.adoc[]
* xref:k8s-operator/cluster-operations.adoc#_create_tigergraph_clusters[Create clusters]


