= Kubernetes Operator
:description: Introduction to TigerGraph Kubernetes Operator.

The TigerGraph Kubernetes Operator provides native integration of TigerGraph Server with Kubernetes.
It enables you to automate operations such as the creation, status checking, resizing and deletion of TigerGraph clusters.

By reducing the complexity of running a TigerGraph cluster, it lets you focus on the desired state of your clusters and saves you time from the details of manual deployment and life-cycle management.

The Operator provides the following features:

* xref:k8s-operator/cluster-operations.adoc#_create_tigergraph_clusters[Cluster provisioning]
* xref:k8s-operator/cluster-operations.adoc#_delete_tigergraph_clusters[Cluster deletion]
* xref:k8s-operator/cluster-operations.adoc#_list_tigergraph_clusters[Listing clusters]
* xref:k8s-operator/cluster-operations.adoc#_check_cluster_status[Checking cluster status]
* xref:k8s-operator/cluster-operations.adoc#_shrink_expand_cluster[Shrink or expand a cluster]
* xref:k8s-operator/backup-and-restore.adoc[]

== Getting started

Install the Operator and provision your first cluster using the Operator to get started:

* xref:k8s-operator/installation.adoc[]
* xref:k8s-operator/cluster-operations.adoc#_create_tigergraph_clusters[Create clusters]

== Supported cloud platforms
The TigerGraph Kubernetes Operator is platform-agnostic.
You should be able to use the Operator on any cloud platform that provides a Kubernetes service.
TigerGraph has verified the full functionality of the operator on the Kubernetes services of the following platform:

* Google Kubernetes Engine (GKE)
* Azure Kubernetes Service (AKS)
* AWS Elastic Kubernetes Service (EKS)


