= Installing TigerGraph Kubernetes Operator
:description: Instructions on how to install TigerGraph Kubernetes Operator.
:sectnums:

This page describes the steps to install TigerGraph Kubernetes Operator on your Kubernetes cluster.

NOTE: The Operator only needs to be installed once for each cluster.
If you run into errors saying that Custom Resource Definition (CRD) already exists, it is likely that someone else who has access to your cluster has already installed the operator.
Therefore, you can safely ignore the error and skip installation.

== Prerequisites
* You have configured the `kubectl` command-line tool for access to your running Kubernetes cluster.
* Helm is installed on your local machine.
* https://cert-manager.io/docs/installation/kubectl/[cert-manager is installed on your Kubernetes cluster].
* If you are pulling from a private registry, configure your cluster for access to the registry.
You can do this by https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret[creating a Secret] and https://kubernetes.io/docs/concepts/configuration/secret/#use-case-as-container-environment-variables[using it as a container environment variable].

== Procedure

[#_install_the_tigergraph_kubectl_plugin]
=== Install the TigerGraph `kubectl` plugin
Run the command below to install the TigerGraph plugin for the `kubectl` command-line tool:

[.wrap,console]
----

----

The plugin is installed on your local machine.
You do not need to install the plugin for each cluster you operate on.


=== Initialize TigerGraph Kubernetes Operator
Run the command below to initialize the TigerGraph Kubernetes Operator.

[.wrap,console]
----
$ kubectl tg init --helm-repo http://docker.tigergraph.com
----

If you are using a private helm repository, replace `http://docker.tigergraph.com` with the URL of your repository, and supply the name of your Secret:

[.wrap,console]
----
$ kubectl tg init --helm-repo <private_repo_url> -p <secret_name>
----



