= List of Legacy Privilege Syntax

This page provides a complete list of privileges in TigerGraph's Role-based Access Control system.


== Legacy Privilege Syntax Limitations
* Any privilege marked "`Global only`" can only be granted to a global role.
It cannot be granted to a local role (See xref:user-access:access-control-model.adoc[Global role vs local role]).

* Local roles are deprecated and will be dropped in a later version.

* As of 3.10.0, when using the legacy privilege syntax, a user will receive a warning when trying to grant or revoke a privilege.

* Legacy privilege syntax for function privileges is only supported on the global scope.
** To add function privileges, it's best to use the Object-Based Privileges syntax.

[NOTE]
====
It’s recommended to use the xref:tigergraph-server:user-access:rbac-row-policy/rbac-row-policy.adoc#_object_based_privileges[Object-Based Privileges] syntax.
See xref:tigergraph-server:user-access:rbac-row-policy/row-policy-privlages-table.adoc[] for a comparison with the legacy syntax.
====



== Table of Privileges
[width="100%",cols="22%,63%,15%",options="header",]
|===
|*Privilege Name* |*Commands Associated* |*Global Only*
|`READ_SCHEMA`
a|* `ls`
  * `show vertex <vName>`
  * `show edge <eName>`
  * `show graph <gName>`
  * `show job (<schema_changeJobName>`
|No

|`WRITE_SCHEMA`
a|* `create schema_change job <scjName>`
* `run schema_change job <scjName>`
* `drop schema_change job <scjName>`
* `create vertex <vName>`
* `drop vertex <vName>`
* `create edge <eName>`
* `drop edge <eName>`
* `create graph <gName>`
* `create global schema_change job <gscjName>`
* `run global schema_change job <gscjName>`
* `drop global schema_change job <gscjName>`
|No

|`READ_LOADINGJOB`
a|* `show job <loadingJobName>`
* `show data_source <dsName>`
|No

|`EXECUTE_LOADINGJOB`
a|* `run loading job <ljName>`
* `show loading status <jobId>`
* `abort loading job <ljName>`
* `resume loading job <ljName>`
|No

|`WRITE_LOADINGJOB`
a|* `create loading job <ljName>`
* `drop loading job <ljName>` |No

|`READ_QUERY` |`show query <qName>` |No

|`WRITE_QUERY`
a|* `create query <qName>`
* `install query <qName>`
* `drop query <qName>`
|No

|`CREATE_DATA`|
Running queries that insert vertices or edges in the allowed scope.
For details see xref:user-access:access-control-model.adoc#_data_crud_privileges[Data CRUD privileges].|No

|`READ_DATA` |
Running queries that read vertex or edge information in the allowed scope.
For details see xref:user-access:access-control-model.adoc#_data_crud_privileges[Data CRUD privileges].
|No

|`UPDATE_DATA`
a|Running queries that update vertex or edge information in the allowed scope.
For details see xref:user-access:access-control-model.adoc#_data_crud_privileges[Data CRUD privileges].
|No

|`DELETE_DATA`
|Running queries that delete vertices or edges in the allowed scope.
For details see xref:user-access:access-control-model.adoc#_data_crud_privileges[Data CRUD privileges].
|No

|`WRITE_DATASOURCE`
a|* `create data_source <dsName>`
* `grant data_source <dsName>`
* `revoke data_source <dsName>`
* `drop data_source <dsName>`
|No

|`READ_ROLE` a|* `show role`
* `show privilege on role <rName>` |No

|`WRITE_ROLE`
a|* `create role <rName>`
* `grant role <rName>`
* `revoke role <rName>`
* `drop role <rName>`
* `grant privilege <pName> on graph <gName> to <rName>`
* `revoke privilege <pName> on graph <gName> from <rName>`
|No

|`READ_USER`
a|* `show user`
* `show privilege on user <uName>`
* `show secret`
|No

|`WRITE_USER`
a|* `create user <uName>`
* `drop user <uName>`
* `alter password`
|Yes

|`READ_PROXYGROUP` |`show group` |No

|`WRITE_PROXYGROUP`
a|* `create group <pgName> proxy <rule>`
* `drop group <pgName>`
|Yes

|`READ_FILE` |`get <fileName> to <path-to-file>` |Yes

|`WRITE_FILE` |`put <fileName> from <path-to-file>` |Yes

|`DROP_GRAPH` |`drop graph <gName>` |Yes

|`EXPORT_GRAPH` |`export graph <gName>` |Yes

|`CLEAR_GRAPHSTORE` |`clear graph store` |Yes

|`ACCESS_TAG`

[Dropped in 4.1]
|`ACCESS_TAG`

[Dropped in 4.1]
|`ACCESS_TAG`

[Dropped in 4.1]
|`ACCESS_TAG`

[Dropped in 4.1]

a|
* Operations with schema change jobs involving tags
* Operations with loading jobs involving tags
* Operations with queries involving tags
| No

|`APP_ACCESS_DATA`
|Accessing data through TigerGraph Suite applications including GraphStudio and TigerGraph Insights.

This privilege only allows you to access the information through TigerGraph Suite applications if you already have access to the data in GSQL.
It only pertains to the applications and does not have meaning in GSQL itself.
|

|`DROP_ALL`
| `drop all`
| Yes
|===
