=== Database Connection

.Predefined connection options:
[source, scala]
----
val tgOptions = Map(
    "url" -> "http(s)://<tg_node_host>:<tg_nginx_port>",
    "version" -> "<tg_version>",
    "graph" -> "<graph_name>",
    "username" -> "<username>",
    "password" -> "<password>"
)
----

*Some Helpful tips*

* **Connection options object**

To simplify configuration, you can bundle the options related to database connection in a data object (e.g., `tgOptions`) and then use `.options(tgOptions)` when running the connector. This approach helps keep user credentials separate from connection commands.

* **High Availability**

To ensure fault tolerance, provide a list of all node `URLs` in the `url` option for the connector:

[source,json]
----
"url" -> "https://m1:14240,https://m2:14240,https://m3:14240,https://m4:14240",
----

=== Authentication Methods

[NOTE]
====
In version *4.2*, TigerGraph's Spark Connector supports `OAuth2` authentication, enabling it to request JWT tokens from third-party Identity Providers (IdPs) like `Azure AD` and `Auth0`, enhancing security and token management for Spark jobs.
====

We recommend using *OAuth2* for authentication. Our implementation supports automatic token requests and refresh, and is more secure that *username/password*, offering convenience and security for both batch and streaming jobs. 

The Spark connector now supports the following authentication methods:

* `oauth2`: Recommended for both batch and streaming jobs. The token is automatically requested and refreshed using `oauth2.url` and `oauth2.parameters`.
* `token`: Suitable for one-time Spark jobs, but lacks support for refresh tokens.
* `username/password`: Works for both batch and streaming jobs, but is considered an older, less secure method. The token is automatically requested and refreshed.
* `secret`: Also works for batch and streaming jobs, and the token is managed using the GSQL secret, but is less secure compared to OAuth2.
