=== Database Connection

[TIP]
.Connection options object
====
You may find it convenient to bundle the options related to making a database connection in a data object (e.g., `tgOptions`) and then use `.options(tgOptions)` when running the connector.
Moreover, placing the user credentials in a data object keeps them separate from the connection commands.
====

.Predefined connection options:
[source, scala]
----
val tgOptions = Map(
    "url" -> "http(s)://<tg_node_host>:<tg_nginx_port>",
    "version" -> "<tg_version>",
    "graph" -> "<graph_name>",
    "username" -> "<username>",
    "password" -> "<password>"
)
----

[NOTE]
====
If you’re running long queries through the Spark connector and a load balancer (for example, Azure Load Balancer) is between Spark and TigerGraph, increase the load balancer’s idle timeout to prevent the connection from timing out.
====

[TIP]
.Authentication methods
====
Using username/password has the advantage that this authentication method will automatically refresh an access token as needed.

If you choose to use a token, please make sure the lifetime of the token is long enough for the loading job.
====
