=== Database Connection

.Predefined connection options:
[source, scala]
----
val tgOptions = Map(
    "url" -> "http(s)://<tg_node_host>:<tg_nginx_port>",
    "version" -> "<tg_version>",
    "graph" -> "<graph_name>",
    "username" -> "<username>",
    "password" -> "<password>"
)
----

==== Some Helpful tips

* **Connection options object**

To simplify configuration, you can bundle the options related to database connection in a data object (e.g., `tgOptions`) and then use `.options(tgOptions)` when running the connector. This approach helps keep user credentials separate from connection commands.

* **Authentication methods**

We recommend using username/password or secret-based authentication over a fixed token, as these allow for automatic token refresh.

The Spark connector now supports the following authentication methods:

. `token`: Suitable for one-time Spark jobs, without refresh token support.
. `username/password`: Works for both batch and streaming jobs. The token is automatically requested and refreshed.
. `secret`: Also supports both batch and streaming jobs. The token is automatically managed using the GSQL secret.
. `oauth2`: Can be used for both batch and streaming jobs. The token is automatically requested and refreshed using `oauth2.url` and `oauth2.parameters`.

* **High Availability**

To ensure fault tolerance, provide a list of all node `URLs` in the `url` option for the connector:

[source,json]
----
"url" -> "https://m1:14240,https://m2:14240,https://m3:14240,https://m4:14240",
----