= Kafka Loader Loading Job Management

Kafka Loader loading jobs are managed the same way as regular loading jobs. The three key commands are

* `SHOW LOADING STATUS`
* `ABORT LOADING JOB`
* `RESUME LOADING JOB`

For example, the syntax for the `SHOW LOADING STATUS` command is as follows:

[source,gsql]
----
SHOW LOADING STATUS job_id|ALL
----

To refer to a specific job instance, using the job_id which is provided when `RUN LOADING JOB` is executed. For each loading job, the above command reports the following information :

* Current loaded offset for each partition
* Average loading speed
* Loaded size
* Duration

See https://docs.tigergraph.com/dev/gsql-ref/ddl-and-loading/running-a-loading-job#inspecting-and-managing-loading-jobs[Inspecting and Managing Loading Jobs] for more details.

[#_enable_concurrent_loading_jobs]
== Enable concurrent loading jobs

TigerGraph limits the number of running Kafka Loader loading jobs to 1 by default.
You can increase this limit by changing the following configuration:

[.wrap,console]
----
$ gadmin config set KafkaLoader.ReplicaNumber <new_limit>
$ gadmin config apply -y && gadmin restart gse gpe restpp -y
----

