[NOTE]
We currently support xref:#BigQuery[BigQuery], xref:Snowflake[Snowflake], and xref:_postgresql[] data warehouses.
More data warehouses will be supported in future releases.

=== BigQuery

TigerGraph's BigQuery loader makes use of the https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers[BigQuery JDBC connector provided by Google], in collaboration with Simba.
Use the following configuration for the `DATA_SOURCE`.

[source,json,linenums]
.Data source configuration for BigQuery
----
{
  "type":"bigquery",
  "ProjectId":"tigergraph-dev",
  "OAuthType":2,
  "parameters" : {
    "OAuthRefreshToken":"<refresh token>",
    "OAuthClientId":"<client ID>.apps.googleusercontent.com",
    "OAuthClientSecret":"<client secret>"
    #other Simba JDBC parameters
  }
}
----

[IMPORTANT]
In addition, for large query results, we highly recommended specifying the following parameters:

[source,json,linenums]
.Addition parameter setting for large BigQuery results
----
"EnableHighThroughputAPI":"1" -> Storage Read API
"AllowLargeResults":"1" -> Large Query Result Support
"LargeResultDataset":"<target_dataset>" -> Storage for Temp Result
"LargeResultsDatasetExpirationTime":"<time_ms>" -> Expiration of Temp Result
----

For more information about Simba/Google BigQuery JDBC connection parameters, please refer the
https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers[BigQuery JDBC Installation and Configuration Guide].

=== Snowflake

[source,json,linenums]
.Data source configuration for Snowflake:
----
{
    "type":"snowflake",
    "connection.url":"jdbc:snowflake://https://<account_id>.snowflakecomputing.com/?db=<db>&schema=<schema>&role=<role>",
    "connection.user": "<username>",
    "connection.password": "<password>"
}
----

Alternately, key-pair authentication can be used. 
See Snowflake's document for more details on their support for https://docs.snowflake.com/en/user-guide/key-pair-auth[key-pair authentication and rotation].

.Data source configuration with key-pair authentication:
----
{
    "type":"snowflake",
    "connection.url":"jdbc:snowflake://https://<account_id>.snowflakecomputing.com/?db=<db>&schema=<schema>&role=<role>&private_key_file=<key_file>",
    "connection.user": "<userwithrsa>",
    "connection.password": "<anystring>"
}
----

[NOTE]
We recommend to use this version(OpenSSL 3.0.11 19 Sep 2023) to generate the key.
When the private key is provided, the `connection.password` is still required and can be set to any non-empty string.
Passing private key directly or using private key file with password is NOT supported.
More can be found in https://docs.snowflake.com/en/user-guide/key-pair-auth[Snowflake Docs]

[WARNING]
====
For Snowflake loading jobs only the default setting for `batch.max.rows` is set to `100000` for better performance.
====

Use the required fields below for a Snowflake data `DATA_SOURCE`:

.Required fields for Snowflake `DATA_SOURCE`
[col="3"separator=¦ ]
|===
¦ Field ¦ Example ¦ Notes

¦ connection.url
¦ `"jdbc:snowflake://https://
<account_id>.snowflakecomputing.com/?db=<db>&schema=<schema>&role=<role>",`
¦ It should start with `jdbc:snowflake:`
¦ connection.user ¦ "tigergraph" ¦
¦ connection.password ¦ "password" ¦ This will be masked and shown as `****`
¦ type ¦ "snowflake" ¦ This must be `snowflake`.
|===

=== PostgreSql

.Data source configuration for PostgreSql:
[source,json,linenums]
----
{
    "type":"postgresql",
    "host":"pg_address",
    "port": 5432,
    "connection.user":"postgres",
    "connection.password":"postgres",
    "db.name":"postgres"
}
----

These are some required and optional configuration parameters for connection and authentication with a PostgreSql data `DATA_SOURCE`.

.Fields for PostgreSql `DATA_SOURCE`
[col="3"separator=¦ ]
|===
¦ Field ¦ Example ¦ Notes

¦ host
¦ "postgresql_server_address"
¦ The PostgreSql server’s address.

This is *required*.

¦ port
¦ "5432"
¦ The port used by the PostgreSql server.

The default is set to `5432`.

¦ connection.user
¦ "postgres"
¦ The user of the PostgreSql server.

This is *required*

¦ connection.password
¦ "postgres"
¦ The password of the user.

This is *required*

¦ db.name
¦ "postgres"
¦ The database name.

This is *required*
|===

