NOTE: While a loading job may have multiple `FILENAME` variables , they must all refer to the same `DATA_SOURCE` object.

==== Data warehouse file descriptors

For data warehouses, you run a SQL query to get the data.
The file descriptor has three valid formats.
You can simply provide the SQL query statement. Or, you can provide optional configuration details, either in a JSON file or as inline JSON content.
[source,gsql,linenum]
DEFINE FILENAME file_name = "$[data source name]:[SQL]";
DEFINE FILENAME file_name = "$[data source name]:[json config file]";
DEFINE FILENAME file_name = "$[data source name]:[inline json content]";

For example:

[source,gsql]
----
// Format 1: SQL query statement
DEFINE FILENAME query_person = "$s1:SELECT id,name,gender FROM ldbc.person";

// Format 2: Configuration file
DEFINE FILENAME bq_inline_json = """$s1:myfile.json""";

// Format 3: Inline JSON
DEFINE FILENAME query_person="""$s1:{
  "query": "SELECT id,name,gender
            FROM ldbc.person where age < 10;
            SELECT id,name,gender
            FROM ldbc.person where age > 50",
  "num.partitions": 6,
  "tasks.max": 2
}""";
----

==== Filename parameters

These are the required and optional configuration parameters:

[%header,cols="1,4,1,4"]
|===
|Parameter |Description |Required? |Default value

|query
|One or more SQL queries separated by commas.
To avoid timeout in a large query, you can break it into multiple smaller queries based on the partitioning key.
These queries may be assigned to multiple tasks for execution, while the execution order is not guaranteed.
|Yes
|N/A

|batch.max.rows
|Maximum number of rows to include in a single batch when polling for new data from the query result.
|No
|1000

For Snowflake loading jobs only: The default setting for `batch.max.rows` is set to `100000` for better performance.

|tasks.max
|The maximum number of tasks used to execute queries.
When `query` contains multiple queries, you can increase this parameter to execute queries in parallel.
|No
|1

|poll.interval.ms
|Time interval in ms for periodic executoion of the query.
|No
|5000

|loading.timeout.ms
|The loading timeout per batch in milliseconds.

If set to 0, then the global parameter `RESTPP.Factory.DefaultLoadingTimeoutSec` is used.
|No
|0

|loading.max.retry.attempts
|The maximum number of retries after a retryable server error.

0 means an unlimited number of retries.
|No
|0

|io.max.retry.attempts
|The maximum number of HTTP transport retries.

0 means an unlimited number of retries.
|No
|0

|batch.size.bytes
|The maximum data batch size in bytes, overriding the `batch.size.rows` limit.

Example: If each row of data is 1000b, `batch.size.rows` = 10, and `batch.size.bytes` = 5000, then the data will be split into 2 5000b batches.
|No
|2,097,152 (2 MiB)

|num.partitions
|[Legacy: only used when gadmin parameter `KafkaConnect.EnableV2` is false] The number of partitions to use.
When loading data, each partition is distributed evenly across each node.
If one filename contains much more data than others, consider increasing this value.
|No
|3
|===
